title: Bookstacks
description: A curated library of public domain literature.
url: "https://bookstacks.org"
baseurl: ""

permalink: /:categories/:title/

exclude:
  - seed_indexes.py
  - .jekyll-cache
  - .sass-cache
  - vendor
