import re

en_text_4 = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter IV</head>
					<p>Anna Pávlovna smiled and promised to take Pierre in hand. She knew he was related to Prince Vasíli on his father's side. The elderly lady who had been sitting with <foreign xml:lang="fr" n="my aunt">ma tante</foreign> hurriedly rose and overtook Prince Vasíli in the anteroom. All the former affectation of interest had vanished from her face. Her kind, tear-stained face expressed only anxiety and fear.</p>
					<p>— What can you tell me, Prince, about my Borís? — she said, overtaking him in the anteroom. (She pronounced the name Borís with a special emphasis on the <emph>o</emph>). — I cannot remain any longer in Petersburg. Tell me, what news can I take to my poor boy?</p>
					<p>Although Prince Vasíli listened to the elderly lady reluctantly and almost impolitely, and even showed impatience, she smiled at him affectionately and touchingly, and, so that he should not go away, took him by the hand.</p>
					<p>— What would it cost you to say a word to the Emperor, and he would be directly transferred to the Guards? — she begged.</p>
					<p>— Believe me, I will do all I can, Princess, — answered Prince Vasíli, — but it is difficult for me to ask the Emperor; I should advise you to apply to Rumyántsev through Prince Golítsyn: that would be wiser.</p>
					<p>The elderly lady bore the name of Princess Drubetskáya, one of the best families in Russia, but she was poor, had long since retired from society, and had lost her former connections. She had come now to procure for her only son an appointment in the Guards. Only in order to see Prince Vasíli had she named herself and come to Anna Pávlovna's evening party; only for that had she listened to the vicomte's story. She was frightened by Prince Vasíli's words; her once beautiful face expressed anger, but it lasted only a minute. She smiled again and grasped Prince Vasíli's arm more firmly.</p>
					<p>— Listen, Prince, — she said, — I have never asked you, I will never ask you, I have never reminded you of my father's friendship for you. But now, I implore you by God, do this for my son, and I will consider you our benefactor, — she added hastily. — No, don't be angry, but promise me. I asked Golítsyn, he refused. <foreign xml:lang="fr" n="Be the good fellow you used to be">Soyez le bon enfant que vous avez été</foreign>, — she said, trying to smile, while there were tears in her eyes.</p>
					<p>— Papa, we shall be late. — said Princess Hélène, turning her beautiful head on its antique shoulders, as she waited by the door.</p>
					<p>But influence in society is a capital which has to be economized if it is not to disappear. Prince Vasíli knew this, and having once realized that if he were to ask on behalf of all who begged of him, he would soon be unable to ask for himself, he rarely used his influence. In Princess Drubetskáya's case, however, he felt, after her new appeal, something like a twinge of conscience. She had reminded him of the truth: for his first steps in the service he had been indebted to her father. Besides, he saw by her manner that she was one of those women, especially mothers, who, having once taken a thing into their heads, will not leave off until their wishes are fulfilled, and otherwise are ready for daily, minutely badgering, and even for scenes. This last consideration made him waver.</p>
					<p>— <foreign xml:lang="fr" n="Dear">Chère</foreign> Anna Mikháylovna, — he said with his usual familiarity and boredom in his voice, — it is almost impossible for me to do what you wish; but to prove to you how I love you and honor your late father's memory, I will do the impossible: your son shall be transferred to the Guards, here is my hand on it. Are you satisfied?</p>
					<p>— My dear, you are our benefactor! I expected nothing else from you; I knew how kind you are.</p>
					<p>He turned to go.</p>
					<p>— Wait, two words. <foreign xml:lang="fr" n="Once he is transferred to the Guards...">Une fois passé aux gardes...</foreign> — She hesitated: — You are on good terms with Mikhail Ilaríonovich Kutúzov, recommend Borís to him as an aide-de-camp. Then I should be at peace, and then indeed...</p>
					<p>Prince Vasíli smiled.</p>
					<p>— That I do not promise. You don't know how Kutúzov is besieged since he was appointed commander-in-chief. He told me himself that all the Moscow ladies have conspired to give him all their children as aides-de-camp.</p>
					<p>— No, promise, I will not let you go, my dear benefactor.</p>
					<p>— Papa, — the beauty repeated again in the same tone, — we shall be late.</p>
					<p>— Well, <foreign xml:lang="fr" n="goodbye">au revoir</foreign>, goodbye. You see?</p>
					<p>— So tomorrow you will report to the Emperor?</p>
					<p>— Without fail, but to Kutúzov I don't promise.</p>
					<p>— No, promise, promise, <foreign xml:lang="fr" n="Basile">Basile</foreign>, — Anna Mikháylovna said after him, with the smile of a young coquette, which must once have been natural to her, but now suited her exhausted face so ill.</p>
					<p>She evidently forgot her years and put into play, from habit, all the old feminine devices. But as soon as he had gone, her face again assumed the same cold, artificial expression it had worn before. She returned to the group where the vicomte was still talking, and again made a pretense of listening, waiting for the time to leave, as her business was done.</p>
					<p>— But what do you think of all this latest comedy <foreign xml:lang="fr" n="of the coronation in Milan?">du sacre de Milan?</foreign> — said Anna Pávlovna. <foreign xml:lang="fr" n="And the new comedy: the peoples of Genoa and Lucca coming to present their desires to Monsieur Bonaparte. Monsieur Bonaparte sitting on a throne and granting the desires of nations! Adorable! No, but it is enough to drive one mad. One would say that the whole world has lost its head.">Et la nouvelle comédie des peuples de Gênes et de Lucques, qui viennent présenter leurs voeux à M. Buonaparte. M. Buonaparte assis sur un trône, et exauèant les voeux des nations! Adorable! Non, mais c'est à en devenir folle! On dirait, que le monde entier a perdu la tête.</foreign></p>
					<p>Prince Andréi smiled, looking straight into Anna Pávlovna's face.</p>
					<p>— "Dieu me la donne, gare à qui la touche", — he said (Bonaparte's words spoken at the putting on of the crown). — <foreign xml:lang="fr" n="They say he was very handsome when he pronounced these words">On dit qu'il a été très beau en prononèant ces paroles</foreign>, — he added, and repeated the words once more in Italian: "Dio mi la dona, guai a chi la tocca".</p>
					<p>— <foreign xml:lang="fr" n="I hope finally">J'espère enfin</foreign>, — continued Anna Pávlovna, — <foreign xml:lang="fr" n="that that was the drop of water that will make the glass overflow. The sovereigns can no longer endure this man who threatens everything">que èa a été la goutte d'eau qui fera déborder le verre. Les souverains ne peuvent plus supporter cet homme, qui menace tout</foreign>.</p>
					<p>— <foreign xml:lang="fr" n="The sovereigns? I do not speak of Russia">Les souverains? Je ne parle pas de la Russie</foreign>, — said the vicomte politely and hopelessly: — <foreign xml:lang="fr" n="The sovereigns, Madame! What have they done for Louis XVII, for the Queen, for Madame Elisabeth? Nothing">Les souverains, madame! Qu'ont ils fait pour Louis XVII, pour la reine, pour madame Elisabeth? Rien</foreign>, — he continued, becoming animated. — <foreign xml:lang="fr" n="And believe me, they are undergoing the punishment for their betrayal of the Bourbon cause. The sovereigns? They send ambassadors to compliment the usurper">Et croyez-moi, ils subissent la punition pour leur trahison de la cause des Bourbons. Les souverains? Ils envoient des ambassadeurs complimenter l'usurpateur</foreign>.</p>
					<p>And sighing contemptuously, he again changed his position. Prince Hippolyte, who for a long time had been looking at the vicomte through his lorgnette, suddenly, at these words, turned his whole body towards the little princess and, asking her for a needle, began to trace the Condé coat of arms for her on the table with the needle. He explained this coat of arms to her with as significant an air as if the princess had asked him to do so.</p>
					<p>— <foreign xml:lang="fr" n="Baton of gules, engrailed of gules of azure — House of Condé">Bâton de gueules, engrêlé de gueules d'azur — maison Condé</foreign>, — he was saying.</p>
					<p>The princess listened, smiling.</p>
					<p>— If Bonaparte remains another year on the throne of France, — continued the vicomte, resuming the conversation with the air of a man who does not listen to others, but, in a matter he knows better than anyone else, follows only the course of his own thoughts, — things will go too far. By intrigue, by violence, by exile, by executions, society, I mean good French society, will be destroyed forever, and then...</p>
					<p>He shrugged his shoulders and spread his hands. Pierre was about to say something: the conversation interested him, but Anna Pávlovna, who was keeping watch on him, interrupted.</p>
					<p>— The Emperor Alexander, — she said, with the melancholy which always accompanied any reference of hers to the Imperial family, — has declared that he will leave it to the French themselves to choose their form of government. And I think there is no doubt that the whole nation, freed from the usurper, will throw itself into the arms of the lawful King, — said Anna Pávlovna, trying to be amiable to the émigré and royalist.</p>
					<p>— That is doubtful, — said Prince Andréi. — <foreign xml:lang="fr" n="Monsieur the vicomte">Monsieur le vicomte</foreign> quite rightly thinks that things have already gone too far. I think it will be difficult to return to the old state of things.</p>
					<p>— From what I have heard, — Pierre, blushing, again thrust himself into the conversation, — almost all the nobility has already gone over to Bonaparte's side.</p>
					<p>— That is what the Bonapartists say, — said the vicomte, not looking at Pierre. — It is difficult now to ascertain the public opinion of France.</p>
					<p>— <foreign xml:lang="fr" n="Bonaparte has said it">Bonaparte l'a dit</foreign>, — said Prince Andréi with a smirk.</p>
					<p>(It was evident that he did not like the vicomte, and that, although he was not looking at him, he was directing his remarks against him).</p>
					<p>— "Je leur ai montré le chemin de la gloire" — he said after a brief silence, again repeating Napoleon's words: — "ils n'en ont pas voulu; je leur ai ouvert mes antichambres, ils se sont précipités en foule"... <foreign xml:lang="fr" n="I do not know to what extent he had the right to say it">Je ne sais pas à quel point il a eu le droit de le dire</foreign>.</p>
					<p>— <foreign xml:lang="fr" n="None">Aucun</foreign>, — objected the vicomte. — After the murder of the duke, even the most partial people ceased to see him as a hero. <foreign xml:lang="fr" n="If he was even a hero for certain people">Si même èa été un héros pour certaines gens</foreign>, — said the vicomte, turning to Anna Pávlovna, — <foreign xml:lang="fr" n="since the assassination of the duke there is one more martyr in heaven, one less hero on earth">depuis l'assassinat du duc il y a un martyr de plus dans le ciel, un héros de moins sur la terre</foreign>.</p>
					<p>Anna Pávlovna and the others had not yet had time to appreciate these words of the vicomte's with a smile, when Pierre broke into the conversation again, and Anna Pávlovna, though she foresaw that he would say something improper, was no longer able to stop him.</p>
					<p>— The execution of the Duc d'Enghien, — said Pierre, — was a political necessity; and I see exactly greatness of soul in the fact that Napoleon was not afraid to take upon himself alone the responsibility for this action.</p>
					<p>— <foreign xml:lang="fr" n="God! my God!">Dieu! mon Dieu!</foreign> — Anna Pávlovna uttered in a terrified whisper.</p>
					<p>— <foreign xml:lang="fr" n="What, Monsieur Pierre, you find that assassination is greatness of soul?">Comment, М. Pierre, vous trouvez que l'assassinat est grandeur d'âme</foreign>, — said the little princess, smiling and drawing her work towards her.</p>
					<p>— Ah! Oh! — said various voices.</p>
					<p>— <foreign xml:lang="en" n="Capital!">Capital!</foreign> — said Prince Hippolyte in English, and began slapping his knee with his palm. The vicomte only shrugged his shoulders.</p>
					<p>Pierre looked solemnly over his spectacles at his listeners.</p>
					<p>— I say so, — he continued desperately, — because the Bourbons fled from the Revolution leaving the people to anarchy; and Napoleon alone understood the Revolution, overcame it, and so for the public good he could not stop before the life of one man.</p>
					<p>— Won't you come over to the other table? — said Anna Pávlovna. But Pierre, without answering, continued his speech.</p>
					<p>— No, — he said, growing more and more animated, — Napoleon is great because he rose above the Revolution, suppressed its abuses, preserving all that was good — the equality of citizens, and freedom of speech and of the press — and only for that reason acquired power.</p>
					<p>— Yes, if having taken power, without using it for murder, he had handed it over to the lawful King, — said the vicomte, — then I should have called him a great man.</p>
					<p>— He could not do that. The people only gave him power that he might rid them of the Bourbons, and because the people saw him as a great man. The Revolution was a grand thing, — continued Monsieur Pierre, betraying by this desperate and provocative opening proposition his extreme youth and his desire to express everything as quickly as possible.</p>
					<p>— The Revolution and regicide a grand thing?... After that... but won't you come to this other table? — repeated Anna Pávlovna.</p>
					<p>— <foreign xml:lang="fr" n="The Social Contract">Contrat social</foreign>, — said the vicomte with a mild smile.</p>
					<p>— I am not speaking of regicide. I am speaking of ideas.</p>
					<p>— Yes, ideas of robbery, murder, and regicide, — again interrupted the ironical voice.</p>
					<p>— Those were extremes, of course, but the whole meaning does not lie in them; the meaning lies in the rights of man, in emancipation from prejudices, in the equality of citizens; and all these ideas Napoleon retained in all their force.</p>
					<p>— Liberty and Equality, — said the vicomte contemptuously, as if at last having decided seriously to prove to this youth the whole stupidity of his speeches, — are all high-sounding words which have long been compromised. Who does not love liberty and equality? Even our Savior preached liberty and equality. Have people become happier since the Revolution? On the contrary. We wanted liberty, but Bonaparte has destroyed it.</p>
					<p>Prince Andréi kept looking with a smile now at Pierre, now at the vicomte, now at their hostess. In the first moment of Pierre's outburst Anna Pávlovna was horrified, despite her habit of society; but when she saw that in spite of the sacrilegious words Pierre had uttered, the vicomte did not lose his temper, and when she convinced herself that it was no longer possible to hush up these speeches, she mustered her forces and, joining the vicomte, attacked the orator.</p>
					<p>— <foreign xml:lang="fr" n="But, my dear Monsieur Pierre">Mais, mon cher m-r Pierre</foreign>, — said Anna Pávlovna, — how do you explain a great man who could execute a duke, or indeed simply a man, without trial and without guilt?</p>
					<p>— I should ask, — said the vicomte, — how monsieur explains the 18th Brumaire? Was not that a hoax? <foreign xml:lang="fr" n="It is a conjuring trick, which in no way resembles the manner of acting of a great man">C'est un escamotage, qui ne ressemble nullement à la manière d'agir d'un grand homme</foreign>.</p>
					<p>— And the prisoners in Africa whom he killed? — said the little princess, — that was horrible! — And she shrugged her shoulders.</p>
					<p>— <foreign xml:lang="fr" n="He is a plebeian, say what you will">C'est un roturier, vous aurez beau dire</foreign>, — said Prince Hippolyte.</p>
					<p>Monsieur Pierre did not know whom to answer, he looked at them all and smiled. His smile was not like other people's, blending with non-smiling. On the contrary, with him, when a smile came, his serious and even somewhat gloomy face suddenly and instantly disappeared, and another appeared — childlike, kind, even slightly foolish and as if asking forgiveness.</p>
					<p>To the vicomte, who was seeing him for the first time, it became clear that this Jacobin was not nearly so terrible as his words. Everyone fell silent.</p>
					<p>— How do you expect him to answer everyone at once? — said Prince Andréi. — Besides, in the actions of a statesman one must distinguish the actions of a private person, a general, or an emperor. It seems so to me.</p>
					<p>— Yes, yes, of course, — chimed in Pierre, delighted with the help that had come forward for him.</p>
					<p>— One must admit, — continued Prince Andréi, — Napoleon as a man was great on the bridge of Arcole, and in the hospital at Jaffa, where he gave his hand to the plague-stricken, but... but there are other actions which it is difficult to justify.</p>
					<p>Prince Andréi, who evidently wished to soften the awkwardness of Pierre's speech, half rose, making ready to go and giving a sign to his wife.</p>
					<p>Suddenly Prince Hippolyte rose and, stopping everyone with signs of his hands and asking them to sit down, began to speak:</p>
					<p>— <foreign xml:lang="fr" n="Ah! today I was told a charming Moscow anecdote: I must treat you to it. Excuse me, vicomte, I must tell it in Russian. Otherwise one will not feel the salt of the story">Ah! aujourd'hui on m'a raconté une anecdote moscovite, charmante: il faut que je vous en régale. Vous m'excusez, vicomte, il faut que je raconte en russe. Autrement on ne sentira pas le sel de l'histoire</foreign>.</p>
					<p>And Prince Hippolyte began to speak in Russian, with the pronunciation of a Frenchman who has lived in Russia for about a year. Everyone paused: so animatedly, urgently did Prince Hippolyte demand attention to his story.</p>
					<p>— In Moscou there is a lady, <foreign xml:lang="fr" n="a lady">une dame</foreign>. And she is very stingy. She needed to have two <foreign xml:lang="fr" n="footmen">valets de pied</foreign> behind the carriage. And very tall in stature. That was her taste. And she had <foreign xml:lang="fr" n="a maid">une femme de chambre</foreign>, still taller in stature. She said...</p>
					<p>Here Prince Hippolyte fell to thinking, evidently having difficulty gathering his thoughts.</p>
					<p>— She said... yes, she said: 'girl (<foreign xml:lang="fr" n="to the maid">à la femme de chambre</foreign>), put on a <foreign xml:lang="fr" n="livery">livrée</foreign> and come with me, behind the carriage, <foreign xml:lang="fr" n="to pay visits">faire des visites</foreign>.'</p>
					<p>Here Prince Hippolyte snorted and burst out laughing much sooner than his listeners, which produced an unfavorable impression on the storyteller. However, many, including the elderly lady and Anna Pávlovna, smiled.</p>
					<p>— She went out. Suddenly there was a strong wind. The girl lost her hat, and her long hair was combed out...</p>
					<p>Here he could hold out no longer and began laughing jerkily, and through this laughter articulated:</p>
					<p>— And the whole world knew...</p>
					<p>And so the anecdote ended. Though it was unintelligible why he was telling it and why it absolutely had to be told in Russian, nevertheless Anna Pávlovna and the others appreciated the social amiability of Prince Hippolyte, who had so pleasantly concluded the unpleasant and unamiable outburst of Monsieur Pierre. The conversation after the anecdote scattered into petty, insignificant talk about the future and past ball, the theater, and when and where who would see whom.</p>
				</div>"""

es_text_4 = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo IV</head>
					<p>Anna Pávlovna sonrió y prometió ocuparse de Pierre, de quien sabía que era pariente del príncipe Vasíli por parte de padre. La señora mayor, que había estado sentada antes con <foreign xml:lang="fr" n="mi tía">ma tante</foreign>, se levantó apresuradamente y alcanzó al príncipe Vasíli en la antesala. Toda la antigua afectación de interés había desaparecido de su rostro. Su rostro bondadoso, bañado en lágrimas, sólo expresaba ansiedad y miedo.</p>
					<p>— ¿Qué me dice, príncipe, de mi Borís? — dijo, alcanzándole en la antesala. (Pronunciaba el nombre Borís con un énfasis especial en la <emph>o</emph>). — No puedo quedarme más tiempo en Petersburgo. Dígame, ¿qué noticias puedo llevarle a mi pobre muchacho?</p>
					<p>A pesar de que el príncipe Vasíli escuchó a la señora mayor de mala gana y casi con descortesía, e incluso mostró impaciencia, ella le sonrió con afecto y de forma conmovedora, y, para que no se fuera, le cogió de la mano.</p>
					<p>— ¿Qué le cuesta a usted decir una palabra al Emperador, y él será trasladado directamente a la Guardia? — suplicó ella.</p>
					<p>— Créame que haré todo lo que pueda, princesa, — contestó el príncipe Vasíli, — pero me resulta difícil pedirselo al Emperador; yo le aconsejaría que se dirigiera a Rumyántsev por medio del príncipe Golítsyn: sería más prudente.</p>
					<p>La anciana dama llevaba el nombre de princesa Drubetskáya, una de las mejores familias de Rusia, pero era pobre, hacía tiempo que se había retirado de la sociedad y había perdido sus antiguas conexiones. Había venido ahora para procurar a su único hijo un nombramiento en la Guardia. Sólo para ver al príncipe Vasíli se había nombrado y había acudido a la velada de Anna Pávlovna, sólo para eso había escuchado el relato del vizconde. Se asustó ante las palabras del príncipe Vasíli; su rostro, en otro tiempo hermoso, expresó enfado, pero sólo duró un minuto. Volvió a sonreír y agarró con más firmeza el brazo del príncipe Vasíli.</p>
					<p>— Escuche, príncipe, — dijo, — nunca se lo he pedido, nunca se lo pediré, nunca le he recordado la amistad que mi padre sentía por usted. Pero ahora, se lo ruego por Dios, haga esto por mi hijo, y le consideraré nuestro benefactor, — añadió apresuradamente. — No, no se enfade, pero prométamelo. Se lo pedí a Golítsyn, se negó. <foreign xml:lang="fr" n="Sea el buen muchacho que solía ser">Soyez le bon enfant que vous avez été</foreign>, — dijo, intentando sonreír, mientras había lágrimas en sus ojos.</p>
					<p>— Papá, llegaremos tarde. — dijo la princesa Hélène, volviendo su hermosa cabeza sobre sus hombros de estatua antigua, mientras esperaba junto a la puerta.</p>
					<p>Pero la influencia en la sociedad es un capital que hay que economizar si no se quiere que desaparezca. El príncipe Vasíli lo sabía, y habiendo comprendido una vez que si pidiera en favor de todos los que le suplicaban, pronto se vería imposibilitado de pedir para sí mismo, rara vez usaba su influencia. En el caso de la princesa Drubetskáya, sin embargo, sintió, tras su nueva súplica, algo parecido a un remordimiento de conciencia. Le había recordado la verdad: por sus primeros pasos en el servicio estaba en deuda con el padre de ella. Además, veía por sus modales que era una de esas mujeres, especialmente madres, que, habiéndose metido una vez una cosa en la cabeza, no la dejan hasta que se cumplen sus deseos, y de lo contrario están dispuestas a acosos diarios, al minuto, e incluso a escenas. Esta última consideración le hizo vacilar.</p>
					<p>— <foreign xml:lang="fr" n="Querida">Chère</foreign> Anna Mikháylovna, — dijo con su habitual familiaridad y aburrimiento en la voz, — me es casi imposible hacer lo que desea; pero para demostrarle cuánto la quiero y honro la memoria de su difunto padre, haré lo imposible: su hijo será trasladado a la Guardia, aquí tiene mi mano. ¿Está usted satisfecha?</p>
					<p>— ¡Mi querido, es usted nuestro benefactor! No esperaba otra cosa de usted; sabía lo bondadoso que es.</p>
					<p>Hizo ademán de irse.</p>
					<p>— Espere, dos palabras. <foreign xml:lang="fr" n="Una vez que pase a la Guardia...">Une fois passé aux gardes...</foreign> — Ella dudó: — Usted se lleva bien con Mikhail Ilaríonovich Kutúzov, recomiéndele a Borís como ayudante de campo. Entonces estaría tranquila, y entonces sí que...</p>
					<p>El príncipe Vasíli sonrió.</p>
					<p>— Eso no se lo prometo. No sabe usted cómo asedian a Kutúzov desde que fue nombrado comandante en jefe. Él mismo me dijo que todas las damas de Moscú se han confabulado para darle a todos sus hijos como ayudantes de campo.</p>
					<p>— No, prométamelo, no le dejaré marchar, mi querido benefactor.</p>
					<p>— Papá, — repitió de nuevo la bella en el mismo tono, — llegaremos tarde.</p>
					<p>— Bueno, <foreign xml:lang="fr" n="hasta la vista">au revoir</foreign>, adiós. ¿Lo ve?</p>
					<p>— ¿Así que mañana informará al Emperador?</p>
					<p>— Sin falta, pero a Kutúzov no se lo prometo.</p>
					<p>— No, prométalo, prométalo, <foreign xml:lang="fr" n="Basile">Basile</foreign>, — dijo Anna Mikháylovna tras él, con la sonrisa de una joven coqueta, que en otro tiempo debió serle natural, pero que ahora sentaba tan mal a su rostro agotado.</p>
					<p>Evidentemente, se olvidó de sus años y puso en juego, por costumbre, todas las antiguas artimañas femeninas. Pero en cuanto él se fue, su rostro volvió a adoptar la misma expresión fría y artificial de antes. Volvió al grupo en el que el vizconde seguía hablando y volvió a fingir que escuchaba, esperando el momento de marcharse, pues su asunto estaba terminado.</p>
					<p>— Pero, ¿qué opina de toda esta última comedia <foreign xml:lang="fr" n="de la coronación en Milán?">du sacre de Milan?</foreign> — dijo Anna Pávlovna. <foreign xml:lang="fr" n="Y la nueva comedia: los pueblos de Génova y Lucca que vienen a presentar sus deseos al señor Bonaparte. ¡El señor Bonaparte sentado en un trono y concediendo los deseos de las naciones! ¡Adorable! No, pero es para volverse loco. Se diría que el mundo entero ha perdido la cabeza.">Et la nouvelle comédie des peuples de Gênes et de Lucques, qui viennent présenter leurs voeux à M. Buonaparte. M. Buonaparte assis sur un trône, et exauèant les voeux des nations! Adorable! Non, mais c'est à en devenir folle! On dirait, que le monde entier a perdu la tête.</foreign></p>
					<p>El príncipe Andréi sonrió, mirando directamente a la cara a Anna Pávlovna.</p>
					<p>— "Dieu me la donne, gare à qui la touche", — dijo (palabras de Bonaparte pronunciadas al ponerse la corona). — <foreign xml:lang="fr" n="Dicen que estaba muy guapo al pronunciar estas palabras">On dit qu'il a été très beau en prononèant ces paroles</foreign>, — añadió, y repitió las palabras una vez más en italiano: "Dio mi la dona, guai a chi la tocca".</p>
					<p>— <foreign xml:lang="fr" n="Espero por fin">J'espère enfin</foreign>, — continuó Anna Pávlovna, — <foreign xml:lang="fr" n="que esa haya sido la gota de agua que colmará el vaso. Los soberanos no pueden soportar más a este hombre que lo amenaza todo">que èa a été la goutte d'eau qui fera déborder le verre. Les souverains ne peuvent plus supporter cet homme, qui menace tout</foreign>.</p>
					<p>— <foreign xml:lang="fr" n="¿Los soberanos? Yo no hablo de Rusia">Les souverains? Je ne parle pas de la Russie</foreign>, — dijo el vizconde con cortesía y desesperanza: — <foreign xml:lang="fr" n="¡Los soberanos, señora! ¿Qué han hecho por Luis XVII, por la reina, por Madame Elisabeth? Nada">Les souverains, madame! Qu'ont ils fait pour Louis XVII, pour la reine, pour madame Elisabeth? Rien</foreign>, — continuó, animándose. — <foreign xml:lang="fr" n="Y créame, están sufriendo el castigo por su traición a la causa de los Borbones. ¿Los soberanos? Envían embajadores a felicitar al usurpador">Et croyez-moi, ils subissent la punition pour leur trahison de la cause des Bourbons. Les souverains? Ils envoient des ambassadeurs complimenter l'usurpateur</foreign>.</p>
					<p>Y suspirando despectivamente, volvió a cambiar de postura. El príncipe Hippolyte, que llevaba un buen rato mirando al vizconde a través de sus impertinentes, repentinamente, ante estas palabras, giró todo su cuerpo hacia la princesita y, pidiéndole una aguja, empezó a trazarle el escudo de los Condé en la mesa con la aguja. Le explicó el escudo de armas con un aire tan significativo como si la princesa se lo hubiera pedido.</p>
					<p>— <foreign xml:lang="fr" n="Bastón de gules, cairelado de gules de azur — Casa de Condé">Bâton de gueules, engrêlé de gueules d'azur — maison Condé</foreign>, — decía él.</p>
					<p>La princesa escuchaba, sonriendo.</p>
					<p>— Si Bonaparte permanece un año más en el trono de Francia, — continuó el vizconde, reanudando la conversación con aire de hombre que no escucha a los demás, sino que, en un asunto que conoce mejor que nadie, sigue únicamente el curso de sus propios pensamientos, — las cosas irán demasiado lejos. Mediante la intriga, la violencia, el exilio, las ejecuciones, la sociedad, me refiero a la buena sociedad francesa, será destruida para siempre, y entonces...</p>
					<p>Se encogió de hombros y abrió las manos. Pierre estaba a punto de decir algo: la conversación le interesaba, pero Anna Pávlovna, que le vigilaba, le interrumpió.</p>
					<p>— El emperador Alejandro, — dijo ella, con la melancolía que acompañaba siempre cualquier referencia suya a la familia imperial, — ha declarado que dejará a los propios franceses la elección de su forma de gobierno. Y creo que no hay duda de que toda la nación, liberada del usurpador, se arrojará en brazos del Rey legítimo, — dijo Anna Pávlovna, intentando ser amable con el emigrado y monárquico.</p>
					<p>— Eso es dudoso, — dijo el príncipe Andréi. — <foreign xml:lang="fr" n="El señor vizconde">Monsieur le vicomte</foreign> piensa con toda razón que las cosas han ido ya demasiado lejos. Creo que será difícil volver al antiguo estado de cosas.</p>
					<p>— Por lo que he oído, — Pierre, ruborizándose, volvió a inmiscuirse en la conversación, — casi toda la nobleza se ha pasado ya al bando de Bonaparte.</p>
					<p>— Eso dicen los bonapartistas, — dijo el vizconde, sin mirar a Pierre. — Ahora es difícil averiguar la opinión pública de Francia.</p>
					<p>— <foreign xml:lang="fr" n="Bonaparte lo ha dicho">Bonaparte l'a dit</foreign>, — dijo el príncipe Andréi con una mueca.</p>
					<p>(Era evidente que el vizconde no le gustaba, y que, aunque no le miraba, dirigía sus comentarios contra él).</p>
					<p>— "Je leur ai montré le chemin de la gloire" — dijo tras un breve silencio, volviendo a repetir las palabras de Napoleón: — "ils n'en ont pas voulu; je leur ai ouvert mes antichambres, ils se sont précipités en foule"... <foreign xml:lang="fr" n="No sé hasta qué punto tenía derecho a decirlo">Je ne sais pas à quel point il a eu le droit de le dire</foreign>.</p>
					<p>— <foreign xml:lang="fr" n="Ninguno">Aucun</foreign>, — objetó el vizconde. — Tras el asesinato del duque, incluso las personas más parciales dejaron de ver en él a un héroe. <foreign xml:lang="fr" n="Si es que fue un héroe para algunas personas">Si même èa été un héros pour certaines gens</foreign>, — dijo el vizconde, dirigiéndose a Anna Pávlovna, — <foreign xml:lang="fr" n="desde el asesinato del duque hay un mártir más en el cielo, un héroe menos en la tierra">depuis l'assassinat du duc il y a un martyr de plus dans le ciel, un héros de moins sur la terre</foreign>.</p>
					<p>Anna Pávlovna y los demás aún no habían tenido tiempo de apreciar con una sonrisa estas palabras del vizconde, cuando Pierre volvió a intervenir en la conversación, y Anna Pávlovna, aunque previó que diría algo indecoroso, ya no pudo detenerle.</p>
					<p>— La ejecución del duque de Enghien, — dijo Pierre, — fue una necesidad política; y veo exactamente grandeza de alma en el hecho de que Napoleón no tuviera miedo de asumir él solo la responsabilidad de esta acción.</p>
					<p>— <foreign xml:lang="fr" n="¡Dios! ¡Dios mío!">Dieu! mon Dieu!</foreign> — pronunció Anna Pávlovna en un susurro aterrorizado.</p>
					<p>— <foreign xml:lang="fr" n="Cómo, señor Pierre, ¿encuentra usted que el asesinato es grandeza de alma?">Comment, М. Pierre, vous trouvez que l'assassinat est grandeur d'âme</foreign>, — dijo la princesita, sonriendo y atrayendo hacia sí su labor.</p>
					<p>— ¡Ah! ¡Oh! — dijeron varias voces.</p>
					<p>— <foreign xml:lang="en" n="¡Estupendo!">Capital!</foreign> — dijo el príncipe Hippolyte en inglés, y empezó a darse palmadas en la rodilla con la mano. El vizconde se limitó a encogerse de hombros.</p>
					<p>Pierre miró solemnemente por encima de sus gafas a sus oyentes.</p>
					<p>— Lo digo, — continuó desesperadamente, — porque los Borbones huyeron de la Revolución dejando al pueblo en la anarquía; y sólo Napoleón comprendió la Revolución, la venció, y así, por el bien público, no pudo detenerse ante la vida de un hombre.</p>
					<p>— ¿No quiere pasarse a la otra mesa? — dijo Anna Pávlovna. Pero Pierre, sin contestar, continuó su discurso.</p>
					<p>— No, — dijo, animándose cada vez más, — Napoleón es grande porque se elevó por encima de la Revolución, reprimió sus abusos, conservando todo lo bueno — la igualdad de los ciudadanos, y la libertad de palabra y de prensa — y sólo por ello adquirió el poder.</p>
					<p>— Sí, si habiendo tomado el poder, sin usarlo para asesinar, se lo hubiera entregado al Rey legítimo, — dijo el vizconde, — entonces yo le habría llamado un gran hombre.</p>
					<p>— No podía hacer eso. El pueblo sólo le dio el poder para que les librara de los Borbones, y porque el pueblo veía en él a un gran hombre. La Revolución fue algo grandioso, — prosiguió monsieur Pierre, delatando con esta desesperada y provocativa proposición de apertura su extrema juventud y su deseo de expresarlo todo lo más rápidamente posible.</p>
					<p>— ¿La Revolución y el regicidio una cosa grandiosa?... Después de eso... pero, ¿no quiere pasar a esta otra mesa? — repitió Anna Pávlovna.</p>
					<p>— <foreign xml:lang="fr" n="El Contrato Social">Contrat social</foreign>, — dijo el vizconde con una leve sonrisa.</p>
					<p>— No hablo del regicidio. Hablo de ideas.</p>
					<p>— Sí, ideas de robo, asesinato y regicidio, — volvió a interrumpir la voz irónica.</p>
					<p>— Fueron extremos, por supuesto, pero en ellos no reside todo el significado; el significado reside en los derechos del hombre, en la emancipación de los prejuicios, en la igualdad de los ciudadanos; y todas estas ideas Napoleón las retuvo con toda su fuerza.</p>
					<p>— La Libertad y la Igualdad, — dijo el vizconde con desprecio, como si por fin hubiera decidido demostrar seriamente a aquel joven toda la estupidez de sus discursos, — son todas palabras altisonantes que hace tiempo que están comprometidas. ¿Quién no ama la libertad y la igualdad? Hasta nuestro Salvador predicó la libertad y la igualdad. ¿Se ha vuelto la gente más feliz desde la Revolución? Al contrario. Queríamos libertad, pero Bonaparte la ha destruido.</p>
					<p>El príncipe Andréi no dejaba de mirar con una sonrisa ora a Pierre, ora al vizconde, ora a su anfitriona. En el primer momento del exabrupto de Pierre, Anna Pávlovna se horrorizó, a pesar de su costumbre de sociedad; pero cuando vio que, a pesar de las palabras sacrílegas que Pierre había pronunciado, el vizconde no perdía los estribos, y cuando se convenció de que ya no era posible silenciar aquellos discursos, reunió sus fuerzas y, uniéndose al vizconde, atacó al orador.</p>
					<p>— <foreign xml:lang="fr" n="Pero, mi querido señor Pierre">Mais, mon cher m-r Pierre</foreign>, — dijo Anna Pávlovna, — ¿cómo se explica usted que un gran hombre pueda ejecutar a un duque, o incluso simplemente a un hombre, sin juicio y sin culpa?</p>
					<p>— Yo preguntaría, — dijo el vizconde, — ¿cómo explica monsieur el 18 de Brumario? ¿No fue un engaño? <foreign xml:lang="fr" n="Es un juego de manos, que no se parece en nada a la manera de actuar de un gran hombre">C'est un escamotage, qui ne ressemble nullement à la manière d'agir d'un grand homme</foreign>.</p>
					<p>— ¿Y los prisioneros de África a los que mató? — dijo la princesita, — ¡eso fue horrible! — Y se encogió de hombros.</p>
					<p>— <foreign xml:lang="fr" n="Es un plebeyo, diga lo que diga">C'est un roturier, vous aurez beau dire</foreign>, — dijo el príncipe Hippolyte.</p>
					<p>Monsieur Pierre no sabía a quién contestar, miró a todos y sonrió. Su sonrisa no era como la de los demás, mezclada con el no sonreír. Al contrario, en él, cuando asomaba una sonrisa, su rostro serio e incluso algo sombrío desaparecía repentinamente e al instante, y aparecía otro: infantil, bondadoso, incluso ligeramente bobalicón y como pidiendo perdón.</p>
					<p>Para el vizconde, que le veía por primera vez, quedó claro que aquel jacobino no era ni de lejos tan terrible como sus palabras. Todos guardaron silencio.</p>
					<p>— ¿Cómo espera usted que conteste a todos a la vez? — dijo el príncipe Andréi. — Además, en las acciones de un estadista hay que distinguir las acciones de una persona privada, de un general o de un emperador. A mí me lo parece.</p>
					<p>— Sí, sí, por supuesto, — intervino Pierre, encantado con la ayuda que se le había adelantado.</p>
					<p>— Hay que admitir, — continuó el príncipe Andréi, — que Napoleón como hombre fue grande en el puente de Arcole, y en el hospital de Jaffa, donde dio la mano a los apestados, pero... pero hay otras acciones que es difícil justificar.</p>
					<p>El príncipe Andréi, que evidentemente deseaba suavizar la incomodidad del discurso de Pierre, se levantó a medias, disponiéndose a marcharse y haciendo una seña a su esposa.</p>
					<p>De repente el príncipe Hippolyte se levantó y, deteniendo a todos con señales de las manos y pidiéndoles que se sentaran, empezó a hablar:</p>
					<p>— <foreign xml:lang="fr" n="¡Ah! Hoy me han contado una anécdota moscovita encantadora: debo invitarles a ella. Disculpe, vizconde, debo contarla en ruso. De lo contrario no se sentirá la sal de la historia">Ah! aujourd'hui on m'a raconté une anecdote moscovite, charmante: il faut que je vous en régale. Vous m'excusez, vicomte, il faut que je raconte en russe. Autrement on ne sentira pas le sel de l'histoire</foreign>.</p>
					<p>Y el príncipe Hippolyte empezó a hablar en ruso, con la pronunciación de un francés que ha vivido en Rusia cerca de un año. Todos se detuvieron: con tal animación y urgencia el príncipe Hippolyte exigió atención para su historia.</p>
					<p>— En Moscou hay una señora, <foreign xml:lang="fr" n="una dama">une dame</foreign>. Y es muy tacaña. Necesitaba tener dos <foreign xml:lang="fr" n="lacayos">valets de pied</foreign> detrás del carruaje. Y muy altos de estatura. Ese era su gusto. Y tenía <foreign xml:lang="fr" n="una doncella">une femme de chambre</foreign>, de estatura aún mayor. Ella dijo...</p>
					<p>Aquí el príncipe Hippolyte se puso a pensar, teniendo evidentemente dificultades para reunir sus pensamientos.</p>
					<p>— Ella dijo... sí, ella dijo: 'chica (<foreign xml:lang="fr" n="a la doncella">à la femme de chambre</foreign>), ponte una <foreign xml:lang="fr" n="librea">livrée</foreign> y ven conmigo, detrás del carruaje, <foreign xml:lang="fr" n="a hacer visitas">faire des visites</foreign>.'</p>
					<p>Aquí el príncipe Hippolyte resopló y se echó a reír mucho antes que sus oyentes, lo que produjo una impresión desfavorable del narrador. Sin embargo, muchos, entre ellos la anciana dama y Anna Pávlovna, sonrieron.</p>
					<p>— Ella salió. De repente hubo un viento fuerte. La chica perdió el sombrero, y sus largos cabellos se soltaron...</p>
					<p>Aquí ya no aguantó más y empezó a reír a sacudidas, y a través de esta risa articuló:</p>
					<p>— Y el mundo entero lo supo...</p>
					<p>Y así terminó la anécdota. Aunque resultaba incomprensible por qué la contaba y por qué debía contarla obligatoriamente en ruso, Anna Pávlovna y los demás apreciaron, sin embargo, la amabilidad social del príncipe Hippolyte, que había concluido tan agradablemente el desagradable y poco amable exabrupto de monsieur Pierre. Tras la anécdota, la conversación se dispersó en pequeñas e insignificantes charlas sobre el baile futuro y pasado, el teatro, y cuándo y dónde vería quién a quién.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

ch4_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="4">'))
text = text[:ch4_start] + en_text_4 + '\n' + es_text_4 + '\n' + text[ch4_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
