import re

en_text_6 = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter VI</head>
					<p>In the next room a woman's dress rustled. As if waking up, Prince Andréi shook himself, and his face assumed the same expression it had worn in Anna Pávlovna's drawing room. Pierre lowered his legs from the sofa. The princess came in. She was already in a different, indoor, but equally elegant and fresh dress. Prince Andréi stood up, politely offering her a chair.</p>
					<p>— Why is it, I often think, — she began, as always in French, hastily and fussily settling into the chair, — why is it Annette has not married? How stupid you all are, <foreign xml:lang="fr" n="gentlemen">messieurs</foreign>, not to have married her. You must excuse me, but you understand nothing about women. What an arguer you are, Monsieur Pierre!</p>
					<p>— I am always arguing with your husband too; I don't understand why he wants to go to war, — said Pierre, addressing the princess without any of the restraint (so usual in the relations of a young man to a young woman).</p>
					<p>The princess started. Evidently, Pierre's words had touched her to the quick.</p>
					<p>— Ah, that is just what I say! — she said. — I don't understand, I absolutely don't understand why men cannot live without war? Why is it that we women want nothing and need nothing? Now, you be the judge. I keep telling him: here he is aide-de-camp to his uncle, a most brilliant position. Everyone knows him so well and appreciates him so much. The other day at the Apráksins' I heard a lady asking: <foreign xml:lang="fr" n="is that the famous Prince André? My word of honor!">c'est èa le fameux prince André? Ma parole d'honneur!</foreign> — She laughed. — He is received so well everywhere. He could very easily be a flügel-adjutant too. You know, the Emperor spoke to him very graciously. Annette and I were talking, it would be very easy to arrange. What do you think?</p>
					<p>Pierre looked at Prince Andréi and, noticing that his friend did not like this conversation, made no reply.</p>
					<p>— When do you leave? — he asked.</p>
					<p>— <foreign xml:lang="fr" n="Ah, don't speak to me of that departure, don't speak of it. I won't hear of it">Ah! ne me parlez pas de ce départ, ne m'en parlez pas. Je ne veux pas en entendre parler</foreign>, — the princess began to speak in that capriciously playful tone in which she had spoken to Hippolyte in the drawing room, and which was so evidently unsuited to the family circle where Pierre was like a member. — Today, when I thought that we must break off all these dear relations... And then, do you know, <foreign xml:lang="fr" n="Andréi">André</foreign>? — She winked significantly at her husband. — <foreign xml:lang="fr" n="I'm afraid, I'm afraid!">J'ai peur, j'ai peur!</foreign> — she whispered, shuddering with her back.</p>
					<p>Her husband looked at her as if he were surprised to notice that anyone else besides himself and Pierre was in the room: however, he addressed his wife inquiringly with cold politeness:</p>
					<p>— What are you afraid of, Lise? I cannot understand, — he said.</p>
					<p>— See how all men are egoists; all, all egoists! He himself, out of his own whims, God knows why, leaves me, locks me up alone in the country.</p>
					<p>— With my father and sister, don't forget, — Prince Andréi said quietly.</p>
					<p>— All the same alone, without <emph>my</emph> friends... And he wants me not to be afraid.</p>
					<p>Her tone was already grumbling, her little lip went up, giving her face not a joyful, but a bestial, squirrel-like expression. She fell silent, as if finding it improper to speak of her pregnancy before Pierre, whereas that was the essence of the matter.</p>
					<p>— I still have not understood <foreign xml:lang="fr" n="what you are afraid of">de quoi vous avez peur</foreign>, — Prince Andréi pronounced slowly, not taking his eyes off his wife.</p>
					<p>The princess blushed and waved her arms despairingly.</p>
					<p>— <foreign xml:lang="fr" n="No, Andréi, I say that you have changed so much, so much...">Non, André, je dis que vous avez tellement, tellement changé...</foreign></p>
					<p>— Your doctor orders you to go to bed earlier, — said Prince Andréi. — You had better go to sleep.</p>
					<p>The princess said nothing, and suddenly her short downy lip trembled; Prince Andréi, rising and shrugging his shoulders, walked across the room.</p>
					<p>Pierre looked with naive surprise through his spectacles now at him, now at the princess, and stirred as if he too wished to rise, but changed his mind again.</p>
					<p>— What does it matter to me that Monsieur Pierre is here, — the little princess suddenly said, and her pretty face suddenly broke into a tearful grimace. — I have long wanted to tell you, <foreign xml:lang="fr" n="Andréi">André</foreign>: why have you changed so towards me? What have I done to you? You are going to the army, you have no pity for me. Why?</p>
					<p>— Lise! — was all Prince Andréi said; but in that word there was an entreaty, a threat, and above all an assurance that she herself would repent of her words; but she went on hurriedly:</p>
					<p>— You treat me like a sick person or a child. I see it all. Were you like this six months ago?</p>
					<p>— Lise, I beg you to stop, — said Prince Andréi still more expressively.</p>
					<p>Pierre, who had been growing more and more agitated during this conversation, got up and went to the princess. He seemed unable to bear the sight of tears and was ready to cry himself.</p>
					<p>— Calm yourself, Princess. It only seems so to you, because I assure you, I myself have experienced... why... because... No, excuse me, a stranger is out of place here... No, calm yourself... Goodbye...</p>
					<p>Prince Andréi stopped him by the arm.</p>
					<p>— No, stay, Pierre. The princess is too kind to wish to deprive me of the pleasure of spending the evening with you.</p>
					<p>— No, he thinks only of himself, — the princess muttered, not restraining her angry tears.</p>
					<p>— Lise, — said Prince Andréi dryly, raising his tone to that pitch which indicates that patience is exhausted.</p>
					<p>Suddenly the angry, squirrel-like expression of the princess's pretty little face was replaced by an attractive and pity-arousing expression of fear; she looked from under her brows with her beautiful eyes at her husband, and on her face appeared that timid and confessing expression which a dog has when it rapidly but feebly wags its drooping tail.</p>
					<p>— <foreign xml:lang="fr" n="My God, my God!">Mon Dieu, mon Dieu!</foreign> — the princess muttered, and gathering up a fold of her dress with one hand, she went to her husband and kissed him on the forehead.</p>
					<p>— <foreign xml:lang="fr" n="Goodnight, Lise">Bonsoir, Lise</foreign>, — said Prince Andréi, rising and politely, as to a stranger, kissing her hand. ————</p>
					<p>The friends were silent. Neither the one nor the other began to speak. Pierre glanced at Prince Andréi, Prince Andréi rubbed his forehead with his small hand.</p>
					<p>— Let us go to supper, — he said with a sigh, rising and going to the door.</p>
					<p>They entered the elegantly, newly, and richly decorated dining room. Everything, from the napkins to the silver, china, and crystal, bore that peculiar stamp of newness that is found in the household of young married couples. In the middle of supper Prince Andréi leaned on his elbow and, like a man who has long had something on his heart and suddenly decides to speak out, with an expression of nervous irritation such as Pierre had never yet seen on his friend's face, began to speak:</p>
					<p>— Never, never marry, my friend; here is my advice to you: do not marry until you can say to yourself that you have done all you could, and until you have ceased to love the woman you have chosen, until you see her clearly; otherwise you will make a cruel and irreparable mistake. Marry when you are an old man, good for nothing... Otherwise all that is good and noble in you will be lost. It will all be frittered away on trifles. Yes, yes, yes! Do not look at me with such surprise. If you expect anything of yourself in the future, at every step you will feel that for you all is ended, all is closed except the drawing room, where you will be on the same level as a court footman and an idiot... Why!..</p>
					<p>He waved his hand energetically.</p>
					<p>Pierre took off his spectacles, which altered his face, making it look even more good-natured, and gazed in surprise at his friend.</p>
					<p>— My wife, — continued Prince Andréi, — is an excellent woman. She is one of those rare women with whom one can feel secure about one's honor; but, my God, what would I not give now not to be married! You are the first and only one to whom I say this, because I love you.</p>
					<p>Prince Andréi, as he said this, was even less like than before to that Bolkónsky who had lounged in Anna Pávlovna's armchairs and through his teeth, screwing up his eyes, muttered French phrases. His dry face was all quivering with the nervous animation of every muscle; his eyes, in which the fire of life had seemed extinguished before, now gleamed with a radiant, bright luster. It was evident that the more lifeless he seemed at ordinary times, the more energetic he became in moments of irritation.</p>
					<p>— You do not understand why I say this, — he continued. — Why, it is the whole story of life. You speak of Bonaparte and his career, — he said, though Pierre had not spoken of Bonaparte. — You speak of Bonaparte; but Bonaparte, when he worked, went step by step to his goal, he was free, he had nothing but his goal — and he reached it. But tie yourself to a woman — and like a chained convict, you lose all freedom. And all the hopes and strength you have only weigh you down and torment you with regret. Drawing rooms, gossip, balls, vanity, triviality — these are the enchanted circle from which I cannot escape. I am now going to the war, the greatest war there has ever been, and I know nothing and am fit for nothing. <foreign xml:lang="fr" n="I am very amiable and very caustic">Je suis très aimable et très caustique</foreign>, — continued Prince Andréi, — and at Anna Pávlovna's they listen to me. And this stupid society, without which my wife cannot live, and these women... If you only knew what <foreign xml:lang="fr" n="all distinguished women">toutes les femmes distinguées</foreign> and women in general are! My father is right. Egoism, vanity, stupidity, triviality in everything — that is what women are when they show themselves as they are. You look at them in society and think there is something to them, but there is nothing, nothing, nothing! Yes, do not marry, my dear fellow, do not marry, — concluded Prince Andréi.</p>
					<p>— It seems ridiculous to me, — said Pierre, — that <emph>you</emph>, <emph>you</emph> should consider yourself incapable, your life a ruined life. You have everything, everything before you. And you...</p>
					<p>He did not say <emph>what you</emph>, but his tone already showed how highly he valued his friend and how much he expected of him in the future.</p>
					<p>"How can he say this!" thought Pierre. Pierre considered Prince Andréi a model of all perfections precisely because Prince Andréi combined in the highest degree all those qualities that Pierre lacked, and which might best be expressed by the concept of strength of will. Pierre was always amazed by Prince Andréi's ability to deal calmly with all sorts of people, his extraordinary memory, his wide reading (he had read everything, knew everything, had an idea of everything), and most of all his capacity for work and study. If Pierre was often struck in Andréi by a lack of capacity for dreamy philosophizing (to which Pierre was particularly prone), he saw even in this not a defect but a strength.</p>
					<p>In the very best, friendly, and simple relations, flattery or praise is necessary, just as grease is necessary to make wheels turn.</p>
					<p>— <foreign xml:lang="fr" n="I am a finished man">Je suis un homme fini</foreign>, — said Prince Andréi. — What is there to say about me? Let us talk about you, — he said, after a pause, smiling at his own comforting thoughts.</p>
					<p>That smile was instantly reflected on Pierre's face.</p>
					<p>— And what is there to say about me? — said Pierre, relaxing his mouth into a careless, merry smile. — What am I? <foreign xml:lang="fr" n="I am a bastard!">Je suis un bâtard!</foreign> — And he suddenly blushed crimson. It was evident that he had made a great effort to say this. — <foreign xml:lang="fr" n="Without name, without fortune...">Sans nom, sans fortune...</foreign> And really, what does it... — But he did not say <emph>what really</emph>. — I am free for the present, and I am well off. I only do not know at all what I am to begin. I wanted to consult you seriously.</p>
					<p>Prince Andréi looked at him with kind eyes. But in his glance, friendly and affectionate as it was, there was nevertheless an expression of consciousness of his own superiority.</p>
					<p>— You are dear to me, especially because you are the one living man in all our society. You are well off. Choose what you will; it is all the same. You will do well everywhere, but one thing: stop going to those Kurágins, leading this life. It does not suit you at all: all those carousals, and hussar tricks, and all that...</p>
					<p>— <foreign xml:lang="fr" n="What will you have, my dear">Que voulez-vous, mon cher</foreign>, — said Pierre, shrugging his shoulders, — <foreign xml:lang="fr" n="women, my dear, women!">les femmes, mon cher, les femmes!</foreign></p>
					<p>— I do not understand, — answered Andréi. — <foreign xml:lang="fr" n="Respectable women">Les femmes comme il faut</foreign>, that is another matter; but Kurágin's <foreign xml:lang="fr" n="women">les femmes</foreign>, <foreign xml:lang="fr" n="women and wine">les femmes et le vin</foreign>, I do not understand!</p>
					<p>Pierre lived with Prince Vasíli Kurágin and shared the dissipated life of his son Anatole, the very one they were planning to marry to Prince Andréi's sister for the sake of reforming him.</p>
					<p>— Do you know what! — said Pierre, as if a happy thought had unexpectedly struck him, — seriously, I have long been thinking this. With this life I can neither decide nor consider anything. My head aches, I have no money. He invited me today, but I will not go.</p>
					<p>— Give me your word of honor that you will stop going?</p>
					<p>— Word of honor! ————</p>
					<p>It was already past one o'clock in the night when Pierre left his friend. It was a June night in Petersburg, a night without darkness. Pierre got into a hired carriage with the intention of going home. But the nearer he drew, the more he felt the impossibility of falling asleep on this night, which was more like evening or morning. One could see far down the empty streets. On the way Pierre remembered that the usual gambling company was to assemble at Anatole Kurágin's this evening, after which there was usually a drinking bout, ending with one of Pierre's favorite amusements.</p>
					<p>"It would be good to go to Kurágin's," he thought. But he immediately recalled the word of honor he had given Prince Andréi not to visit Kurágin.</p>
					<p>But immediately, as happens with people called weak-willed, he felt such a passionate desire to experience once more that dissipated life, so familiar to him, that he decided to go. And immediately the thought came into his head that his word of honor meant nothing, because even before Prince Andréi, he had also given Prince Anatole his word to be with him; finally, he thought that all these words of honor were such conventional things, having no definite meaning, especially if one considers that perhaps tomorrow he will either die or something so extraordinary will happen to him that there will no longer be anything honorable or dishonorable. Reasonings of this kind, destroying all his resolutions and intentions, often came to Pierre. He drove to Kurágin's.</p>
					<p>Having driven up to the porch of a large house near the Horse Guards barracks, in which Anatole lived, he went up the lighted porch and the stairs, and entered the open door. There was no one in the anteroom; empty bottles, cloaks, and galoshes were lying about; it smelled of wine, and distant talking and shouting could be heard.</p>
					<p>The play and supper were already over, but the guests were not yet leaving. Pierre threw off his cloak and went into the first room, where the remains of supper stood and a single footman, thinking no one saw him, was stealthily finishing the unfinished glasses. From the third room came sounds of scuffling, laughter, the shouts of familiar voices, and the roar of a bear. Some eight young men were crowding anxiously round an open window. Three were struggling with a young bear, which one was dragging by a chain, frightening another with it.</p>
					<p>— I bet a hundred on Stevens! — shouted one.</p>
					<p>— Mind you don't support him! — shouted another.</p>
					<p>— I'm for Dólokhov! — shouted a third. — Separate them, Kurágin.</p>
					<p>— Come, leave Míshka alone, there's a bet on here.</p>
					<p>— At one draught, or else you lose, — shouted a fourth.</p>
					<p>— Yákov! bring a bottle, Yákov! — shouted the host himself, a tall handsome fellow, standing in the middle of the crowd in nothing but a fine shirt unbuttoned halfway down his chest. — Wait, gentlemen. Here is Petrúsha, my dear friend, — he addressed Pierre.</p>
					<p>Another voice, of a rather short man with clear blue eyes, striking particularly among all those drunken voices for its sober expression, shouted from the window: — Come here — judge the bet! — This was Dólokhov, a Semënov officer, a notorious gambler and duelist, who lived with Anatole. Pierre smiled, looking merrily around him.</p>
					<p>— I don't understand anything. What's the matter? — he asked.</p>
					<p>— Wait, he is not drunk. Give me a bottle, — said Anatole, and taking a glass from the table, he went up to Pierre.</p>
					<p>— First of all, drink.</p>
					<p>Pierre began to drink glass after glass, looking from under his brows at the drunken guests, who had again crowded round the window, and listening to their talk. Anatole poured him wine and told him that Dólokhov was betting with the Englishman Stevens, a sailor who was there, that he, Dólokhov, would drink a bottle of rum sitting on the window-sill of the third floor with his legs hanging outside.</p>
					<p>— Come, drink it all! — said Anatole, handing Pierre the last glass, — or I won't let you go!</p>
					<p>— No, I don't want to, — said Pierre, pushing Anatole aside, and went up to the window.</p>
					<p>Dólokhov was holding the Englishman by the hand and clearly, distinctly stating the terms of the bet, addressing himself principally to Anatole and Pierre.</p>
					<p>Dólokhov was a man of medium height, curly-haired and with light blue eyes. He was about twenty-five. He wore no mustache, as did all infantry officers, and his mouth, the most striking feature of his face, was fully visible. The lines of this mouth were remarkably finely curved. In the middle the upper lip descended energetically on the firm lower one in a sharp wedge, and in the corners something like two smiles was constantly forming, one on each side; and all together, and especially in conjunction with his firm, insolent, intelligent gaze, produced an impression such that it was impossible not to notice this face. Dólokhov was a man of little means, without any connections. And despite the fact that Anatole squandered tens of thousands, Dólokhov lived with him and had managed to position himself so that Anatole and all who knew them respected Dólokhov more than Anatole. Dólokhov played all games and almost always won. However much he drank, he never lost his clear head. Both Kurágin and Dólokhov were at that time celebrities in the rake and spendthrift world of Petersburg.</p>
					<p>The bottle of rum was brought; the frame, which prevented sitting on the outer slope of the window, was broken out by two footmen, who were evidently hurrying and intimidated by the advice and shouts of the gentlemen around them.</p>
					<p>Anatole, with his victorious air, went up to the window. He wanted to break something. He pushed the footmen aside and tugged at the frame, but the frame would not yield. He broke a pane of glass.</p>
					<p>— Come now, you strong man, — he turned to Pierre.</p>
					<p>Pierre took hold of the crossbars, pulled, and with a crash broke the oak frame in one place and wrenched it out in another.</p>
					<p>— Take it all out, or they will think I am holding on, — said Dólokhov.</p>
					<p>— Is the Englishman boasting... eh?... is it good?... — Anatole was saying.</p>
					<p>— Good, — said Pierre, looking at Dólokhov, who, taking the bottle of rum in his hands, approached the window, from which could be seen the light of the sky and the morning and evening twilight merging on it.</p>
					<p>Dólokhov jumped onto the window-sill with the bottle of rum in his hand.</p>
					<p>— Listen! — he shouted, standing on the sill and addressing the room. Everyone fell silent.</p>
					<p>— I bet (he spoke in French so that the Englishman should understand him, and spoke that language none too well). — I bet fifty imperials, do you want a hundred? — he added, turning to the Englishman.</p>
					<p>— No, fifty, — said the Englishman.</p>
					<p>— Very well, for fifty imperials, — that I will drink a whole bottle of rum without taking it from my mouth, drink it sitting outside the window, on this spot (he bent down and pointed to the sloping ledge of the wall outside the window) and not holding on to anything... Is that so?...</p>
					<p>— Very good, — said the Englishman.</p>
					<p>Anatole turned to the Englishman and, taking him by the button of his coat and looking down at him (the Englishman was short), began repeating the terms of the bet to him in English.</p>
					<p>— Wait! — cried Dólokhov, tapping the bottle on the window to attract attention. — Wait, Kurágin; listen. If anyone does the same, I pay a hundred imperials. Do you understand?</p>
					<p>The Englishman nodded his head, without giving any indication whether he intended to accept this new bet or not. Anatole would not let the Englishman go, and although he, nodding, gave to understand that he had understood everything, Anatole translated Dólokhov's words into English for him. A young, thin boy, a Life Hussar, who had lost at cards that evening, climbed onto the window, leaned out and looked down.</p>
					<p>— Ooh!... ooh!... ooh!... — he uttered, looking out the window at the stone pavement.</p>
					<p>— Quiet! — shouted Dólokhov, and pulled the officer down from the window, who, getting tangled in his spurs, jumped awkwardly into the room.</p>
					<p>Placing the bottle on the window-sill so that it should be easy to reach, Dólokhov cautiously and quietly climbed into the window. Letting his legs down and bracing both hands against the sides of the window, he measured himself, sat down, let go of his hands, moved to the right, to the left, and reached the bottle. Anatole brought two candles and set them on the window-sill, though it was already quite light. Dólokhov's back in his white shirt and his curly head were illuminated from both sides. Everyone crowded to the window. The Englishman stood in front. Pierre smiled and said nothing. One of those present, older than the rest, with a frightened and angry face, suddenly pushed forward and tried to seize Dólokhov by his shirt.</p>
					<p>— Gentlemen, this is nonsense; he will kill himself to death, — said this more prudent man.</p>
					<p>Anatole stopped him.</p>
					<p>— Don't touch him, you will frighten him, he will be killed. Eh?... What then?... Eh?...</p>
					<p>Dólokhov turned round, adjusting himself and again bracing his hands.</p>
					<p>— If anyone else pokes his nose in, — he said, uttering the words sparsely through his clenched and thin lips, — I will throw him down right here. Well!...</p>
					<p>Having said "well!", he turned again, let go his hands, took the bottle and raised it to his mouth, threw back his head, and flung his free arm upward for balance. One of the footmen, who had begun to pick up the glass, stopped in a bent position, not taking his eyes off the window and Dólokhov's back. Anatole stood upright, his eyes wide open. The Englishman, thrusting his lips forward, watched from the side. The one who had tried to stop him ran into the corner of the room and lay face to the wall on the sofa. Pierre covered his face, and a faint smile, forgotten, remained on his face, though it now expressed horror and fear. Everyone was silent. Pierre took his hands from his eyes. Dólokhov sat in the same position, only his head had tilted back so that the curly hair at the nape of his neck touched his shirt collar, and his arm holding the bottle was rising higher and higher, shuddering and making an effort. The bottle was evidently emptying and rising with it, tilting his head back. "Why is it taking so long?" thought Pierre. It seemed to him that more than half an hour had passed. Suddenly Dólokhov made a backward movement with his spine, and his arm shuddered nervously; this shudder was enough to shift his whole body as he sat on the sloping ledge. He shifted all over, and his arm and head shuddered still more violently, making an effort. One hand rose to grasp the window-sill, but sank again. Pierre closed his eyes again and said to himself that he would never open them again. Suddenly he felt that everything around had begun to stir. He looked: Dólokhov stood on the window-sill, his face pale and cheerful.</p>
					<p>— Empty!</p>
					<p>He threw the bottle to the Englishman, who caught it deftly. Dólokhov jumped down from the window. He smelled strongly of rum.</p>
					<p>— Excellent! Splendid! That's a bet for you! The devil take you entirely! — people shouted from all sides.</p>
					<p>The Englishman, having taken out his purse, was counting out the money. Dólokhov frowned and remained silent. Pierre jumped onto the window.</p>
					<p>— Gentlemen! Who will bet with me? I will do the same, — he suddenly shouted. — And there is no need for a bet, either. Tell them to give me a bottle. I will do it... tell them to give me one.</p>
					<p>— Let him, let him! — said Dólokhov, smiling.</p>
					<p>— What is the matter with you? Are you crazy? Who will let you? You get dizzy even on a staircase, — people began to say from all sides.</p>
					<p>— I will drink it, give me a bottle of rum! — shouted Pierre, striking a chair with a resolute and drunken gesture, and climbed into the window.</p>
					<p>They seized him by the arms; but he was so strong that he pushed far away the one who approached him.</p>
					<p>— No, you will never persuade him that way, — said Anatole, — wait, I will deceive him. Listen, I take your bet, but tomorrow; and now we are all going to ***'s.</p>
					<p>— Let's go, — shouted Pierre, — let's go!... And we will take Míshka with us...</p>
					<p>And he caught the bear, and embracing and lifting him, began to whirl round the room with him.</p>
				</div>"""

es_text_6 = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo VI</head>
					<p>En la habitación contigua crujió un vestido de mujer. Como si despertara, el príncipe Andréi se desperezó y su rostro adoptó la misma expresión que había tenido en el salón de Anna Pávlovna. Pierre bajó las piernas del sofá. Entró la princesa. Llevaba ya otro vestido, de andar por casa, pero igualmente elegante y fresco. El príncipe Andréi se levantó y le ofreció cortésmente una silla.</p>
					<p>— ¿Por qué será?, me pregunto a menudo, — comenzó a decir, como siempre en francés, mientras se acomodaba apresurada y atareadamente en la silla, — ¿por qué será que Annette no se ha casado? Qué estúpidos son todos ustedes, <foreign xml:lang="fr" n="señores">messieurs</foreign>, por no haberse casado con ella. Perdonen, pero no entienden nada de mujeres. ¡Qué discutidor es usted, monsieur Pierre!</p>
					<p>— Siempre estoy discutiendo con su marido también; no entiendo por qué quiere ir a la guerra, — dijo Pierre, dirigiéndose a la princesa sin ninguna de las trabas (tan habituales en las relaciones de un joven con una mujer joven).</p>
					<p>La princesa se sobresaltó. Evidentemente, las palabras de Pierre la habían tocado en lo más vivo.</p>
					<p>— ¡Ah, eso es exactamente lo que yo digo! — exclamó. — No comprendo, no comprendo en absoluto, ¿por qué los hombres no pueden vivir sin la guerra? ¿Por qué nosotras, las mujeres, no queremos nada y no necesitamos nada? Juzgue usted mismo. Se lo repito continuamente: aquí es ayudante de campo de su tío, una posición brillantísima. Todos lo conocen muy bien y lo aprecian mucho. El otro día en casa de los Apráksin oí a una señora que preguntaba: <foreign xml:lang="fr" n="¿es ese el famoso príncipe Andréi? ¡Palabra de honor!">c'est èa le fameux prince André? Ma parole d'honneur!</foreign> — Se rió. — Es tan bien recibido en todas partes. También podría ser muy fácilmente ayudante de campo del emperador. Sabe, el Emperador le habló con mucha amabilidad. Annette y yo estábamos hablando, sería muy fácil arreglarlo. ¿Qué opina?</p>
					<p>Pierre miró al príncipe Andréi y, al notar que a su amigo no le agradaba esta conversación, no respondió.</p>
					<p>— ¿Cuándo te vas? — preguntó.</p>
					<p>— <foreign xml:lang="fr" n="Ah, no me hables de esa partida, no me hables de ella. No quiero oír hablar de ello">Ah! ne me parlez pas de ce départ, ne m'en parlez pas. Je ne veux pas en entendre parler</foreign>, — la princesa empezó a hablar en aquel tono caprichosamente juguetón con el que había hablado con Hippolyte en el salón, y que tan evidentemente desentonaba con el círculo familiar en el que Pierre era como un miembro más. — Hoy, al pensar que debemos romper todas estas queridas relaciones... Y además, ¿sabes, <foreign xml:lang="fr" n="Andréi">André</foreign>? — Le guiñó un ojo a su marido. — <foreign xml:lang="fr" n="¡Tengo miedo, tengo miedo!">J'ai peur, j'ai peur!</foreign> — susurró, estremeciéndosele la espalda.</p>
					<p>Su marido la miró como sorprendido al notar que había alguien más en la habitación aparte de él y Pierre: sin embargo, se dirigió a su esposa inquiriendo con fría cortesía:</p>
					<p>— ¿De qué tienes miedo, Lise? No lo comprendo, — dijo.</p>
					<p>— Mira cómo todos los hombres son egoístas; ¡todos, todos egoístas! Él mismo, por sus propios caprichos, sabe Dios por qué, me deja y me encierra sola en el campo.</p>
					<p>— Con mi padre y mi hermana, no lo olvides, — dijo en voz baja el príncipe Andréi.</p>
					<p>— Sola de todas formas, sin <emph>mis</emph> amigos... Y quiere que no tenga miedo.</p>
					<p>Su tono era ya gruñón, su labio respingón se levantó, dando a su rostro una expresión no alegre, sino bestial, parecida a la de una ardilla. Se calló, como si le pareciera impropio hablar de su embarazo delante de Pierre, cuando en realidad ésa era la esencia de la cuestión.</p>
					<p>— Aún no he comprendido <foreign xml:lang="fr" n="de qué tienes miedo">de quoi vous avez peur</foreign>, — pronunció lentamente el príncipe Andréi, sin quitarle los ojos de encima a su mujer.</p>
					<p>La princesa se ruborizó y agitó los brazos con desesperación.</p>
					<p>— <foreign xml:lang="fr" n="No, Andréi, te digo que has cambiado tanto, tanto...">Non, André, je dis que vous avez tellement, tellement changé...</foreign></p>
					<p>— Tu médico te manda que te acuestes más temprano, — dijo el príncipe Andréi. — Será mejor que te vayas a dormir.</p>
					<p>La princesa no dijo nada, y de repente su breve labio velludo tembló; el príncipe Andréi, levantándose y encogiéndose de hombros, atravesó la habitación.</p>
					<p>Pierre miraba con ingenua sorpresa a través de sus gafas, tan pronto a él como a la princesa, y se removió como si él también quisiera levantarse, pero volvió a cambiar de idea.</p>
					<p>— Qué más me da que monsieur Pierre esté aquí, — dijo de repente la princesita, y su bonito rostro se deshizo repentinamente en una mueca de llanto. — Hace tiempo que quería decírtelo, <foreign xml:lang="fr" n="Andréi">André</foreign>: ¿por qué has cambiado así conmigo? ¿Qué te he hecho? Te vas al ejército y no sientes piedad por mí. ¿Por qué?</p>
					<p>— ¡Lise! — fue todo lo que dijo el príncipe Andréi; pero en aquella palabra había una súplica, una amenaza y, sobre todo, la seguridad de que ella misma se arrepentiría de sus palabras; pero ella continuó apresuradamente:</p>
					<p>— Me tratas como a una enferma o a una niña. Lo veo todo. ¿Eras así hace seis meses?</p>
					<p>— Lise, te ruego que pares, — dijo el príncipe Andréi aún más expresivamente.</p>
					<p>Pierre, que cada vez se agitaba más durante esta conversación, se levantó y se acercó a la princesa. Parecía incapaz de soportar la vista de las lágrimas y estaba dispuesto a llorar él mismo.</p>
					<p>— Cálmese, princesa. A usted se lo parece, porque le aseguro que yo mismo he experimentado... por qué... porque... No, perdone, un extraño está aquí fuera de lugar... No, cálmese... Adiós...</p>
					<p>El príncipe Andréi le detuvo por el brazo.</p>
					<p>— No, quédese, Pierre. La princesa es demasiado amable para querer privarme del placer de pasar la velada con usted.</p>
					<p>— No, sólo piensa en sí mismo, — murmuró la princesa, sin contener sus lágrimas de ira.</p>
					<p>— Lise, — dijo secamente el príncipe Andréi, elevando el tono a ese punto que indica que la paciencia se ha agotado.</p>
					<p>De pronto, la expresión enfadada de ardilla de la bonita cara de la princesa fue sustituida por una expresión atractiva de miedo que despertaba lástima; miró por debajo del ceño con sus hermosos ojos a su marido, y en su rostro apareció esa expresión tímida y de confesión que tiene un perro cuando mueve rápida pero débilmente su cola caída.</p>
					<p>— <foreign xml:lang="fr" n="¡Dios mío, Dios mío!">Mon Dieu, mon Dieu!</foreign> — murmuró la princesa y, recogiéndose con una mano un pliegue del vestido, se acercó a su marido y le dio un beso en la frente.</p>
					<p>— <foreign xml:lang="fr" n="Buenas noches, Lise">Bonsoir, Lise</foreign>, — dijo el príncipe Andréi, levantándose y, cortésmente, como a una extraña, besándole la mano. ————</p>
					<p>Los amigos guardaron silencio. Ninguno de los dos empezó a hablar. Pierre miró al príncipe Andréi; éste se frotó la frente con su pequeña mano.</p>
					<p>— Vamos a cenar, — dijo suspirando, levantándose y yendo hacia la puerta.</p>
					<p>Entraron en el comedor, elegante, nuevo y ricamente decorado. Todo, desde las servilletas hasta la plata, la porcelana y el cristal, llevaba ese peculiar sello de novedad que se encuentra en la casa de los recién casados. A mitad de la cena, el príncipe Andréi se apoyó en el codo y, como un hombre que lleva mucho tiempo con algo en el corazón y de repente decide hablar, con una expresión de irritación nerviosa como Pierre no había visto nunca en el rostro de su amigo, empezó a hablar:</p>
					<p>— Nunca, nunca te cases, amigo mío; éste es mi consejo: no te cases hasta que puedas decirte a ti mismo que has hecho todo lo que podías, y hasta que hayas dejado de amar a la mujer que has elegido, hasta que la veas con claridad; de lo contrario, cometerás un error cruel e irreparable. Cásate cuando seas un anciano que no sirva para nada... De lo contrario, se perderá todo lo que hay de bueno y noble en ti. Todo se derrochará en pequeñeces. ¡Sí, sí, sí! No me mires con tanta sorpresa. Si esperas algo de ti mismo en el futuro, a cada paso sentirás que para ti todo se ha acabado, todo está cerrado excepto el salón, donde estarás al mismo nivel que un lacayo de la corte y un idiota... ¡Qué más da!..</p>
					<p>Agitó la mano enérgicamente.</p>
					<p>Pierre se quitó las gafas, lo que alteró su rostro, haciéndole parecer aún más bonachón, y miró sorprendido a su amigo.</p>
					<p>— Mi esposa, — continuó el príncipe Andréi, — es una mujer excelente. Es una de esas raras mujeres con las que uno puede sentirse seguro en cuanto a su honor; pero, Dios mío, ¡qué no daría yo ahora por no estar casado! Eres el primero y el único a quien se lo digo, porque te quiero.</p>
					<p>El príncipe Andréi, al decir esto, se parecía aún menos que antes a aquel Bolkónsky que se había repantingado en los sillones de Anna Pávlovna y mascullaba frases en francés entre dientes, entornando los ojos. Su enjuto rostro temblaba con la animación nerviosa de todos sus músculos; sus ojos, en los que el fuego de la vida parecía antes extinguido, brillaban ahora con un fulgor resplandeciente y vivo. Era evidente que cuanto más inanimado parecía en tiempos normales, más enérgico se volvía en los momentos de irritación.</p>
					<p>— No entiendes por qué digo esto, — continuó. — Pues porque es toda la historia de la vida. Hablas de Bonaparte y de su carrera, — dijo, aunque Pierre no había hablado de Bonaparte. — Hablas de Bonaparte; pero Bonaparte, cuando trabajaba, iba paso a paso hacia su meta, era libre, no tenía más que su meta, y la alcanzó. Pero si te atas a una mujer, y como un presidiario encadenado, pierdes toda tu libertad. Y todas las esperanzas y fuerzas que tienes sólo te pesan y te atormentan de arrepentimiento. Los salones, los cotilleos, los bailes, la vanidad, la trivialidad... son el círculo encantado del que no puedo escapar. Ahora voy a la guerra, la guerra más grande que ha habido nunca, y no sé nada y no sirvo para nada. <foreign xml:lang="fr" n="Soy muy amable y muy cáustico">Je suis très aimable et très caustique</foreign>, — prosiguió el príncipe Andréi, — y en casa de Anna Pávlovna me escuchan. Y esta estúpida sociedad sin la cual mi mujer no puede vivir, y estas mujeres... ¡Si supieras lo que son <foreign xml:lang="fr" n="todas las mujeres distinguidas">toutes les femmes distinguées</foreign> y las mujeres en general! Mi padre tiene razón. Egoísmo, vanidad, estupidez, trivialidad en todo... eso es lo que son las mujeres cuando se muestran tal como son. Las miras en sociedad y crees que hay algo en ellas, ¡pero no hay nada, nada, nada! Sí, no te cases, querido amigo, no te cases, — concluyó el príncipe Andréi.</p>
					<p>— Me parece ridículo, — dijo Pierre, — que <emph>tú</emph>, <emph>tú</emph> te consideres incapaz, tu vida una vida arruinada. Tienes de todo, todo por delante. Y tú...</p>
					<p>No dijo <emph>qué tú</emph>, pero su tono mostraba ya en qué alta estima tenía a su amigo y cuánto esperaba de él en el futuro.</p>
					<p>"¡Cómo puede decir esto!", pensó Pierre. Pierre consideraba al príncipe Andréi un modelo de todas las perfecciones precisamente porque el príncipe Andréi reunía en sumo grado todas las cualidades de las que Pierre carecía, y que mejor podrían expresarse mediante el concepto de fuerza de voluntad. A Pierre siempre le asombró la capacidad del príncipe Andréi para tratar con calma a todo tipo de personas, su extraordinaria memoria, su amplia lectura (lo había leído todo, lo sabía todo, tenía idea de todo) y, sobre todo, su capacidad para el trabajo y el estudio. Si a Pierre le sorprendía a menudo en Andréi la falta de capacidad para filosofar ensoñadoramente (a lo que Pierre era particularmente propenso), veía incluso en esto no un defecto sino una fuerza.</p>
					<p>En las mejores relaciones de amistad y sencillez, la adulación o el elogio son necesarios, al igual que la grasa es necesaria para que las ruedas giren.</p>
					<p>— <foreign xml:lang="fr" n="Soy un hombre acabado">Je suis un homme fini</foreign>, — dijo el príncipe Andréi. — ¿Qué hay que decir de mí? Hablemos de ti, — dijo, tras una pausa, sonriendo ante sus propios y reconfortantes pensamientos.</p>
					<p>Aquella sonrisa se reflejó al instante en el rostro de Pierre.</p>
					<p>— ¿Y qué se puede decir de mí? — dijo Pierre, relajando la boca en una sonrisa despreocupada y alegre. — ¿Qué soy yo? <foreign xml:lang="fr" n="¡Soy un bastardo!">Je suis un bâtard!</foreign> — Y de repente se puso rojo como un tomate. Era evidente que había hecho un gran esfuerzo para decir esto. — <foreign xml:lang="fr" n="Sin nombre, sin fortuna...">Sans nom, sans fortune...</foreign> Y la verdad, qué importa... — Pero no dijo <emph>qué importaba</emph>. — Por el momento soy libre, y estoy bien posicionado. Sólo que no sé en absoluto qué debo empezar. Quería consultarte en serio.</p>
					<p>El príncipe Andréi le miró con ojos bondadosos. Pero en su mirada, por muy amistosa y afectuosa que fuera, había sin embargo una expresión de conciencia de su propia superioridad.</p>
					<p>— Me eres querido, sobre todo porque eres el único hombre vivo de toda nuestra sociedad. Estás bien. Elige lo que quieras; da lo mismo. Te irá bien en todas partes, pero una cosa: deja de ir a casa de los Kurágin, de llevar esa vida. No te va en absoluto: todas esas juergas y tonterías de húsares, y todo eso...</p>
					<p>— <foreign xml:lang="fr" n="Qué quieres, amigo mío">Que voulez-vous, mon cher</foreign>, — dijo Pierre, encogiéndose de hombros, — <foreign xml:lang="fr" n="¡las mujeres, amigo mío, las mujeres!">les femmes, mon cher, les femmes!</foreign></p>
					<p>— No lo entiendo, — contestó Andréi. — <foreign xml:lang="fr" n="Las mujeres respetables">Les femmes comme il faut</foreign>, eso es otra cosa; pero <foreign xml:lang="fr" n="las mujeres">les femmes</foreign> de Kurágin, <foreign xml:lang="fr" n="las mujeres y el vino">les femmes et le vin</foreign>, ¡no lo entiendo!</p>
					<p>Pierre vivía con el príncipe Vasíli Kurágin y compartía la vida disipada de su hijo Anatole, precisamente aquel a quien planeaban casar con la hermana del príncipe Andréi para intentar reformarle.</p>
					<p>— ¡Sabes una cosa! — dijo Pierre, como si inesperadamente se le hubiera ocurrido una idea feliz, — en serio, hace tiempo que lo pienso. Con esta vida no puedo decidir ni considerar nada. Me duele la cabeza, no tengo dinero. Hoy me ha invitado, pero no iré.</p>
					<p>— ¿Me das tu palabra de honor de que dejarás de ir?</p>
					<p>— ¡Palabra de honor! ————</p>
					<p>Era ya pasada la una de la madrugada cuando Pierre dejó a su amigo. Era una noche de junio en Petersburgo, una noche sin oscuridad. Pierre subió a un carruaje de alquiler con la intención de ir a casa. Pero cuanto más se acercaba, más sentía la imposibilidad de conciliar el sueño en aquella noche, que más parecía una tarde o una mañana. Se podía ver muy lejos por las calles vacías. Por el camino, Pierre recordó que la habitual compañía de juego iba a reunirse aquella noche en casa de Anatole Kurágin, después de lo cual solía haber una borrachera que terminaba con una de las diversiones favoritas de Pierre.</p>
					<p>"Estaría bien ir a casa de Kurágin", pensó. Pero inmediatamente recordó la palabra de honor que había dado al príncipe Andréi de no visitar a Kurágin.</p>
					<p>Pero de inmediato, como sucede con las personas llamadas de voluntad débil, sintió un deseo tan apasionado de volver a experimentar aquella vida disipada y tan familiar para él, que decidió ir. Y de inmediato le vino a la cabeza la idea de que su palabra de honor no significaba nada, porque incluso antes del príncipe Andréi, también había dado al príncipe Anatole su palabra de estar con él; por último, pensó que todas esas palabras de honor eran cosas tan convencionales que no tenían ningún sentido definido, sobre todo si se tiene en cuenta que quizá mañana morirá él o le sucederá algo tan extraordinario que ya no habrá nada honorable o deshonroso. Razonamientos de este tipo, que destruían todas sus resoluciones e intenciones, acudían a menudo a Pierre. Se dirigió a casa de Kurágin.</p>
					<p>Habiendo llegado al porche de una casa grande cerca del cuartel de la Guardia a Caballo, en la que vivía Anatole, subió al porche iluminado y a las escaleras, y entró por la puerta abierta. No había nadie en la antesala; había botellas vacías, capas y chanclos esparcidos; olía a vino y se oían ruidos de voces y gritos lejanos.</p>
					<p>El juego y la cena ya habían terminado, pero los invitados aún no se marchaban. Pierre se quitó la capa y entró en la primera habitación, donde estaban los restos de la cena y un solo lacayo que, pensando que nadie le veía, se terminaba a hurtadillas las copas inacabadas. De la tercera habitación llegaban ruidos de forcejeos, risas, los gritos de voces conocidas y el rugido de un oso. Unos ocho jóvenes se agolpaban ansiosamente en torno a una ventana abierta. Tres se peleaban con un oso joven, al que uno arrastraba con una cadena asustando con él a otro.</p>
					<p>— ¡Apuesto cien por Stevens! — gritaba uno.</p>
					<p>— ¡Cuidado con no apoyarle! — gritaba otro.</p>
					<p>— ¡Yo voy a favor de Dólokhov! — gritó un tercero. — Sepáralos, Kurágin.</p>
					<p>— Vamos, dejad a Míshka en paz, hay una apuesta de por medio.</p>
					<p>— De un trago, o pierdes, — gritó un cuarto.</p>
					<p>— ¡Yákov! ¡Trae una botella, Yákov! — gritó el propio anfitrión, un mozo alto y apuesto, que estaba en medio de la multitud vestido sólo con una camisa fina desabrochada hasta la mitad del pecho. — Esperen, señores. Aquí está Petrúsha, mi querido amigo, — se dirigió a Pierre.</p>
					<p>Otra voz, la de un hombre más bien bajo y de claros ojos azules, que llamaba especialmente la atención entre todas aquellas voces borrachas por su expresión sobria, gritó desde la ventana: — ¡Ven aquí, juzga la apuesta! — Era Dólokhov, un oficial del Semënovsky, famoso jugador y duelista, que vivía con Anatole. Pierre sonrió, mirando alegremente a su alrededor.</p>
					<p>— No entiendo nada. ¿Qué pasa? — preguntó.</p>
					<p>— Esperad, no está borracho. Dame una botella, — dijo Anatole, y cogiendo un vaso de la mesa, se acercó a Pierre.</p>
					<p>— Antes que nada, bebe.</p>
					<p>Pierre empezó a beber copa tras copa, mirando de soslayo a los borrachos, que se habían vuelto a agolpar alrededor de la ventana, y escuchando sus conversaciones. Anatole le sirvió vino y le contó que Dólokhov había apostado con el inglés Stevens, un marinero que andaba por allí, que él, Dólokhov, se bebería una botella de ron sentado en el alféizar de la ventana del tercer piso con las piernas colgando hacia fuera.</p>
					<p>— ¡Venga, bébetelo todo! — dijo Anatole, tendiéndole a Pierre el último vaso, — ¡o no te dejaré ir!</p>
					<p>— No, no quiero, — dijo Pierre, apartando a Anatole, y se acercó a la ventana.</p>
					<p>Dólokhov tenía agarrado por la mano al inglés y, con toda claridad, enumeraba las condiciones de la apuesta, dirigiéndose principalmente a Anatole y a Pierre.</p>
					<p>Dólokhov era un hombre de estatura media, pelo rizado y ojos azules claros. Tenía unos veinticinco años. No llevaba bigote, como todos los oficiales de infantería, y su boca, el rasgo más llamativo de su rostro, era totalmente visible. Las líneas de su boca eran extraordinariamente finas y curvas. En el centro, el labio superior descendía enérgicamente sobre el firme inferior en una cuña afilada, y en las comisuras se formaba constantemente algo parecido a dos sonrisas, una a cada lado; y en conjunto, y sobre todo en conjunción con su mirada firme, insolente e inteligente, producía una impresión tal que era imposible no fijarse en ese rostro. Dólokhov era un hombre de escasos recursos y sin contactos. Y a pesar de que Anatole despilfarraba decenas de miles, Dólokhov vivía con él y se las había arreglado para posicionarse de tal modo que Anatole y todos los que los conocían respetaban a Dólokhov más que a Anatole. Dólokhov jugaba a todos los juegos y casi siempre ganaba. Por mucho que bebiera, nunca perdía su lucidez mental. Tanto Kurágin como Dólokhov eran en aquella época celebridades en el mundo de los calaveras y derrochadores de Petersburgo.</p>
					<p>Trajeron la botella de ron; el marco de la ventana, que impedía sentarse en el borde exterior, fue arrancado por dos lacayos, que evidentemente tenían prisa y estaban intimidados por los consejos y gritos de los señores que les rodeaban.</p>
					<p>Anatole, con su aire victorioso, se acercó a la ventana. Quería romper algo. Apartó a los lacayos y tiró del marco, pero éste no cedía. Rompió un cristal.</p>
					<p>— Ven ahora, tú, hombre fuerte, — se volvió hacia Pierre.</p>
					<p>Pierre agarró los travesaños, tiró, y con un estrépito rompió el marco de roble por un sitio y lo arrancó por otro.</p>
					<p>— Quítalo todo, o se pensarán que me agarro, — dijo Dólokhov.</p>
					<p>— ¿Se jacta el inglés... eh?... ¿es bueno?... — decía Anatole.</p>
					<p>— Bueno, — dijo Pierre, mirando a Dólokhov, que, cogiendo la botella de ron entre sus manos, se acercó a la ventana, desde la que se veía la luz del cielo y el crepúsculo matutino y vespertino fundiéndose en él.</p>
					<p>Dólokhov saltó al alféizar de la ventana con la botella de ron en la mano.</p>
					<p>— ¡Escuchad! — gritó, de pie en el alféizar y dirigiéndose a la sala. Todos callaron.</p>
					<p>— Apuesto (habló en francés para que el inglés le entendiera, y no hablaba ese idioma demasiado bien). — Apuesto cincuenta imperiales, ¿quiere cien? — añadió, dirigiéndose al inglés.</p>
					<p>— No, cincuenta, — dijo el inglés.</p>
					<p>— Muy bien, por cincuenta imperiales, — que me beberé una botella entera de ron sin separarla de la boca, me la beberé sentado en la ventana, en este sitio (se inclinó y señaló la repisa inclinada del muro exterior de la ventana) y sin agarrarme a nada... ¿Es así?...</p>
					<p>— Muy bien, — dijo el inglés.</p>
					<p>Anatole se volvió hacia el inglés y, cogiéndole por el botón de la levita y mirándole desde arriba (el inglés era bajito), empezó a repetirle en inglés los términos de la apuesta.</p>
					<p>— ¡Espera! — gritó Dólokhov, golpeando con la botella en la ventana para llamar la atención. — Espera, Kurágin; escucha. Si alguien hace lo mismo, pago cien imperiales. ¿Entiendes?</p>
					<p>El inglés asintió con la cabeza, sin indicar en absoluto si pensaba aceptar o no esta nueva apuesta. Anatole no soltaba al inglés, y aunque éste, asintiendo, dio a entender que lo había comprendido todo, Anatole le tradujo al inglés las palabras de Dólokhov. Un chiquillo joven y delgado, de los Húsares de la Vida, que había perdido a las cartas aquella noche, se encaramó a la ventana, se asomó y miró hacia abajo.</p>
					<p>— ¡Oh!... ¡oh!... ¡oh!... — profirió, mirando por la ventana al pavimento de piedra.</p>
					<p>— ¡Callad! — gritó Dólokhov, y tiró de la ventana al oficial, que, enredándose con las espuelas, saltó torpemente al interior de la habitación.</p>
					<p>Colocando la botella en el alféizar para tenerla a mano, Dólokhov se encaramó cautelosa y silenciosamente a la ventana. Dejando caer las piernas y apoyando ambas manos en los lados de la ventana, tomó medidas, se sentó, soltó las manos, se movió hacia la derecha, hacia la izquierda, y alcanzó la botella. Anatole trajo dos velas y las colocó en el alféizar, aunque ya era bastante de día. La espalda de Dólokhov en su camisa blanca y su cabeza rizada estaban iluminadas por ambos lados. Todos se agolparon en la ventana. El inglés se colocó delante. Pierre sonrió y no dijo nada. Uno de los presentes, de más edad que los demás, con cara de asustado y enfadado, se adelantó de repente e intentó agarrar a Dólokhov por la camisa.</p>
					<p>— Señores, esto es una tontería; se va a matar de muerte, — dijo este hombre más prudente.</p>
					<p>Anatole le detuvo.</p>
					<p>— No lo toques, lo asustarás y se matará. ¿Eh?... ¿Y entonces qué?... ¿Eh?...</p>
					<p>Dólokhov se dio la vuelta, arreglándose y apoyando de nuevo las manos.</p>
					<p>— Si alguien más mete las narices, — dijo, pronunciando las palabras con parsimonia a través de sus labios finos y apretados, — lo tiraré abajo ahora mismo. ¡Bueno!...</p>
					<p>Tras decir "¡bueno!", volvió a girarse, soltó las manos, cogió la botella y se la llevó a la boca, echó la cabeza hacia atrás y lanzó el brazo libre hacia arriba para mantener el equilibrio. Uno de los lacayos, que había empezado a recoger los cristales, se detuvo en postura encorvada, sin quitar ojo de la ventana ni de la espalda de Dólokhov. Anatole estaba muy derecho, con los ojos muy abiertos. El inglés, echando los labios hacia delante, observaba desde un lado. El que había intentado detenerle corrió a un rincón de la habitación y se tumbó boca abajo en el sofá. Pierre se tapó la cara, y una débil sonrisa, ya olvidada, permaneció en su rostro, aunque ahora expresaba horror y miedo. Todos guardaban silencio. Pierre apartó las manos de los ojos. Dólokhov estaba sentado en la misma postura, sólo que su cabeza se había inclinado hacia atrás, de modo que el pelo rizado de su nuca rozaba el cuello de la camisa, y su brazo que sostenía la botella subía cada vez más, temblando y haciendo un esfuerzo. Evidentemente, la botella se estaba vaciando y subía con él, inclinando su cabeza hacia atrás. "¿Por qué tarda tanto?", pensaba Pierre. Le pareció que había pasado más de media hora. De repente, Dólokhov hizo un movimiento hacia atrás con la espalda y su brazo se estremeció nerviosamente; este estremecimiento bastó para que se desplazara todo su cuerpo mientras estaba sentado en el saliente inclinado. Se desplazó por todas partes, y su brazo y su cabeza temblaron con más violencia aún, haciendo un esfuerzo. Una mano se alzó para agarrarse al alféizar, pero volvió a hundirse. Pierre volvió a cerrar los ojos y se dijo a sí mismo que no volvería a abrirlos jamás. De repente sintió que todo alrededor empezaba a agitarse. Miró: Dólokhov estaba de pie en el alféizar de la ventana, con el rostro pálido y alegre.</p>
					<p>— ¡Vacía!</p>
					<p>Le lanzó la botella al inglés, que la atrapó hábilmente. Dólokhov saltó de la ventana. Olía fuertemente a ron.</p>
					<p>— ¡Excelente! ¡Espléndido! ¡Eso sí que es una apuesta! ¡Que el diablo se os lleve a todos! — gritaba la gente por todos lados.</p>
					<p>El inglés, tras sacar su bolsa, estaba contando el dinero. Dólokhov frunció el ceño y permaneció en silencio. Pierre saltó a la ventana.</p>
					<p>— ¡Señores! ¿Quién quiere apostar conmigo? Yo haré lo mismo, — gritó de repente. — Y además no hace falta apostar. Que me den una botella. Yo lo haré... que me den una.</p>
					<p>— ¡Dejadle, dejadle! — dijo Dólokhov, sonriendo.</p>
					<p>— ¿Qué te pasa? ¿Te has vuelto loco? ¿Quién te va a dejar? Tú te mareas hasta en una escalera, — empezó a decir la gente por todas partes.</p>
					<p>— ¡Me la beberé, dadme una botella de ron! — gritó Pierre, golpeando una silla con ademán resuelto y borracho, y se subió a la ventana.</p>
					<p>Le agarraron de los brazos; pero él era tan fuerte que empujó muy lejos al que se le acercaba.</p>
					<p>— No, así no le convenceréis nunca, — dijo Anatole, — esperad, yo le engañaré. Escucha, acepto tu apuesta, pero mañana; y ahora nos vamos todos a casa de ***.</p>
					<p>— ¡Vamos, — gritó Pierre, — vamos!... Y nos llevaremos a Míshka con nosotros...</p>
					<p>Y atrapó al oso y, abrazándole y levantándole, se puso a dar vueltas por la habitación con él.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

ch6_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="6">'))
text = text[:ch6_start] + en_text_6 + '\n' + es_text_6 + '\n' + text[ch6_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
