import re

en_text_7 = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter VII</head>
					<p>Prince Vasíli kept the promise he had given at Anna Pávlovna's evening party to Princess Drubetskáya, who had asked him on behalf of her only son, Borís. The Emperor was spoken to about him, and, making an exception to the rule, he was transferred to the Semënovsky Guards regiment as an ensign. But Borís was never appointed an aide-de-camp or attached to Kutúzov, despite all the efforts and intrigues of Anna Mikháylovna. Soon after Anna Pávlovna's evening party, Anna Mikháylovna returned to Moscow, going straight to her rich relations, the Rostóvs, with whom she stayed in Moscow and where her adored Borénka, who had just been promoted to ensign in the army and immediately transferred to the Guards, had been brought up from childhood and lived for years. The Guards had already left Petersburg on the 10th of August, and the son, who had remained in Moscow for his equipment, was to overtake them on the road to Radzivílov.</p>
					<p>It was the name-day of the two Natályas, the mother and the younger daughter of the Rostóvs. From morning till night, carriages with teams of horses kept driving up and driving away, bringing visitors to congratulate the countess to her large, well-known house on the Povarskáya. The countess, with her beautiful eldest daughter and the guests, who did not cease to succeed one another, sat in the drawing room.</p>
					<p>The countess was a woman with an Oriental type of thin face, about forty-five years old, evidently exhausted by childbearing; she had had twelve children. The slowness of her movements and speech, proceeding from weakness, gave her a dignified air which inspired respect. Princess Anna Mikháylovna Drubetskáya, as an intimate friend of the house, sat there too, helping to receive the guests and keep up the conversation. The young people were in the back rooms, not finding it necessary to take part in receiving visits. The count met the guests and saw them out, inviting everyone to dinner.</p>
					<p>— I am very, very grateful to you, <foreign xml:lang="fr" n="my dear">ma chère</foreign> or <foreign xml:lang="fr" n="my dear">mon cher</foreign> — (he said <foreign xml:lang="fr" n="my dear">ma chère</foreign> or <foreign xml:lang="fr" n="my dear">mon cher</foreign> to everyone without exception, without the slightest shades of difference, to those above him as well as to those below him) — on my own behalf and on behalf of the dear name-day girls. Mind now, you must come to dinner. You will offend me, <foreign xml:lang="fr" n="my dear">mon cher</foreign>. I entreat you cordially on behalf of the whole family, <foreign xml:lang="fr" n="my dear">ma chère</foreign>. — These words, with the same expression on his full, cheerful, and clean-shaven face, and with the same firm handshake and repeated short bows, he spoke to everyone without exception or alteration. Having seen a guest out, the count returned to the one or those who were still in the drawing room; drawing up an armchair, with the air of a man who likes and knows how to live, legs spread wide and hands on his knees, he swayed significantly, offered guesses about the weather, gave advice about health, sometimes in Russian, sometimes in very bad but self-confident French, and again, with the air of a man tired but firm in the fulfillment of his duty, went to see out, smoothed his sparse gray hair over his bald spot, and again invited to dinner. Sometimes, returning from the anteroom, he passed through the conservatory and the pantry into the large marble hall, where the table was being laid for eighty covers, and looking at the footmen, who were carrying silver and china, setting out the tables, and unfolding damask tablecloths, he called to Dmítry Vasílyevich, a nobleman who managed all his affairs, and said:</p>
					<p>— Well, well, Mítenka, see that everything is right. That's it, that's it, — he said, looking with pleasure at the huge extended table. — The main thing is the serving. That's it... — And he went away, sighing complacently, back to the drawing room.</p>
					<p>— Márya Lvóvna Karágina and her daughter! — the countess's huge footman announced in a bass voice, entering the drawing-room door. The countess thought a moment and took a pinch from a gold snuffbox with her husband's portrait.</p>
					<p>— I am tormented by these visits, — she said. — Well, I will receive her, and that will be the last. She is very prim. Ask her in, — she said to the footman in a sad voice, as if saying: "Well, finish me off!"</p>
					<p>A tall, stout lady with a proud air, accompanied by her round-faced, smiling daughter, entered the drawing room, rustling their dresses.</p>
					<p>— <foreign xml:lang="fr" n="Dear countess, it has been so long... the poor child has been in bed... at the Razumóvskys' ball... and Countess Apráksina... I was so happy...">Chère comtesse, il y a si longtemps... elle a été alitée la pauvre enfant... au bal des Razoumowsky... et la comtesse Apraksine... j'ai été si heureuse...</foreign> — lively women's voices were heard, interrupting one another and blending with the rustle of dresses and the moving of chairs. That conversation began which is kept up just long enough to enable one at the first pause to rise, rustle one's dresses, say: <foreign xml:lang="fr" n="I am very charmed; mama's health... and Countess Apráksina">Je suis bien charmée; la santé de maman... et la comtesse Apraksine</foreign>, and again, rustling one's dresses, to pass into the anteroom, put on a fur coat or cloak, and drive away. The conversation turned to the chief town news of the time — the illness of the famous rich man and handsome man of Catherine's time, the old Count Bezúkhov, and his illegitimate son Pierre, who had behaved so improperly at Anna Pávlovna Schérer's evening party.</p>
					<p>— I am very sorry for the poor count, — said the visitor, — his health is bad enough as it is, and now this grief from his son will kill him!</p>
					<p>— What is it? — asked the countess, as if she did not know what the visitor was talking about, though she had already heard the cause of Count Bezúkhov's grief fifteen times.</p>
					<p>— That is modern education! Even abroad, — said the visitor, — this young man was left to himself, and now in Petersburg, they say, he has done such terrible things that he has been expelled from there by the police.</p>
					<p>— You don't say! — said the countess.</p>
					<p>— He chose his acquaintances badly, — Princess Anna Mikháylovna intervened. — The son of Prince Vasíli, he, and a certain Dólokhov, they say, did God knows what. And both suffered. Dólokhov has been degraded to the ranks, and Bezúkhov's son has been sent to Moscow. As for Anatole Kurágin, his father somehow hushed it up. But he was expelled from Petersburg anyway.</p>
					<p>— But what exactly did they do? — asked the countess.</p>
					<p>— They are perfect brigands, especially Dólokhov, — the visitor was saying. — He is the son of Márya Ivánovna Dólokhova, such a respectable lady, and what do you think? Can you imagine: the three of them got a bear somewhere, put it in the carriage with them, and took it to the actresses'. The police ran up to calm them down. They caught the police officer and tied him back to back to the bear, and let the bear into the Moýka; the bear swims, and the police officer is on it.</p>
					<p>— A fine figure, <foreign xml:lang="fr" n="my dear">ma chère</foreign>, the police officer must have cut, — cried the count, dying of laughter.</p>
					<p>— Oh, what horror! What is there to laugh at, count?</p>
					<p>But the ladies could not help laughing themselves.</p>
					<p>— They barely saved the unfortunate man, — continued the visitor. — And this is how the son of Count Kiríll Vladímirovich Bezúkhov so cleverly amuses himself! — she added. — And they said he was so well-educated and intelligent. This is what all this foreign education has led to. I hope no one will receive him here, despite his wealth. They wanted to introduce him to me. I flatly refused: I have daughters.</p>
					<p>— Why do you say this young man is so rich? — asked the countess, leaning away from the girls, who immediately pretended not to be listening. — After all, he only has illegitimate children. It seems... Pierre too is illegitimate.</p>
					<p>The visitor waved her hand.</p>
					<p>— He has twenty illegitimate ones, I think.</p>
					<p>Princess Anna Mikháylovna joined in the conversation, evidently wishing to show her connections and her knowledge of all worldly circumstances.</p>
					<p>— The thing is this, — she said significantly and also in a half-whisper. — Count Kiríll Vladímirovich's reputation is known... He has lost count of his own children, but this Pierre was a favorite.</p>
					<p>— How handsome the old man was, — said the countess, — even last year! I have never seen a handsomer man.</p>
					<p>— He has changed very much now, — said Anna Mikháylovna. — So I was going to say, — she continued, — by his wife the direct heir to all the estate is Prince Vasíli, but the father loved Pierre very much, occupied himself with his education, and wrote to the Emperor... so that no one knows, if he dies (he is so bad that this is expected any minute, and Lorrain has arrived from Petersburg), who will get this huge fortune, Pierre or Prince Vasíli. Forty thousand serfs and millions. I know this very well, because Prince Vasíli himself told me so. And besides, Kiríll Vladímirovich is my second cousin once removed on my mother's side. He also stood godfather to Bórya, — she added, as if attributing no importance to this circumstance.</p>
					<p>— Prince Vasíli arrived in Moscow yesterday. He is going on a tour of inspection, I was told, — said the visitor.</p>
					<p>— Yes, but, <foreign xml:lang="fr" n="between us">entre nous</foreign>, — said the princess, — that is a pretext; he came actually for Count Kiríll Vladímirovich, having learned that he is so bad.</p>
					<p>— Still, <foreign xml:lang="fr" n="my dear">ma chère</foreign>, it's a splendid trick, — said the count, and noticing that the elder visitor was not listening to him, he turned to the young ladies. — The police officer must have cut a fine figure, I imagine.</p>
					<p>And imagining how the police officer waved his arms, he again roared with a resonant, bass laugh that shook his whole stout body, as people laugh who have always eaten well and especially drunk well. — So please come to dinner with us, — he said.</p>
				</div>"""

es_text_7 = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo VII</head>
					<p>El príncipe Vasíli cumplió la promesa que le había hecho en la velada de Anna Pávlovna a la princesa Drubetskáya, que le había pedido por su único hijo, Borís. Se le habló de él al Emperador y, como excepción a la regla, fue trasladado al regimiento de la Guardia del Semënovsky como alférez. Pero Borís no fue nombrado ayudante de campo ni agregado a Kutúzov, a pesar de todos los esfuerzos e intrigas de Anna Mikháylovna. Poco después de la velada de Anna Pávlovna, Anna Mikháylovna regresó a Moscú, yendo directamente a casa de sus ricos parientes, los Rostóv, con los que se alojaba en Moscú y donde su adorado Borénka, que acababa de ser ascendido a alférez del ejército e inmediatamente transferido a la Guardia, había sido educado desde niño y había vivido durante años. La Guardia ya había salido de Petersburgo el 10 de agosto, y el hijo, que se había quedado en Moscú a por su equipo, debía alcanzarlos en el camino a Radzivílov.</p>
					<p>Era el santo de las dos Natályas, la madre y la hija menor de los Rostóv. De la mañana a la noche, no dejaron de llegar y marcharse carruajes con tiros de caballos, trayendo visitas para felicitar a la condesa a su casa grande y conocida de la calle Povarskáya. La condesa, con su hermosa hija mayor y las visitas, que no dejaban de sucederse, estaba sentada en el salón.</p>
					<p>La condesa era una mujer con un tipo oriental de rostro delgado, de unos cuarenta y cinco años, evidentemente agotada por los partos; había tenido doce hijos. La lentitud de sus movimientos y de su habla, procedente de la debilidad, le daba un aire digno que inspiraba respeto. La princesa Anna Mikháylovna Drubetskáya, como amiga íntima de la casa, también estaba allí sentada, ayudando a recibir a las visitas y a mantener la conversación. Los jóvenes estaban en las habitaciones del fondo, por no considerar necesario participar en la recepción de visitas. El conde salía al encuentro de los invitados y los despedía, invitando a todos a cenar.</p>
					<p>— Le estoy muy, muy agradecido, <foreign xml:lang="fr" n="querida">ma chère</foreign> o <foreign xml:lang="fr" n="querido">mon cher</foreign> — (decía <foreign xml:lang="fr" n="querida">ma chère</foreign> o <foreign xml:lang="fr" n="querido">mon cher</foreign> a todos sin excepción, sin el menor matiz de diferencia, tanto a los que estaban por encima de él como a los que estaban por debajo) — en mi nombre y en el de las queridas cumpleañeras. Mire usted, tiene que venir a cenar. Me ofenderá, <foreign xml:lang="fr" n="querido">mon cher</foreign>. Se lo ruego cordialmente en nombre de toda la familia, <foreign xml:lang="fr" n="querida">ma chère</foreign>. — Estas palabras, con la misma expresión en su rostro lleno, alegre y bien afeitado, y con el mismo firme apretón de manos y repetidas reverencias breves, las dirigía a todos sin excepción ni alteración. Tras despedir a un invitado, el conde volvía junto al que o los que aún estaban en el salón; acercando un sillón, con aire de hombre al que le gusta y sabe vivir, con las piernas muy separadas y las manos en las rodillas, se balanceaba significativamente, ofrecía conjeturas sobre el tiempo, daba consejos sobre la salud, a veces en ruso, a veces en un francés muy malo pero seguro de sí mismo, y de nuevo, con aire de hombre cansado pero firme en el cumplimiento de su deber, salía a despedir, se alisaba sus escasos cabellos grises sobre la calva y volvía a invitar a cenar. A veces, de vuelta de la antesala, pasaba por el invernadero y la despensa hasta el gran salón de mármol, donde se estaba poniendo la mesa para ochenta cubiertos, y, mirando a los lacayos, que traían plata y porcelana, colocaban las mesas y desdoblaban manteles de damasco, llamaba a Dmítry Vasílyevich, un noble que administraba todos sus asuntos, y le decía:</p>
					<p>— Bueno, bueno, Mítenka, vigila que todo esté bien. Así es, así es, — decía, mirando con placer la inmensa mesa extendida. — Lo principal es el servicio. Eso es... — Y se marchaba, suspirando complacido, de vuelta al salón.</p>
					<p>— ¡Márya Lvóvna Karágina y su hija! — anunció con voz de bajo el enorme lacayo de la condesa al entrar por la puerta del salón. La condesa reflexionó un momento y tomó un pellizco de una tabaquera de oro con el retrato de su marido.</p>
					<p>— Me atormentan estas visitas, — dijo. — Bueno, la recibiré y será la última. Es muy remilgada. Hágala pasar, — le dijo al lacayo con voz triste, como si dijera: "¡Bueno, acaben conmigo!"</p>
					<p>Una señora alta y corpulenta, de aire altivo, acompañada de su hija, de rostro redondo y sonriente, entró en el salón haciendo crujir sus vestidos.</p>
					<p>— <foreign xml:lang="fr" n="Querida condesa, ha pasado tanto tiempo... la pobre niña ha estado en cama... en el baile de los Razumóvsky... y la condesa Apráksina... yo estaba tan feliz...">Chère comtesse, il y a si longtemps... elle a été alitée la pauvre enfant... au bal des Razoumowsky... et la comtesse Apraksine... j'ai été si heureuse...</foreign> — se oían animadas voces de mujeres, interrumpiéndose unas a otras y confundiéndose con el crujido de los vestidos y el movimiento de las sillas. Comenzó esa conversación que se mantiene el tiempo justo para permitir, a la primera pausa, levantarse, hacer crujir los vestidos, decir: <foreign xml:lang="fr" n="Estoy encantada; la salud de mamá... y la condesa Apráksina">Je suis bien charmée; la santé de maman... et la comtesse Apraksine</foreign>, y de nuevo, haciendo crujir los vestidos, pasar a la antesala, ponerse un abrigo de piel o una capa, y marcharse. La conversación giró en torno a la principal noticia de la época en la ciudad: la enfermedad del famoso hombre rico y apuesto de la época de Catalina, el viejo conde Bezúkhov, y de su hijo ilegítimo, Pierre, que se había comportado de forma tan indecorosa en la velada de Anna Pávlovna Schérer.</p>
					<p>— Siento mucha pena por el pobre conde, — dijo la visita, — su salud ya es bastante mala de por sí, ¡y ahora este disgusto de su hijo le matará!</p>
					<p>— ¿Qué ha pasado? — preguntó la condesa, como si no supiera de qué hablaba la visitante, a pesar de que ya había oído la causa del disgusto del conde Bezúkhov quince veces.</p>
					<p>— ¡Eso es la educación moderna! Incluso en el extranjero, — dijo la visitante, — a este joven se le dejó a su aire, y ahora en Petersburgo, según dicen, ha hecho cosas tan terribles que ha sido expulsado de allí por la policía.</p>
					<p>— ¡No me diga! — exclamó la condesa.</p>
					<p>— Eligió mal a sus conocidos, — intervino la princesa Anna Mikháylovna. — El hijo del príncipe Vasíli, él y un tal Dólokhov, dicen, hicieron Dios sabe qué. Y los dos sufrieron las consecuencias. Dólokhov ha sido degradado, y el hijo de Bezúkhov ha sido enviado a Moscú. En cuanto a Anatole Kurágin, su padre se las arregló para silenciarlo de alguna manera. Pero, de todas formas, fue expulsado de Petersburgo.</p>
					<p>— Pero ¿qué hicieron exactamente? — preguntó la condesa.</p>
					<p>— Son unos perfectos bandidos, especialmente Dólokhov, — decía la visitante. — Es hijo de Márya Ivánovna Dólokhova, una señora tan respetable, ¿y qué se cree? ¿Se lo puede imaginar?: los tres consiguieron un oso en alguna parte, lo metieron con ellos en el carruaje y se lo llevaron a casa de las actrices. La policía acudió corriendo para calmarles. Atraparon al policía y lo ataron espalda con espalda al oso, y soltaron al oso en el Moýka; el oso nadaba, y el policía iba encima de él.</p>
					<p>— Menuda estampa, <foreign xml:lang="fr" n="querida">ma chère</foreign>, debió hacer el policía, — gritó el conde, muerto de risa.</p>
					<p>— ¡Oh, qué horror! ¿De qué se ríe, conde?</p>
					<p>Pero las damas no pudieron evitar reírse ellas mismas.</p>
					<p>— Apenas pudieron salvar al desgraciado, — prosiguió la visitante. — ¡Y así es como se divierte tan inteligentemente el hijo del conde Kiríll Vladímirovich Bezúkhov! — añadió. — Y decían que era tan educado e inteligente. A esto ha conducido toda esta educación extranjera. Espero que nadie le reciba aquí, a pesar de su riqueza. Quisieron presentármelo. Me negué en redondo: tengo hijas.</p>
					<p>— ¿Por qué dice que este joven es tan rico? — preguntó la condesa, apartándose de las niñas, que inmediatamente fingieron no estar escuchando. — Al fin y al cabo, sólo tiene hijos ilegítimos. Parece que... Pierre también es ilegítimo.</p>
					<p>La visitante hizo un gesto con la mano.</p>
					<p>— Tiene veinte ilegítimos, creo.</p>
					<p>La princesa Anna Mikháylovna intervino en la conversación, evidentemente deseosa de mostrar sus relaciones y su conocimiento de todas las circunstancias mundanas.</p>
					<p>— La cosa es así, — dijo de forma significativa y también a media voz. — La reputación del conde Kiríll Vladímirovich es conocida... Ha perdido la cuenta de sus propios hijos, pero este Pierre era su favorito.</p>
					<p>— ¡Qué apuesto era el anciano, — dijo la condesa, — incluso el año pasado! Nunca he visto un hombre más apuesto.</p>
					<p>— Ahora ha cambiado mucho, — dijo Anna Mikháylovna. — Y yo que le iba a decir, — continuó, — que por parte de su esposa el heredero directo de toda la hacienda es el príncipe Vasíli, pero el padre quería mucho a Pierre, se ocupó de su educación y escribió al Emperador... de modo que nadie sabe, si muere (está tan mal que se espera que lo haga de un momento a otro, y Lorrain ha llegado de Petersburgo), a quién le tocará esta inmensa fortuna, si a Pierre o al príncipe Vasíli. Cuarenta mil siervos y millones. Lo sé muy bien, porque el propio príncipe Vasíli me lo dijo. Y además, Kiríll Vladímirovich es mi tío segundo por parte de madre. También fue el padrino de Bórya, — añadió, como si no atribuyera importancia a esta circunstancia.</p>
					<p>— El príncipe Vasíli llegó ayer a Moscú. Va a hacer un viaje de inspección, según me han dicho, — dijo la visitante.</p>
					<p>— Sí, pero, <foreign xml:lang="fr" n="entre nosotros">entre nous</foreign>, — dijo la princesa, — eso es un pretexto; en realidad vino por el conde Kiríll Vladímirovich, al enterarse de que está tan mal.</p>
					<p>— Aún así, <foreign xml:lang="fr" n="querida">ma chère</foreign>, es una broma espléndida, — dijo el conde, y notando que la visitante mayor no le escuchaba, se dirigió a las jóvenes. — El policía debió de hacer una buena estampa, me imagino.</p>
					<p>E imaginando cómo el policía agitaba los brazos, volvió a soltar una sonora carcajada de bajo que sacudió todo su corpulento cuerpo, como ríen las personas que siempre han comido bien y, sobre todo, han bebido bien. — Así que vengan a cenar con nosotros, por favor, — dijo.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

ch7_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="7">'))
text = text[:ch7_start] + en_text_7 + '\n' + es_text_7 + '\n' + text[ch7_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
