import re

en_text_10 = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter XI</head>
					<p>The countess was so tired from the visits that she ordered no more to be received, and the porter was told only to be sure to invite to dinner all who should come with congratulations. The countess wanted to have a tête-à-tête talk with the friend of her childhood, Princess Anna Mikháylovna, whom she had not seen properly since her arrival from Petersburg. Anna Mikháylovna, with her tear-stained and pleasant face, moved closer to the countess's armchair.</p>
					<p>— I will be perfectly frank with you, — said Anna Mikháylovna. — There are few of us old friends left! That is why I value your friendship so much.</p>
					<p>Anna Mikháylovna looked at Véra and paused. The countess pressed her friend's hand.</p>
					<p>— Véra, — said the countess, turning to her eldest daughter, evidently the unloved one. — How is it you have no tact? Can't you see you are not wanted here? Go to your sisters, or...</p>
					<p>The handsome Véra smiled contemptuously, evidently not feeling the slightest offense.</p>
					<p>— If you had told me long ago, <foreign xml:lang="fr" n="mama">maman</foreign>, I should have gone immediately, — she said, and went to her room.</p>
					<p>But passing the sitting room, she noticed that two couples were sitting symmetrically at its two windows. She stopped and smiled contemptuously. Sónya was sitting close beside Nikoláy, who was copying out for her some verses he had composed for the first time. Borís and Natásha were sitting at the other window and fell silent when Véra entered. Sónya and Natásha looked at Véra with guilty and happy faces.</p>
					<p>It was merry and touching to look at these little girls in love, but their appearance evidently did not arouse a pleasant feeling in Véra.</p>
					<p>— How many times have I asked you, — she said, — not to take my things; you have your own room. She took the inkstand from Nikoláy.</p>
					<p>— In a minute, in a minute, — he said, dipping his pen.</p>
					<p>— You always manage to do things at the wrong time, — said Véra. — Like when you came running into the drawing room so that everyone felt ashamed of you.</p>
					<p>Despite the fact, or precisely because of the fact, that what she said was perfectly true, no one answered her, and all four only looked at one another. She lingered in the room with the inkstand in her hand.</p>
					<p>— And what secrets can there be at your age between Natásha and Borís and between you, — it's all just nonsense!</p>
					<p>— Well, what business is it of yours, Véra? — said Natásha in a soft, defensive voice.</p>
					<p>She evidently was even kinder and more affectionate to everyone that day than usual.</p>
					<p>— Very stupid, — said Véra, — I am ashamed of you. What sort of secrets?..</p>
					<p>— Everyone has their own secrets. We don't bother you and Berg, — said Natásha, growing heated.</p>
					<p>— I should think you don't bother us, — said Véra, — because there can never be anything bad in my actions. But I will tell <foreign xml:lang="fr" n="mama">maman</foreign> how you behave with Borís.</p>
					<p>— Natálya Ilyínichna behaves very well with me, — said Borís. — I cannot complain, — he said.</p>
					<p>— Leave off, Borís, you are such a diplomat (the word <emph>diplomat</emph> was much in use among the children in the special sense they attached to it); it is even tiresome, — said Natásha in an offended, trembling voice. — Why is she picking on me? You will never understand it, — she said, turning to Véra, — because you have never loved anyone; you have no heart, you are only <foreign xml:lang="fr" n="Madame de Genlis">madame de Genlis</foreign>! (this nickname, considered very insulting, had been given to Véra by Nikoláy), and your chief pleasure is to make trouble for others. You flirt with Berg as much as you please, — she muttered rapidly.</p>
					<p>— I certainly shall not run after a young man in front of visitors...</p>
					<p>— Well, you've achieved your object, — intervened Nikoláy, — you have said unpleasant things to everyone, upset everyone. Let's go to the nursery.</p>
					<p>All four, like a frightened flock of birds, got up and left the room.</p>
					<p>— Unpleasant things have been said to me, and I have said nothing to anyone, — said Véra.</p>
					<p>— <foreign xml:lang="fr" n="Madame de Genlis">Madame de Genlis</foreign>! <foreign xml:lang="fr" n="Madame de Genlis">Madame de Genlis</foreign>! — laughing voices cried from behind the door.</p>
					<p>The handsome Véra, who produced such an irritating, unpleasant effect on everyone, smiled and, evidently untouched by what had been said to her, went up to the mirror and adjusted her scarf and coiffure: looking at her handsome face, she seemed to become still colder and calmer. ————</p>
					<p>The conversation continued in the drawing room.</p>
					<p>— <foreign xml:lang="fr" n="Ah! dear">Ah! chère</foreign>, — the countess was saying, — in my life too <foreign xml:lang="fr" n="not everything is roses">tout n'est pas rose</foreign>. Do I not see that <foreign xml:lang="fr" n="at the rate we are going">du train, que nous allons</foreign>, our fortune will not last us long! And it is all the club, and his good nature. In the country we live, but do we rest? Theaters, hunting, and God knows what. But why speak of myself! Well, how did you manage all this? I often marvel at you, Annette, how at your age you rush about alone in a carriage to Moscow, to Petersburg, to all the ministers, to all the nobility, and know how to deal with everyone, I am amazed! Well, how was it arranged? Now I don't know how to do any of that.</p>
					<p>— Ah, my dear! — answered Princess Anna Mikháylovna. — God grant you never know how hard it is to be left a widow without support and with a son whom you love to adoration. One learns everything, — she continued with some pride. — My lawsuit taught me. If I need to see one of these bigwigs, I write a note: "<foreign xml:lang="fr" n="Princess So-and-So">princesse une telle</foreign> wishes to see So-and-So," and I go myself in a hired cab even two, three, four times, until I get what I need. I don't care what they may think of me.</p>
					<p>— Well, how did it go, who did you ask about Borénka? — asked the countess. — Yours is already an officer in the Guards, and Nikólushka is going as a cadet. There is no one to solicit for him. Who did you ask?</p>
					<p>— Prince Vasíli. He was very sweet. He immediately agreed to everything, reported it to the Emperor, — said Princess Anna Mikháylovna with enthusiasm, completely forgetting all the humiliation she had gone through to achieve her aim.</p>
					<p>— Has he aged, Prince Vasíli? — asked the countess. — I have not seen him since our theatricals at the Rumyántsevs'. And I suppose he has forgotten about me. <foreign xml:lang="fr" n="He used to pay court to me">Il me faisait la cour</foreign>, — recalled the countess with a smile.</p>
					<p>— Just the same, — answered Anna Mikháylovna, — amiable, effusive. <foreign xml:lang="fr" n="Honors have not turned his head at all">Les grandeurs ne lui ont pas tourné la tête du tout</foreign>. "I am sorry I can do so little for you, dear princess," he says to me, "command me." No, he is a splendid man and a fine relation. But you know, Nathalie, my love for my son. I don't know what I would not do for his happiness. But my circumstances are so bad, — continued Anna Mikháylovna sadly and lowering her voice, — so bad that I am now in a most terrible position. My unfortunate lawsuit eats up all I have, and makes no progress. You can imagine, I <foreign xml:lang="fr" n="literally">à la lettre</foreign> haven't a ten-kopeck piece, and I don't know how I am to equip Borís. — She took out her handkerchief and began to cry. — I need five hundred rubles, and I have only one twenty-five-ruble note. I am in such a position... My only hope now is Count Kiríll Vladímirovich Bezúkhov. If he does not want to support his godson — after all, he stood godfather to Bórya — and assign him something for his maintenance, then all my trouble is lost: I shall have nothing to equip him with. The countess shed a tear and pondered something in silence.</p>
					<p>— I often think, perhaps it is a sin, — said the princess, — but I often think: here is Count Kiríll Vladímirovich Bezúkhov living alone... that huge fortune... and what does he live for? Life is a burden to him, and Bórya is only just beginning to live.</p>
					<p>— He will surely leave something to Borís, — said the countess.</p>
					<p>— God knows, <foreign xml:lang="fr" n="dear friend!">chère amie!</foreign> These rich men and grandees are such egoists. But still I am going to him now with Borís and will tell him straight out what the matter is. Let them think what they will of me, I really don't care, when my son's fate depends on it. — The princess rose. — It is now two o'clock, and you dine at four. I shall have time to go there.</p>
					<p>And with the manners of a Petersburg lady of business who knows how to make use of her time, Anna Mikháylovna sent for her son and went out with him into the anteroom.</p>
					<p>— Goodbye, my dear, — she said to the countess, who accompanied her to the door, — wish me success, — she added in a whisper, turning from her son.</p>
					<p>— You are going to Count Kiríll Vladímirovich, <foreign xml:lang="fr" n="my dear">ma chère</foreign>? — said the count from the dining room, also coming out into the anteroom. — If he is better, invite Pierre to dine with me. After all, he used to come here, he danced with the children. Be sure to invite him, <foreign xml:lang="fr" n="my dear">ma chère</foreign>. Well, let's see how Tarás distinguishes himself today. He says Count Orlóv never had such a dinner as we are going to have.</p>
				</div>"""

es_text_10 = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo XI</head>
					<p>La condesa estaba tan cansada de las visitas que dio orden de no recibir a nadie más, y al portero se le dijo únicamente que invitara a cenar a todos los que vinieran a felicitarla. La condesa deseaba hablar a solas con su amiga de la infancia, la princesa Anna Mikháylovna, a la que no había visto bien desde su llegada de Petersburgo. Anna Mikháylovna, con su rostro agradable y manchado de lágrimas, se acercó al sillón de la condesa.</p>
					<p>— Seré completamente franca contigo, — dijo Anna Mikháylovna. — ¡Quedamos pocas amigas de las de antes! Por eso valoro tanto tu amistad.</p>
					<p>Anna Mikháylovna miró a Véra y se detuvo. La condesa estrechó la mano a su amiga.</p>
					<p>— Véra, — dijo la condesa, dirigiéndose a su hija mayor, que evidentemente no era su favorita. — ¿Cómo es que no tienes tacto? ¿No ves que aquí no haces falta? Vete con tus hermanas, o...</p>
					<p>La hermosa Véra sonrió desdeñosamente, evidentemente sin sentir la menor ofensa.</p>
					<p>— Si me lo hubiera dicho hace tiempo, <foreign xml:lang="fr" n="mamá">maman</foreign>, me habría ido inmediatamente, — dijo, y se fue a su habitación.</p>
					<p>Pero al pasar por la sala de estar, se dio cuenta de que dos parejas estaban sentadas simétricamente en sus dos ventanas. Se detuvo y sonrió despectivamente. Sónya estaba sentada muy cerca de Nikoláy, que le copiaba unos versos que él mismo había compuesto por primera vez. Borís y Natásha estaban sentados en la otra ventana y callaron cuando entró Véra. Sónya y Natásha miraron a Véra con rostros culpables y felices.</p>
					<p>Resultaba alegre y conmovedor mirar a aquellas chiquillas enamoradas, pero era evidente que su aspecto no despertaba un sentimiento agradable en Véra.</p>
					<p>— Cuántas veces os lo he pedido, — dijo, — que no cojáis mis cosas; vosotras tenéis vuestra propia habitación. Le quitó el tintero a Nikoláy.</p>
					<p>— Un momento, un momento, — dijo él, mojando la pluma.</p>
					<p>— Siempre os las arregláis para hacer las cosas a destiempo, — dijo Véra. — Como cuando entrasteis corriendo en el salón y todos se sintieron avergonzados de vosotros.</p>
					<p>A pesar de que, o precisamente porque, lo que decía era perfectamente cierto, nadie le contestó, y los cuatro se limitaron a mirarse. Ella se demoró en la habitación con el tintero en la mano.</p>
					<p>— Y qué secretos puede haber a vuestra edad entre Natásha y Borís y vosotras... ¡todo son tonterías!</p>
					<p>— ¿A ti qué te importa, Véra? — dijo Natásha con voz suave y a la defensiva.</p>
					<p>Evidentemente, aquel día se mostraba aún más amable y afectuosa con todo el mundo de lo habitual.</p>
					<p>— Muy estúpido, — dijo Véra, — me dais vergüenza. ¿Qué clase de secretos?..</p>
					<p>— Cada cual tiene sus propios secretos. Nosotros no os molestamos a Berg y a ti, — dijo Natásha, acalorándose.</p>
					<p>— Supongo que no nos molestáis, — dijo Véra, — porque nunca puede haber nada malo en mis actos. Pero le contaré a <foreign xml:lang="fr" n="mamá">maman</foreign> cómo te comportas con Borís.</p>
					<p>— Natálya Ilyínichna se porta muy bien conmigo, — dijo Borís. — No me puedo quejar, — dijo.</p>
					<p>— Déjalo, Borís, eres tan diplomático (la palabra <emph>diplomático</emph> se usaba mucho entre los niños en el sentido especial que le daban); hasta resulta cansino, — dijo Natásha con voz ofendida y temblorosa. — ¿Por qué se mete conmigo? Tú nunca lo entenderás, — dijo, dirigiéndose a Véra, — porque nunca has querido a nadie; no tienes corazón, ¡sólo eres una <foreign xml:lang="fr" n="Madame de Genlis">madame de Genlis</foreign>! (este apodo, considerado muy insultante, se lo había puesto Nikoláy a Véra), y tu mayor placer es crear problemas a los demás. Coquetea con Berg todo lo que quieras, — murmuró rápidamente.</p>
					<p>— Desde luego que no voy a correr detrás de un joven delante de las visitas...</p>
					<p>— Bueno, ya has conseguido tu objetivo, — intervino Nikoláy, — has dicho cosas desagradables a todo el mundo, has molestado a todos. Vámonos a la guardería.</p>
					<p>Los cuatro, como una bandada de pájaros asustados, se levantaron y salieron de la habitación.</p>
					<p>— Me han dicho cosas desagradables y yo no le he dicho nada a nadie, — dijo Véra.</p>
					<p>— ¡<foreign xml:lang="fr" n="Madame de Genlis">Madame de Genlis</foreign>! ¡<foreign xml:lang="fr" n="Madame de Genlis">Madame de Genlis</foreign>! — gritaron voces risueñas desde detrás de la puerta.</p>
					<p>La hermosa Véra, que producía en todos un efecto tan irritante y desagradable, sonrió y, evidentemente sin inmutarse por lo que le habían dicho, se acercó al espejo y se ajustó el pañuelo y el peinado: mirándose su hermoso rostro, parecía volverse aún más fría y serena. ————</p>
					<p>La conversación continuaba en el salón.</p>
					<p>— ¡<foreign xml:lang="fr" n="Ah, querida">Ah! chère</foreign>, — decía la condesa, — tampoco en mi vida <foreign xml:lang="fr" n="todo son rosas">tout n'est pas rose</foreign>. ¡No veo acaso que <foreign xml:lang="fr" n="al ritmo que vamos">du train, que nous allons</foreign>, nuestra fortuna no nos durará mucho! Y todo es culpa del club y de su buen corazón. Vivimos en el campo, pero ¿acaso descansamos? Teatros, caza y Dios sabe qué. ¡Pero por qué hablar de mí! Bueno, ¿cómo te las has arreglado tú con todo esto? A menudo me maravillo de ti, Annette, ¡cómo a tu edad vas corriendo sola en carruaje a Moscú, a Petersburgo, a ver a todos los ministros, a toda la nobleza, y sabes cómo tratar a todo el mundo, me asombras! Bueno, ¿cómo te las has arreglado? Yo ahora no sabría hacer nada de eso.</p>
					<p>— ¡Ah, amiga mía! — respondió la princesa Anna Mikháylovna. — Dios quiera que nunca sepas lo duro que es quedarse viuda sin apoyo y con un hijo al que amas hasta la adoración. Una lo aprende todo, — continuó con cierto orgullo. — Mi pleito me lo enseñó. Si necesito ver a uno de esos prebostes, escribo una nota: "<foreign xml:lang="fr" n="La princesa tal y cual">princesse une telle</foreign> desea ver a fulanito", y voy yo misma en un coche de alquiler hasta dos, tres, cuatro veces, hasta conseguir lo que necesito. Me da igual lo que piensen de mí.</p>
					<p>— Bueno, ¿cómo te ha ido?, ¿a quién le has preguntado por Borénka? — preguntó la condesa. — El tuyo ya es oficial de la Guardia y Nikólushka va de cadete. No hay quien interceda por él. ¿A quién se lo has pedido?</p>
					<p>— Al príncipe Vasíli. Ha sido muy amable. Accedió a todo inmediatamente, se lo comunicó al Emperador, — dijo la princesa Anna Mikháylovna con entusiasmo, olvidando por completo toda la humillación por la que había pasado para conseguir su objetivo.</p>
					<p>— ¿Ha envejecido el príncipe Vasíli? — preguntó la condesa. — No le veo desde nuestras representaciones teatrales en casa de los Rumyántsev. Y supongo que se habrá olvidado de mí. <foreign xml:lang="fr" n="Me cortejaba">Il me faisait la cour</foreign>, — recordó la condesa con una sonrisa.</p>
					<p>— Sigue igual, — respondió Anna Mikháylovna, — amable, efusivo. <foreign xml:lang="fr" n="Los honores no se le han subido a la cabeza en absoluto">Les grandeurs ne lui ont pas tourné la tête du tout</foreign>. "Siento poder hacer tan poco por usted, querida princesa", me dice, "mándeme usted". No, es un hombre espléndido y un buen pariente. Pero tú sabes, Nathalie, el amor que siento por mi hijo. No sé qué no haría yo por su felicidad. Pero mi situación es tan mala, — continuó Anna Mikháylovna con tristeza y bajando la voz, — tan mala que me encuentro ahora en una posición de lo más terrible. Mi desgraciado pleito se come todo lo que tengo, y no avanza. Te puedes imaginar, no tengo <foreign xml:lang="fr" n="literalmente">à la lettre</foreign> ni una moneda de diez kopeks, y no sé cómo voy a equipar a Borís. — Sacó el pañuelo y rompió a llorar. — Necesito quinientos rublos, y sólo tengo un billete de veinticinco rublos. Estoy en un aprieto... Mi única esperanza ahora es el conde Kiríll Vladímirovich Bezúkhov. Si no quiere mantener a su ahijado — después de todo, él apadrinó a Bórya — y asignarle algo para su manutención, entonces todas mis molestias se habrán perdido: no tendré con qué equiparle. La condesa derramó una lágrima y reflexionó sobre algo en silencio.</p>
					<p>— A menudo pienso, quizá sea un pecado, — dijo la princesa, — pero a menudo pienso: he aquí al conde Kiríll Vladímirovich Bezúkhov viviendo solo... esa inmensa fortuna... ¿y para qué vive? La vida es una carga para él, y Bórya no ha hecho más que empezar a vivir.</p>
					<p>— Seguro que le dejará algo a Borís, — dijo la condesa.</p>
					<p>— ¡Dios lo sabe, <foreign xml:lang="fr" n="querida amiga">chère amie!</foreign> Estos ricachones y grandes señores son unos egoístas. Pero aún así voy a ir a verle ahora con Borís y le contaré directamente de qué se trata. Que piensen lo que quieran de mí, la verdad es que me da igual, cuando el destino de mi hijo depende de ello. — La princesa se levantó. — Son las dos de la tarde, y cenáis a las cuatro. Tendré tiempo de ir.</p>
					<p>Y con los modales de una dama de negocios de Petersburgo que sabe aprovechar el tiempo, Anna Mikháylovna mandó llamar a su hijo y salió con él a la antesala.</p>
					<p>— Adiós, querida, — dijo a la condesa, que la acompañaba hasta la puerta, — deséame suerte, — añadió en un susurro, apartándose de su hijo.</p>
					<p>— ¿Vas a ver al conde Kiríll Vladímirovich, <foreign xml:lang="fr" n="querida">ma chère</foreign>? — dijo el conde desde el comedor, saliendo también a la antesala. — Si se encuentra mejor, invita a Pierre a cenar conmigo. Al fin y al cabo, solía venir por aquí, bailaba con los niños. No dejes de invitarle, <foreign xml:lang="fr" n="querida">ma chère</foreign>. Bueno, a ver cómo se distingue hoy Tarás. Dice que el conde Orlóv no ha tenido nunca una cena como la que vamos a tener nosotros.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

ch10_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="10">'))
text = text[:ch10_start] + en_text_10 + '\n' + es_text_10 + '\n' + text[ch10_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
