import re

en_text_3 = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter III</head>
					<p>Anna Pávlovna's evening party was launched. The spindles hummed evenly and ceaselessly from all sides. Except for <foreign xml:lang="fr" n="my aunt">ma tante</foreign>, beside whom sat only one elderly lady with a tear-stained, thin face, somewhat of a stranger in this brilliant society, the company had broken up into three circles. In one, the more masculine, the center was the Abbé; in the second, the young circle, the beautiful Princess Hélène, Prince Vasíli's daughter, and the pretty, rosy, rather too plump for her age, little Princess Bolkónskaya. In the third were Mortemart and Anna Pávlovna.</p>
					<p>The vicomte was a pleasant-looking young man, with soft features and manners, who evidently considered himself a celebrity, but out of good breeding modestly allowed the society in which he found himself to make use of him. Anna Pávlovna was evidently treating her guests to him. As a good maître d'hôtel serves up as something supernaturally exquisite a piece of beef that one would not want to eat if one saw it in a dirty kitchen, so that evening Anna Pávlovna served up to her guests first the vicomte and then the Abbé as something supernaturally refined. In Mortemart's circle they immediately began talking about the murder of the Duc d'Enghien. The vicomte said that the Duc d'Enghien had perished through his own magnanimity, and that there were particular reasons for Bonaparte's animosity.</p>
					<p>— <foreign xml:lang="fr" n="Ah! let us see. Tell us about it, vicomte">Ah! voyons. Contez-nous cela, vicomte</foreign>, — said Anna Pávlovna, feeling with joy how this phrase smacked of something <foreign xml:lang="fr" n="reminiscent of Louis XV">à la Louis XV</foreign>, — <foreign xml:lang="fr" n="tell us about it, vicomte">contez-nous cela, vicomte</foreign>.</p>
					<p>The vicomte bowed in token of submission and smiled courteously. Anna Pávlovna made a circle around the vicomte and invited everyone to hear his tale.</p>
					<p>— <foreign xml:lang="fr" n="The vicomte was personally acquainted with Monseigneur">Le vicomte a été personnellement connu de monseigneur</foreign>, — Anna Pávlovna whispered to one. — <foreign xml:lang="fr" n="The vicomte is a perfect storyteller">Le vicomte est un parfait conteur</foreign>, — she said to another. — <foreign xml:lang="fr" n="How one can see the man of good society">Сomme on voit l'homme de la bonne compagnie</foreign>, — she said to a third; and the vicomte was presented to the company in the most elegant and favorable light for him, like a roast beef on a hot dish, sprinkled with greens.</p>
					<p>The vicomte was about to begin his story and smiled subtly.</p>
					<p>— Come over here, <foreign xml:lang="fr" n="dear Hélène">chère Hélène</foreign>, — Anna Pávlovna said to the beautiful princess, who was sitting some distance away, forming the center of another circle.</p>
					<p>Princess Hélène smiled; she stood up with the same unchanging smile of a perfectly beautiful woman with which she had entered the drawing room. Rustling slightly in her white ball gown, trimmed with ivy and moss, and gleaming with the whiteness of her shoulders, the gloss of her hair, and her diamonds, she passed between the men who stepped aside for her, and went straight to Anna Pávlovna, looking at no one but smiling at everyone and as if graciously granting each the right to admire the beauty of her figure, her plump shoulders, her very exposed breast and back, according to the fashion of the time, and as if bringing with her the brilliance of a ball. Hélène was so beautiful that not only was there not a shadow of coquetry to be seen in her, but on the contrary, she seemed almost ashamed of her unquestionable and too strongly and victoriously acting beauty. She seemed to wish and yet be unable to diminish the effect of her beauty.</p>
					<p>— <foreign xml:lang="fr" n="What a beautiful person!">Quelle belle personne!</foreign> said everyone who saw her. As if struck by something extraordinary, the vicomte shrugged his shoulders and lowered his eyes as she seated herself before him and illuminated him too with the same unchanging smile.</p>
					<p>— <foreign xml:lang="fr" n="Madame, I fear for my abilities before such an audience">Madame, je crains pour mes moyens devant un pareil auditoire</foreign>, — he said, bowing his head with a smile.</p>
					<p>The princess rested her bare plump arm on the little table and did not find it necessary to say anything. She waited, smiling. Throughout the story she sat upright, glancing occasionally now at her plump, beautiful arm, which rested lightly on the table, now at her still more beautiful breast, on which she adjusted her diamond necklace; she adjusted the folds of her dress several times and, when the story made an impression, looked round at Anna Pávlovna and immediately assumed the very expression that was on the maid of honor's face, and then relapsed again into her radiant smile. Following Hélène, the little princess also moved over from the tea table.</p>
					<p>— <foreign xml:lang="fr" n="Wait for me, I am going to get my work">Attendez moi, je vais prendre mon ouvrage</foreign>, — she said. — <foreign xml:lang="fr" n="Come now, what are you thinking of?">Voyons, à quoi pensez-vous?</foreign> — she addressed Prince Hippolyte: — <foreign xml:lang="fr" n="bring me my reticule">apportez-moi mon ridicule</foreign>.</p>
					<p>The princess, smiling and talking to everyone, suddenly made a rearrangement, and settling down, cheerfully smoothed her dress.</p>
					<p>— Now I am comfortable, — she kept saying, and, asking them to begin, took up her work.</p>
					<p>Prince Hippolyte brought her the reticule, followed her, and, drawing a chair close to her, sat down beside her.</p>
					<p><foreign xml:lang="fr" n="The charming Hippolyte">Le charmant Hippolyte</foreign> was striking for his extraordinary resemblance to his beautiful sister and still more for the fact that, despite the resemblance, he was strikingly ugly. His features were the same as his sister's, but in her everything was illuminated by a joyous, self-satisfied, youthful, unchanging smile and the extraordinary, antique beauty of her body; in her brother, on the contrary, the same face was clouded by idiocy and invariably expressed a self-confident peevishness, and his body was thin and weak. His eyes, nose, mouth — everything seemed compressed into one indefinite and bored grimace, and his arms and legs always assumed an unnatural posture.</p>
					<p>— <foreign xml:lang="fr" n="It is not a ghost story?">Ce n'est pas une histoire de revenants?</foreign> — he said, sitting down beside the princess and hastily fixing his lorgnette to his eyes, as if without this instrument he could not begin to speak.</p>
					<p>— <foreign xml:lang="fr" n="Why no, my dear">Mais non, mon cher</foreign>, — said the surprised storyteller, shrugging his shoulders.</p>
					<p>— <foreign xml:lang="fr" n="It's just that I detest ghost stories">C'est que je déteste les histoires de revenants</foreign>, — Prince Hippolyte said in a tone which showed that he had spoken the words before he understood what they meant.</p>
					<p>Because of the self-confidence with which he spoke, no one could tell whether what he said was very clever or very stupid. He wore a dark green dress coat, breeches of the color of a <foreign xml:lang="fr" n="frightened nymph's thigh">cuisse de nymphe effrayée</foreign>, as he himself called it, stockings, and shoes.</p>
					<p><foreign xml:lang="fr" n="The vicomte">Vicomte</foreign> told very nicely the anecdote then current, that the Duc d'Enghien had gone secretly to Paris to see <foreign xml:lang="fr" n="Mademoiselle George">m-llе George</foreign>, and that there he met Bonaparte, who also enjoyed the favors of the famous actress, and that there, meeting the duke, Napoleon accidentally fell into that swoon to which he was subject, and was at the mercy of the duke, a mercy the duke did not use, but that Bonaparte subsequently avenged this very magnanimity with the duke's death.</p>
					<p>The story was very nice and interesting, especially at the point where the rivals suddenly recognize each other, and the ladies seemed to be agitated.</p>
					<p>— <foreign xml:lang="fr" n="Charming">Charmant</foreign>, — said Anna Pávlovna, looking inquiringly at the little princess.</p>
					<p>— <foreign xml:lang="fr" n="Charming">Charmant</foreign>, — whispered the little princess, sticking her needle into her work, as if to signify that the interest and charm of the story prevented her from continuing her work.</p>
					<p>The vicomte appreciated this silent praise and, smiling gratefully, prepared to continue; but at this time Anna Pávlovna, who had kept her eye on the young man who terrified her, noticed that he was talking rather too hotly and loudly with the Abbé, and hurried to the rescue of the dangerous spot. Indeed, Pierre had managed to engage the Abbé in a conversation about the political balance, and the Abbé, evidently interested by the young man's simple-hearted fervor, was developing his favorite idea before him. Both were listening and speaking rather too animatedly and naturally, and this was exactly what Anna Pávlovna did not like.</p>
					<p>— The means are the European balance and the <foreign xml:lang="fr" n="law of nations">droit des gens</foreign>, — the Abbé was saying. — It is only necessary for one powerful state like Russia, renowned for its barbarism, to place itself disinterestedly at the head of an alliance aiming at the balance of Europe — and it will save the world!</p>
					<p>— But how will you find such a balance? — Pierre was beginning; but at that moment Anna Pávlovna came up and, glancing sternly at Pierre, asked the Italian how he was bearing the climate here. The Italian's face suddenly changed and assumed an offensively affected, sugary expression, which was evidently customary for him in conversation with women.</p>
					<p>— I am so charmed by the graces of mind and education of the society, especially the feminine society, into which I have had the happiness to be received, that I have not yet had time to think of the climate, — he said.</p>
					<p>Not letting the Abbé and Pierre go, Anna Pávlovna, for the convenience of observation, joined them to the general circle.</p>
					<p>At this moment a new personage entered the drawing room. This new personage was the young Prince Andréi Bolkónsky, the husband of the little princess. Prince Bolkónsky was a very handsome young man of medium height, with clear and dry features. Everything in his figure, from his tired, bored look to his quiet measured step, presented the sharpest contrast to his little, lively wife. Evidently all the people in the drawing room were not only known to him, but had bored him so much that it was very tedious for him to look at them and listen to them. And of all the faces that bored him, the face of his pretty wife seemed to bore him most of all. With a grimace that spoiled his handsome face, he turned away from her. He kissed Anna Pávlovna's hand and, screwing up his eyes, scanned the whole company.</p>
					<p>— <foreign xml:lang="fr" n="You are enlisting for the war, Prince?">Vous vous enrôlez pour la guerre, mon prince?</foreign> — said Anna Pávlovna.</p>
					<p>— <foreign xml:lang="fr" n="General Kutúzov">Le général Koutouzoff</foreign>, — said Bolkónsky, stressing the last syllable <emph>zoff</emph> like a Frenchman, — <foreign xml:lang="fr" n="has been kind enough to want me as his aide-de-camp...">a bien voulu de moi pour aide-de-camp...</foreign></p>
					<p>— <foreign xml:lang="fr" n="And Lise, your wife?">Et Lise, votre femme?</foreign></p>
					<p>— She will go to the country.</p>
					<p>— Aren't you ashamed to deprive us of your charming wife?</p>
					<p>— <foreign xml:lang="fr" n="Andréi">André</foreign>, — said his wife, addressing her husband in the same coquettish tone she used with outsiders, — what a story the vicomte has just told us about Mademoiselle George and Bonaparte!</p>
					<p>Prince Andréi screwed up his eyes and turned away. Pierre, who had not taken his joyful, friendly eyes off Prince Andréi since he entered the drawing room, went up to him and took his arm. Prince Andréi, without looking round, wrinkled his face into a grimace expressing annoyance with whoever was touching his arm, but, seeing Pierre's smiling face, he smiled an unexpectedly kind and pleasant smile.</p>
					<p>— There now!.. And you too in grand society! — he said to Pierre.</p>
					<p>— I knew you would be here, — answered Pierre. — I will come to supper with you, — he added quietly, so as not to disturb the vicomte, who was continuing his story. — May I?</p>
					<p>— No, you may not, — said Prince Andréi, laughing and by a pressure of the hand letting Pierre know that there was no need to ask. He wanted to say something else, but at that moment Prince Vasíli rose with his daughter, and the men stood up to let them pass.</p>
					<p>— You must excuse me, my dear vicomte, — said Prince Vasíli to the Frenchman, affectionately pulling him down by the sleeve to his chair so that he should not rise. — This unfortunate fête at the ambassador's deprives me of a pleasure and interrupts you. I am very sorry to leave your delightful evening, — he said to Anna Pávlovna.</p>
					<p>His daughter, Princess Hélène, lightly holding the folds of her dress, passed between the chairs, and the smile shone still more brightly on her beautiful face. Pierre looked with almost frightened, rapturous eyes at this beauty as she passed him.</p>
					<p>— Very lovely, — said Prince Andréi.</p>
					<p>— Very, — said Pierre.</p>
					<p>As he passed, Prince Vasíli seized Pierre by the arm and turned to Anna Pávlovna.</p>
					<p>— Educate this bear for me, — he said. — He has been living with me for a month now, and this is the first time I have seen him in society. Nothing is so necessary to a young man as the society of clever women.</p>
				</div>"""

es_text_3 = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo III</head>
					<p>La velada de Anna Pávlovna estaba en marcha. Los husos zumbaban de manera uniforme e incesante por todos lados. A excepción de <foreign xml:lang="fr" n="mi tía">ma tante</foreign>, junto a la cual sólo estaba sentada una señora mayor de rostro enjuto y bañado en lágrimas, un tanto extraña en aquella brillante sociedad, la concurrencia se había dividido en tres círculos. En uno, el más masculino, el centro era el abate; en el segundo, el círculo joven, la bella princesa Hélène, hija del príncipe Vasíli, y la linda, sonrosada y demasiado regordeta para su edad, princesita Bolkónskaya. En el tercero estaban Mortemart y Anna Pávlovna.</p>
					<p>El vizconde era un joven de aspecto agradable, de facciones y modales suaves, que evidentemente se consideraba una celebridad, pero que por buena educación permitía modestamente que la sociedad en la que se encontraba hiciera uso de él. Evidentemente, Anna Pávlovna agasajaba a sus invitados con él. Del mismo modo que un buen maître sirve como algo sobrenaturalmente exquisito un trozo de carne que uno no querría comer si lo viera en una cocina sucia, así aquella noche Anna Pávlovna sirvió a sus invitados primero al vizconde y luego al abate como algo sobrenaturalmente refinado. En el círculo de Mortemart empezaron a hablar inmediatamente del asesinato del duque de Enghien. El vizconde dijo que el duque de Enghien había perecido por su propia magnanimidad, y que había razones particulares para la animosidad de Bonaparte.</p>
					<p>— <foreign xml:lang="fr" n="¡Ah! a ver. Cuéntenoslo, vizconde">Ah! voyons. Contez-nous cela, vicomte</foreign>, — dijo Anna Pávlovna, sintiendo con alegría cómo esta frase tenía un cierto sabor <foreign xml:lang="fr" n="que recordaba a Luis XV">à la Louis XV</foreign>, — <foreign xml:lang="fr" n="cuéntenoslo, vizconde">contez-nous cela, vicomte</foreign>.</p>
					<p>El vizconde se inclinó en señal de sumisión y sonrió cortésmente. Anna Pávlovna formó un círculo alrededor del vizconde e invitó a todos a escuchar su relato.</p>
					<p>— <foreign xml:lang="fr" n="El vizconde conoció personalmente a monseñor">Le vicomte a été personnellement connu de monseigneur</foreign>, — susurró Anna Pávlovna a uno. — <foreign xml:lang="fr" n="El vizconde es un narrador perfecto">Le vicomte est un parfait conteur</foreign>, — dijo a otro. — <foreign xml:lang="fr" n="Cómo se nota al hombre de buena sociedad">Сomme on voit l'homme de la bonne compagnie</foreign>, — dijo a un tercero; y el vizconde fue presentado a la concurrencia bajo la luz más elegante y favorable para él, como un rosbif en una fuente caliente, espolvoreado con verduras.</p>
					<p>El vizconde se disponía a comenzar su relato y sonrió sutilmente.</p>
					<p>— Venga aquí, <foreign xml:lang="fr" n="querida Hélène">chère Hélène</foreign>, — dijo Anna Pávlovna a la bella princesa, que estaba sentada a cierta distancia, formando el centro de otro círculo.</p>
					<p>La princesa Hélène sonrió; se levantó con la misma sonrisa inalterable de una mujer perfectamente hermosa con la que había entrado en el salón. Haciendo crujir ligeramente su vestido de baile blanco, adornado con hiedra y musgo, y brillando con la blancura de sus hombros, el brillo de sus cabellos y de sus diamantes, pasó entre los hombres que se apartaban para dejarla pasar, y fue directamente hacia Anna Pávlovna, sin mirar a nadie pero sonriendo a todos y como concediendo graciosamente a cada uno el derecho a admirar la belleza de su figura, de sus hombros regordetes, de su pecho y espalda muy descubiertos, según la moda de la época, y como trayendo consigo el brillo de un baile. Hélène era tan hermosa que no sólo no se veía en ella ni asomo de coquetería, sino que, por el contrario, parecía casi avergonzada de su indiscutible y demasiado fuerte y victoriosa belleza. Parecía desear y, sin embargo, ser incapaz de disminuir el efecto de su belleza.</p>
					<p>— <foreign xml:lang="fr" n="¡Qué persona tan hermosa!">Quelle belle personne!</foreign> decían todos los que la veían. Como impresionado por algo extraordinario, el vizconde se encogió de hombros y bajó los ojos mientras ella se sentaba ante él y le iluminaba también con la misma sonrisa inalterable.</p>
					<p>— <foreign xml:lang="fr" n="Señora, temo por mis aptitudes ante semejante auditorio">Madame, je crains pour mes moyens devant un pareil auditoire</foreign>, — dijo, inclinando la cabeza con una sonrisa.</p>
					<p>La princesa apoyó su brazo regordete y desnudo en la mesita y no consideró necesario decir nada. Esperó, sonriendo. Durante todo el relato permaneció sentada muy derecha, mirando de vez en cuando ya a su brazo regordete y hermoso, que descansaba ligeramente sobre la mesa, ya a su pecho aún más hermoso, sobre el que se ajustaba el collar de diamantes; se ajustó varias veces los pliegues del vestido y, cuando el relato le causaba impresión, miraba a Anna Pávlovna e inmediatamente adoptaba la misma expresión que había en el rostro de la dama de honor, y luego volvía a relajarse en su radiante sonrisa. Siguiendo a Hélène, la princesita también se acercó desde la mesa del té.</p>
					<p>— <foreign xml:lang="fr" n="Espérenme, voy a buscar mi labor">Attendez moi, je vais prendre mon ouvrage</foreign>, — dijo. — <foreign xml:lang="fr" n="Vamos, ¿en qué está pensando?">Voyons, à quoi pensez-vous?</foreign> — se dirigió al príncipe Hippolyte: — <foreign xml:lang="fr" n="tráigame mi retículo">apportez-moi mon ridicule</foreign>.</p>
					<p>La princesa, sonriendo y hablando con todos, hizo de pronto un reajuste y, al instalarse, se alisó alegremente el vestido.</p>
					<p>— Ahora estoy cómoda, — no dejaba de decir y, pidiendo que empezaran, retomó su labor.</p>
					<p>El príncipe Hippolyte le llevó el retículo, la siguió y, acercando una silla a la de ella, se sentó a su lado.</p>
					<p><foreign xml:lang="fr" n="El encantador Hippolyte">Le charmant Hippolyte</foreign> llamaba la atención por su extraordinario parecido con su bella hermana y más aún por el hecho de que, a pesar del parecido, era sorprendentemente feo. Sus facciones eran las mismas que las de su hermana, pero en ella todo estaba iluminado por una sonrisa alegre, satisfecha de sí misma, juvenil, inalterable y por la extraordinaria belleza antigua de su cuerpo; en su hermano, por el contrario, el mismo rostro estaba nublado por la idiotez e invariablemente expresaba una displicencia segura de sí misma, y su cuerpo era delgado y débil. Sus ojos, nariz, boca, todo parecía comprimido en una mueca indefinida y aburrida, y sus brazos y piernas adoptaban siempre una postura poco natural.</p>
					<p>— <foreign xml:lang="fr" n="¿No es una historia de fantasmas?">Ce n'est pas une histoire de revenants?</foreign> — dijo él, sentándose al lado de la princesa y llevándose apresuradamente los impertinentes a los ojos, como si sin este instrumento no pudiera empezar a hablar.</p>
					<p>— <foreign xml:lang="fr" n="Pues no, amigo mío">Mais non, mon cher</foreign>, — dijo el sorprendido narrador, encogiéndose de hombros.</p>
					<p>— <foreign xml:lang="fr" n="Es que detesto las historias de fantasmas">C'est que je déteste les histoires de revenants</foreign>, — dijo el príncipe Hippolyte en un tono que demostraba que había pronunciado las palabras antes de comprender lo que significaban.</p>
					<p>Debido a la seguridad con que hablaba, nadie podía saber si lo que decía era muy inteligente o muy estúpido. Llevaba un frac verde oscuro, calzones color <foreign xml:lang="fr" n="muslo de ninfa asustada">cuisse de nymphe effrayée</foreign>, como él mismo lo llamaba, medias y zapatos.</p>
					<p><foreign xml:lang="fr" n="El vizconde">Vicomte</foreign> contó muy bien la anécdota corriente entonces de que el duque de Enghien había ido en secreto a París para ver a <foreign xml:lang="fr" n="Mademoiselle George">m-llе George</foreign>, y que allí se encontró con Bonaparte, que también gozaba de los favores de la famosa actriz, y que allí, al encontrarse con el duque, Napoleón cayó accidentalmente en ese desmayo al que era propenso, y quedó a merced del duque, merced que el duque no utilizó, pero que Bonaparte posteriormente vengó esta misma magnanimidad con la muerte del duque.</p>
					<p>La historia era muy bonita e interesante, especialmente en el punto en que los rivales se reconocen de repente, y las damas parecían agitadas.</p>
					<p>— <foreign xml:lang="fr" n="Encantador">Charmant</foreign>, — dijo Anna Pávlovna, mirando inquisitivamente a la princesita.</p>
					<p>— <foreign xml:lang="fr" n="Encantador">Charmant</foreign>, — susurró la princesita, clavando la aguja en su labor, como para indicar que el interés y el encanto de la historia le impedían continuar con ella.</p>
					<p>El vizconde apreció esta silenciosa alabanza y, sonriendo con gratitud, se dispuso a continuar; pero en ese momento Anna Pávlovna, que no había quitado el ojo de encima al joven que la aterrorizaba, notó que hablaba demasiado acalorada y fuertemente con el abate, y se apresuró a acudir al rescate del lugar peligroso. En efecto, Pierre se las había arreglado para enzarzar al abate en una conversación sobre el equilibrio político, y el abate, evidentemente interesado por el fervor ingenuo del joven, desarrollaba ante él su idea favorita. Ambos escuchaban y hablaban de un modo demasiado animado y natural, y esto era exactamente lo que a Anna Pávlovna no le gustaba.</p>
					<p>— Los medios son el equilibrio europeo y el <foreign xml:lang="fr" n="derecho de gentes">droit des gens</foreign>, — decía el abate. — ¡Sólo es necesario que un Estado poderoso como Rusia, famoso por su barbarie, se ponga desinteresadamente a la cabeza de una alianza que tenga por objeto el equilibrio de Europa, y salvará al mundo!</p>
					<p>— Pero, ¿cómo encontrará usted ese equilibrio? — empezaba a decir Pierre; pero en aquel momento se acercó Anna Pávlovna y, lanzando una severa mirada a Pierre, preguntó al italiano cómo soportaba el clima de allí. El rostro del italiano cambió repentinamente y adoptó una expresión ofensivamente afectada, azucarada, que era evidentemente habitual en él en la conversación con mujeres.</p>
					<p>— Estoy tan encantado por las gracias de la mente y la educación de la sociedad, especialmente de la sociedad femenina, en la que he tenido la felicidad de ser recibido, que aún no he tenido tiempo de pensar en el clima, — dijo.</p>
					<p>Sin dejar ir al abate ni a Pierre, Anna Pávlovna, por comodidad de observación, los unió al círculo general.</p>
					<p>En este momento entró un nuevo personaje en el salón. Este nuevo personaje era el joven príncipe Andréi Bolkónsky, el marido de la princesita. El príncipe Bolkónsky era un joven muy apuesto, de mediana estatura, con rasgos claros y secos. Todo en su figura, desde su mirada cansada y aburrida hasta su paso lento y mesurado, presentaba el contraste más agudo con su mujercita vivaz. Evidentemente, todos los del salón no sólo le eran conocidos, sino que le aburrían tanto que le resultaba muy tedioso mirarlos y escucharlos. Y de todas las caras que le aburrían, la cara de su bonita esposa parecía aburrirle más que ninguna. Con una mueca que estropeaba su apuesto rostro, se apartó de ella. Besó la mano de Anna Pávlovna y, entrecerrando los ojos, observó a toda la concurrencia.</p>
					<p>— <foreign xml:lang="fr" n="¿Se alista usted para la guerra, príncipe?">Vous vous enrôlez pour la guerre, mon prince?</foreign> — dijo Anna Pávlovna.</p>
					<p>— <foreign xml:lang="fr" n="El general Kutúzov">Le général Koutouzoff</foreign>, — dijo Bolkónsky, acentuando la última sílaba <emph>zoff</emph> como un francés, — <foreign xml:lang="fr" n="ha tenido la amabilidad de quererme como su ayudante de campo...">a bien voulu de moi pour aide-de-camp...</foreign></p>
					<p>— <foreign xml:lang="fr" n="¿Y Lise, su esposa?">Et Lise, votre femme?</foreign></p>
					<p>— Ella irá al campo.</p>
					<p>— ¿No le da vergüenza privarnos de su encantadora esposa?</p>
					<p>— <foreign xml:lang="fr" n="Andréi">André</foreign>, — dijo su esposa, dirigiéndose a su marido en el mismo tono coqueto que usaba con los extraños, — ¡qué historia nos acaba de contar el vizconde sobre Mademoiselle George y Bonaparte!</p>
					<p>El príncipe Andréi entrecerró los ojos y se dio la vuelta. Pierre, que no había apartado sus ojos alegres y amistosos del príncipe Andréi desde que entró en el salón, se acercó a él y le tomó del brazo. El príncipe Andréi, sin mirar atrás, arrugó la cara en una mueca que expresaba molestia hacia quienquiera que le estuviera tocando el brazo, pero al ver la cara sonriente de Pierre, sonrió con una sonrisa inesperadamente amable y agradable.</p>
					<p>— ¡Vaya, vaya!.. ¡Y usted también en la gran sociedad! — dijo a Pierre.</p>
					<p>— Sabía que estaría aquí, — contestó Pierre. — Iré a cenar con usted, — añadió en voz baja, para no molestar al vizconde, que continuaba su historia. — ¿Puedo?</p>
					<p>— No, no puede, — dijo el príncipe Andréi riendo y, con un apretón de manos, haciendo saber a Pierre que no había necesidad de preguntar. Quería decir algo más, pero en ese momento el príncipe Vasíli se levantó con su hija, y los hombres se pusieron de pie para dejarles pasar.</p>
					<p>— Debe disculparme, mi querido vizconde, — dijo el príncipe Vasíli al francés, tirando cariñosamente de él por la manga hacia su silla para que no se levantara. — Esta desafortunada fiesta en casa del embajador me priva de un placer y le interrumpe. Siento mucho dejar su encantadora velada, — dijo a Anna Pávlovna.</p>
					<p>Su hija, la princesa Hélène, sujetando ligeramente los pliegues de su vestido, pasó entre las sillas, y la sonrisa brilló aún más alegremente en su hermoso rostro. Pierre miró con ojos casi asustados y extasiados a esta belleza cuando pasaba a su lado.</p>
					<p>— Muy encantadora, — dijo el príncipe Andréi.</p>
					<p>— Muy, — dijo Pierre.</p>
					<p>Al pasar, el príncipe Vasíli agarró a Pierre por el brazo y se volvió hacia Anna Pávlovna.</p>
					<p>— Edúqueme a este oso, — dijo. — Lleva un mes viviendo conmigo, y es la primera vez que lo veo en sociedad. Nada es tan necesario para un joven como la sociedad de mujeres inteligentes.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

ch3_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="3">'))
text = text[:ch3_start] + en_text_3 + '\n' + es_text_3 + '\n' + text[ch3_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
