import re

en_text_9 = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter IX</head>
					<p>Of the young people, not counting the countess's eldest daughter (who was four years older than her sister and behaved already like an adult) and the young lady visitor, Nikoláy and the niece Sónya remained in the drawing room. Sónya was a slender, miniature brunette with a soft gaze shaded by long eyelashes, a thick black braid twice wound around her head, and a yellowish tint of skin on her face and especially on her bare, thin, but graceful and muscular arms and neck. By the smoothness of her movements, the softness and flexibility of her small limbs, and a somewhat sly and reserved manner, she resembled a beautiful but not yet formed kitten that will become a charming little cat. She evidently thought it proper to show her participation in the general conversation by a smile; but against her will, her eyes from under their long thick lashes looked at her <foreign xml:lang="fr" n="cousin">cousin</foreign>, who was leaving for the army, with such passionate girlish adoration that her smile could not deceive anyone for a moment, and it was evident that the kitten had crouched only to spring still more energetically and play with her <foreign xml:lang="fr" n="cousin">cousin</foreign> as soon as they, like Borís and Natásha, should get out of that drawing room.</p>
					<p>— Yes, <foreign xml:lang="fr" n="my dear">ma chère</foreign>, — said the old count, turning to the visitor and pointing to his Nikoláy. — His friend Borís has been promoted to officer, and out of friendship he does not want to be left behind; he is giving up the university and leaving me, an old man: going into the military service, <foreign xml:lang="fr" n="my dear">ma chère</foreign>. And a place in the archives was already prepared for him, and everything. There's friendship for you! — said the count inquiringly.</p>
					<p>— Yes, they say war has been declared, — said the visitor.</p>
					<p>— They have been saying so for a long time, — said the count. — They will talk and talk again, and then leave it at that. <foreign xml:lang="fr" n="My dear">Ma chère</foreign>, there's friendship for you! — he repeated. — He is going into the hussars.</p>
					<p>The visitor, not knowing what to say, shook her head.</p>
					<p>— It's not out of friendship at all, — answered Nikoláy, flushing and excusing himself as if from a shameful calumny on him. — It's not friendship at all, but I simply feel a calling for military service.</p>
					<p>He glanced back at his cousin and the young lady visitor: both were looking at him with a smile of approval.</p>
					<p>— Schubert, the colonel of the Pávlograd Hussar regiment, is dining with us today. He has been here on leave and is taking him with him. What is to be done? — said the count, shrugging his shoulders and speaking jokingly of an affair that evidently cost him much grief.</p>
					<p>— I have already told you, papa, — said the son, — that if you don't want to let me go, I will stay. But I know that I am fit for nothing else but military service; I am not a diplomat, not an official, I cannot hide what I feel, — he said, looking constantly with the coquetry of handsome youth at Sónya and the young lady visitor.</p>
					<p>The kitten, drinking him in with her eyes, seemed ready every second to play and show all her feline nature.</p>
					<p>— Well, well, all right! — said the old count, — he always gets hot-headed... It's all Bonaparte has turned everybody's head; everyone is thinking how he got from lieutenant to emperor. Well, God grant it, — he added, not noticing the mocking smile of the visitor.</p>
					<p>The adults began to speak of Bonaparte. Julie, the daughter of Karágina, turned to young Rostóv:</p>
					<p>— What a pity you were not at the Arkhárovs' on Thursday. It was dull for me without you, — she said, smiling tenderly at him.</p>
					<p>The flattered young man with a coquettish smile of youth moved nearer to her and entered into a separate conversation with the smiling Julie, quite unaware that this involuntary smile of his was cutting the heart of Sónya, who was blushing and smiling artificially, with the knife of jealousy. In the middle of the conversation he glanced round at her. Sónya gave him a passionate, resentful look, and, scarcely keeping back the tears in her eyes and the artificial smile on her lips, got up and left the room. All Nikoláy's animation disappeared. He waited for the first break in the conversation and with a distressed face left the room to seek Sónya.</p>
					<p>— How the secrets of all these young people are sewn with white thread! — said Anna Mikháylovna, pointing to the departing Nikoláy. — <foreign xml:lang="fr" n="Cousinhood is a dangerous neighborhood">Cousinage dangereux voisinage</foreign>, — she added.</p>
					<p>— Yes, — said the countess, after the ray of sunshine that had penetrated into the drawing room together with that young generation had disappeared, and as if answering a question no one had asked her, but which constantly occupied her. — How much suffering, how much anxiety has to be borne in order to rejoice in them now! And even now, really, there is more fear than joy. Always fearing, always fearing! It is exactly the age when there are so many dangers for both girls and boys.</p>
					<p>— It all depends on the upbringing, — said the visitor.</p>
					<p>— Yes, you are right, — continued the countess. — Till now I have been, thank God, my children's friend, and enjoy their full confidence, — said the countess, repeating the error of many parents who suppose that their children have no secrets from them. — I know that I shall always be the first <foreign xml:lang="fr" n="confidante">confidente</foreign> of my daughters, and that if Nikólenka, with his ardent character, should play pranks (a boy cannot do without that), at any rate it will not be like those Petersburg gentlemen.</p>
					<p>— Yes, they are splendid, splendid children, — confirmed the count, who always solved questions that were tangled for him by finding everything splendid. — Just think! he took it into his head to join the hussars! Well, what will you have, <foreign xml:lang="fr" n="my dear">ma chère</foreign>!</p>
					<p>— What a sweet creature your youngest is! — said the visitor. — Gunpowder!</p>
					<p>— Yes, gunpowder, — said the count. — Takes after me! And what a voice: though she is my daughter, I will tell the truth, she will be a singer, a second Salomoni. We have engaged an Italian to teach her.</p>
					<p>— Isn't it too early? They say it is harmful for the voice to study at that age.</p>
					<p>— Oh, no, how can it be too early! — said the count. — Why, our mothers used to marry at twelve or thirteen?</p>
					<p>— She is already in love with Borís! How about that? — said the countess, smiling quietly, looking at Borís's mother, and, evidently answering a thought that always occupied her, went on. — Well, you see, if I kept her strictly, if I forbade her... God knows what they would do on the sly (the countess meant they would kiss), but now I know her every word. She will come running to me herself in the evening and tell me everything. Perhaps I spoil her, but really, it seems to be better. I kept the eldest strictly.</p>
					<p>— Yes, I was brought up quite differently, — said the eldest, the handsome Countess Véra, smiling.</p>
					<p>But the smile did not adorn Véra's face, as is usually the case; on the contrary, her face became unnatural and therefore unpleasant. The eldest, Véra, was good-looking, was not stupid, studied excellently, was well brought up, her voice was pleasant, what she said was true and to the point; but, strange to say, everyone, both the visitor and the countess, glanced round at her as if surprised that she had said it, and felt awkward.</p>
					<p>— People are always too clever by half with their eldest children, they want to make something extraordinary out of them, — said the visitor.</p>
					<p>— It's no use hiding a sin, <foreign xml:lang="fr" n="my dear">ma chère</foreign>! My dear countess was too clever by half with Véra, — said the count. — Well, what of it! she turned out a splendid girl all the same, — he added, winking approvingly at Véra.</p>
					<p>The visitors rose and took their leave, promising to come to dinner.</p>
					<p>— What a manner! They sat and sat! — said the countess, seeing the visitors out.</p>
				</div>"""

es_text_9 = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo IX</head>
					<p>De los jóvenes, sin contar a la hija mayor de la condesa (que era cuatro años mayor que su hermana y se comportaba ya como una adulta) y a la joven visitante, en el salón se quedaron Nikoláy y la sobrina Sónya. Sónya era una morenita esbelta y diminuta, de mirada suave sombreada por largas pestañas, una gruesa trenza negra que le daba dos vueltas a la cabeza y un tono de piel amarillento en el rostro y sobre todo en los brazos y el cuello desnudos, delgados pero gráciles y musculosos. Por la suavidad de sus movimientos, la blandura y flexibilidad de sus pequeños miembros y unos modales un tanto pícaros y reservados, recordaba a una gatita hermosa pero aún no formada, que se convertirá en una gatita encantadora. Evidentemente, consideraba decoroso mostrar su participación en la conversación general con una sonrisa; pero, a su pesar, sus ojos asomaban por debajo de sus largas y espesas pestañas para mirar a su <foreign xml:lang="fr" n="primo">cousin</foreign>, que se marchaba al ejército, con una adoración de muchacha tan apasionada que su sonrisa no podía engañar a nadie ni un momento, y era evidente que la gatita se había agazapado sólo para saltar con más energía aún y jugar con su <foreign xml:lang="fr" n="primo">cousin</foreign> en cuanto, como Borís y Natásha, salieran de aquel salón.</p>
					<p>— Sí, <foreign xml:lang="fr" n="querida">ma chère</foreign>, — dijo el viejo conde, dirigiéndose a la visita y señalando a su Nikoláy. — Su amigo Borís ha sido ascendido a oficial, y él por amistad no quiere quedarse atrás; deja la universidad y me abandona a mí, un anciano: entra en el servicio militar, <foreign xml:lang="fr" n="querida">ma chère</foreign>. Y ya le tenían preparado un puesto en el archivo, y todo. ¡Vaya amistad! — dijo el conde interrogante.</p>
					<p>— Sí, dicen que se ha declarado la guerra, — dijo la visitante.</p>
					<p>— Llevan tiempo diciéndolo, — dijo el conde. — Hablarán y volverán a hablar, y luego lo dejarán estar. <foreign xml:lang="fr" n="Querida">Ma chère</foreign>, ¡vaya amistad! — repitió. — Se va a los húsares.</p>
					<p>La visitante, sin saber qué decir, sacudió la cabeza.</p>
					<p>— No es en absoluto por amistad, — respondió Nikoláy, ruborizándose y excusándose como si se tratara de una calumnia vergonzosa sobre él. — No es en absoluto por amistad, sino que simplemente siento vocación por el servicio militar.</p>
					<p>Miró de reojo a su prima y a la joven visita: ambas le miraban con una sonrisa de aprobación.</p>
					<p>— Schubert, el coronel del regimiento de Húsares de Pávlograd, cena hoy con nosotros. Ha estado aquí de permiso y se lo lleva con él. ¿Qué se le va a hacer? — dijo el conde, encogiéndose de hombros y hablando en broma de un asunto que evidentemente le costaba mucho dolor.</p>
					<p>— Ya se lo he dicho, papá, — dijo el hijo, — que si no quiere dejarme ir, me quedaré. Pero sé que no sirvo para otra cosa que para el servicio militar; no soy diplomático, ni funcionario, no puedo ocultar lo que siento, — dijo, mirando constantemente con el coqueteo de la juventud apuesto a Sónya y a la joven visitante.</p>
					<p>La gatita, bebiéndoselo con los ojos, parecía dispuesta a cada segundo a jugar y mostrar toda su naturaleza felina.</p>
					<p>— Bueno, bueno, ¡está bien! — dijo el viejo conde, — siempre se acalora... Todo esto de Bonaparte ha trastornado la cabeza de todos; todo el mundo piensa en cómo pasó de teniente a emperador. Bueno, Dios lo quiera, — añadió, sin reparar en la sonrisa burlona de la visitante.</p>
					<p>Los adultos empezaron a hablar de Bonaparte. Julie, la hija de Karágina, se volvió hacia el joven Rostóv:</p>
					<p>— Qué pena que no estuviera usted el jueves en casa de los Arkhárov. Me aburrí sin usted, — le dijo, sonriéndole tiernamente.</p>
					<p>El joven, halagado, con una sonrisa coqueta de juventud, se acercó a ella y entabló una conversación aparte con la sonriente Julie, sin darse cuenta de que esta sonrisa involuntaria suya estaba cortando el corazón de Sónya, que se ruborizaba y sonreía artificialmente, con el cuchillo de los celos. En medio de la conversación él la miró de reojo. Sónya le dirigió una mirada apasionada y resentida y, apenas conteniendo las lágrimas en los ojos y la sonrisa artificial en los labios, se levantó y salió de la habitación. Toda la animación de Nikoláy desapareció. Esperó a la primera pausa en la conversación y, con rostro afligido, salió de la habitación a buscar a Sónya.</p>
					<p>— ¡Cómo se cosen con hilo blanco los secretos de todos estos jóvenes! — dijo Anna Mikháylovna, señalando a Nikoláy, que se marchaba. — <foreign xml:lang="fr" n="Primo hermano, peligro cercano">Cousinage dangereux voisinage</foreign>, — añadió.</p>
					<p>— Sí, — dijo la condesa, después de que desapareciera el rayo de sol que había penetrado en el salón junto con aquella joven generación, y como si respondiera a una pregunta que nadie le había hecho, pero que la ocupaba constantemente. — ¡Cuánto sufrimiento, cuánta ansiedad hay que soportar para alegrarse de ellos ahora! Y aún ahora, de verdad, hay más miedo que alegría. ¡Siempre temiendo, siempre temiendo! Es exactamente la edad en la que hay tantos peligros tanto para las chicas como para los chicos.</p>
					<p>— Todo depende de la educación, — dijo la visitante.</p>
					<p>— Sí, tiene razón, — prosiguió la condesa. — Hasta ahora he sido, gracias a Dios, amiga de mis hijos, y gozo de toda su confianza, — decía la condesa, repitiendo el error de muchos padres que suponen que sus hijos no tienen secretos para ellos. — Sé que siempre seré la primera <foreign xml:lang="fr" n="confidente">confidente</foreign> de mis hijas, y que si Nikólenka, con su carácter ardiente, hiciera travesuras (un chico no puede pasarse sin ellas), en cualquier caso no será como esos señores de Petersburgo.</p>
					<p>— Sí, son unos chicos espléndidos, espléndidos, — confirmó el conde, que siempre resolvía las cuestiones que se le enredaban encontrándolo todo espléndido. — ¡Fíjese! ¡Se le metió en la cabeza hacerse húsar! ¡Pues qué le vamos a hacer, <foreign xml:lang="fr" n="querida">ma chère</foreign>!</p>
					<p>— ¡Qué criatura tan dulce es su hija menor! — dijo la visitante. — ¡Pólvora!</p>
					<p>— Sí, pólvora, — dijo el conde. — ¡Se parece a mí! Y qué voz: aunque es mi hija, diré la verdad, será cantante, una segunda Salomoni. Hemos contratado a un italiano para que le dé clases.</p>
					<p>— ¿No es demasiado pronto? Dicen que es perjudicial para la voz estudiar a esa edad.</p>
					<p>— ¡Oh, no, cómo va a ser demasiado pronto! — dijo el conde. — ¿Por qué nuestras madres solían casarse a los doce o trece años?</p>
					<p>— ¡Ya está enamorada de Borís! ¿Qué le parece? — dijo la condesa, sonriendo en silencio, mirando a la madre de Borís, y, evidentemente respondiendo a un pensamiento que la ocupaba siempre, continuó. — Pues verá, si yo la mantuviera a raya, si se lo prohibiera... Dios sabe lo que harían a escondidas (la condesa quería decir que se besarían), pero ahora conozco cada una de sus palabras. Ella misma viene corriendo a verme por la noche y me lo cuenta todo. Quizá la mimo, pero la verdad es que me parece mejor. A la mayor la tuve a raya.</p>
					<p>— Sí, a mí me criaron de un modo muy distinto, — dijo la mayor, la bella condesa Véra, sonriendo.</p>
					<p>Pero la sonrisa no adornó el rostro de Véra, como suele ocurrir; por el contrario, su rostro se volvió antinatural y, por tanto, desagradable. La mayor, Véra, era guapa, no era estúpida, estudiaba estupendamente, estaba bien educada, su voz era agradable, lo que decía era cierto y venía al caso; pero, por extraño que parezca, todos, tanto la visitante como la condesa, se giraron para mirarla como sorprendidos de que lo hubiera dicho, y se sintieron incómodos.</p>
					<p>— La gente siempre se pasa de lista con sus hijos mayores, quieren hacer algo extraordinario con ellos, — dijo la visita.</p>
					<p>— ¡No se puede ocultar un pecado, <foreign xml:lang="fr" n="querida">ma chère</foreign>! Mi querida condesa se pasó de lista con Véra, — dijo el conde. — Bueno, ¡y qué! De todos modos resultó ser una chica espléndida, — añadió, guiñando un ojo a Véra con aprobación.</p>
					<p>Las visitas se levantaron y se despidieron, prometiendo venir a cenar.</p>
					<p>— ¡Vaya modales! ¡Se han pasado el rato sentadas! — dijo la condesa, despidiendo a las visitas.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

ch9_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="9">'))
text = text[:ch9_start] + en_text_9 + '\n' + es_text_9 + '\n' + text[ch9_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
