import re

en_text_8 = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter VIII</head>
					<p>A silence ensued. The countess looked at her visitor, smiling pleasantly, without, however, concealing the fact that she would not be at all sorry now if the visitor got up and left. The visitor's daughter was already adjusting her dress, looking inquiringly at her mother, when suddenly from the next room was heard the running to the door of several men's and women's feet, the crash of a caught and overturned chair, and a thirteen-year-old girl ran into the room, wrapping something in her short muslin skirt, and stopped in the middle of the room. It was evident she had accidentally, from an uncalculated run, jumped so far. At the same moment there appeared in the doorway a student with a crimson collar, a Guards officer, a fifteen-year-old girl, and a plump, rosy boy in a child's jacket.</p>
					<p>The count jumped up and, swaying, spread his arms wide around the girl who had run in.</p>
					<p>— Ah, here she is! — he cried laughing. — The name-day girl! <foreign xml:lang="fr" n="My dear">Ma chère</foreign>, the name-day girl!</p>
					<p>— <foreign xml:lang="fr" n="My dear, there is a time for everything">Ma chère, il y a un temps pour tout</foreign>, — said the countess, pretending to be severe. — You spoil her so, <foreign xml:lang="fr" n="Ilyá">Élie</foreign>, — she added to her husband.</p>
					<p>— <foreign xml:lang="fr" n="Hello, my dear, I congratulate you">Bonjour, ma chère, je vous félicite</foreign>, — said the visitor. — <foreign xml:lang="fr" n="What a delightful child!">Quelle délicieuse enfant!</foreign> — she added, turning to the mother.</p>
					<p>The black-eyed, large-mouthed, plain, but lively girl, with her childish bare shoulders, which had popped out of her bodice from her rapid run, with her black curls tumbled back, her thin bare arms and tiny feet in lace pantaloons and low shoes, was at that charming age when a girl is no longer a child, but the child is not yet a young woman. Twisting away from her father, she ran up to her mother and, paying no attention whatever to her severe remark, hid her flushed face in the lace of her mother's mantilla and laughed. She was laughing at something, talking jerkily about a doll, which she took out from under her skirt.</p>
					<p>— Do you see?... A doll... Mimi... Do you see.</p>
					<p>And Natásha could not speak anymore (it all seemed funny to her). She fell against her mother and burst out laughing so loudly and ringingly that everyone, even the prim visitor, laughed against their will.</p>
					<p>— Come, go, go away with your monster! — said the mother, pushing her daughter away with feigned anger. — This is my youngest, — she turned to the visitor.</p>
					<p>Natásha, tearing her face for a moment from her mother's lace kerchief, looked up at her through tears of laughter and again hid her face.</p>
					<p>The visitor, compelled to admire the family scene, thought it necessary to take some part in it.</p>
					<p>— Tell me, my dear, — she said, turning to Natásha, — how is this Mimi related to you? A daughter, surely?</p>
					<p>Natásha did not like the tone of condescension to childish talk with which the visitor addressed her. She answered nothing and looked seriously at the visitor.</p>
					<p>Meanwhile all this younger generation: Borís, the officer, the son of Princess Anna Mikháylovna; Nikoláy, the student, the count's eldest son; Sónya, the count's fifteen-year-old niece; and little Petrúsha, the youngest son, had all settled down in the drawing room and were evidently trying to keep within the bounds of propriety the animation and mirth that still breathed in their every feature. It was evident that there, in the back rooms, from which they had all come running so impetuously, they had had conversations more amusing than here about town gossip, the weather, and <foreign xml:lang="fr" n="Countess Apráksina">comtesse Apraksine</foreign>. Occasionally they glanced at one another and could hardly restrain their laughter.</p>
					<p>The two young men, the student and the officer, friends from childhood, were of the same age and both handsome, but not like each other. Borís was a tall, fair youth with regular, delicate features on a calm and handsome face; Nikoláy was a short, curly-haired young man with an open expression. A dark down was already showing on his upper lip, and his whole face expressed impetuosity and enthusiasm. Nikoláy blushed as soon as he entered the drawing room. It was evident that he sought and could not find what to say; Borís, on the contrary, immediately found himself and related calmly and jokingly how he had known this Mimi doll when she was still a young girl with a nose that was not yet spoiled, how in five years, in his memory, she had grown old, and how her head had cracked right across the skull. Having said this, he looked at Natásha. Natásha turned away from him, looked at her younger brother, who, with his eyes squeezed shut, was shaking with soundless laughter, and, unable to contain herself any longer, jumped up and ran out of the room as fast as her swift little feet could carry her. Borís did not laugh.</p>
					<p>— You too were wanting to go, I think, <foreign xml:lang="fr" n="mama">maman</foreign>? Shall I order the carriage? — he said, turning with a smile to his mother.</p>
					<p>— Yes, go, go, order it to be got ready, — she said, smiling.</p>
					<p>Borís quietly went out the door and went after Natásha; the plump boy ran angrily after them, as if vexed at the disturbance that had occurred in his occupations.</p>
				</div>"""

es_text_8 = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo VIII</head>
					<p>Se produjo un silencio. La condesa miraba a su invitada, sonriendo agradablemente, sin ocultar, no obstante, que no le importaría en absoluto que la invitada se levantara y se fuera. La hija de la visitante ya se estaba arreglando el vestido y miraba inquisitivamente a su madre, cuando de repente, desde la habitación contigua, se oyó el correr hacia la puerta de varios pies de hombres y mujeres, el estrépito de una silla enganchada y volcada, y una niña de trece años entró corriendo en la habitación, envolviendo algo en su corta falda de muselina, y se detuvo en medio de la habitación. Era evidente que, sin querer, en una carrera mal calculada, había saltado demasiado lejos. En ese mismo instante aparecieron en la puerta un estudiante con cuello carmesí, un oficial de la Guardia, una muchacha de quince años y un niño regordete y sonrosado con chaquetilla infantil.</p>
					<p>El conde se levantó de un salto y, tambaleándose, abrió los brazos para rodear a la niña que había entrado corriendo.</p>
					<p>— ¡Ah, aquí está! — gritó riendo. — ¡La cumpleañera! ¡<foreign xml:lang="fr" n="Querida">Ma chère</foreign>, la cumpleañera!</p>
					<p>— <foreign xml:lang="fr" n="Querida, hay tiempo para todo">Ma chère, il y a un temps pour tout</foreign>, — dijo la condesa, fingiendo severidad. — La mimas demasiado, <foreign xml:lang="fr" n="Ilyá">Élie</foreign>, — añadió dirigiéndose a su marido.</p>
					<p>— <foreign xml:lang="fr" n="Hola, querida, te felicito">Bonjour, ma chère, je vous félicite</foreign>, — dijo la visitante. — <foreign xml:lang="fr" n="¡Qué niña tan encantadora!">Quelle délicieuse enfant!</foreign> — añadió, volviéndose hacia la madre.</p>
					<p>La niña de ojos negros, boca grande, poco agraciada pero vivaracha, con sus infantiles hombros desnudos, que se habían salido del corpiño a causa de su rápida carrera, con sus rizos negros echados hacia atrás, sus delgados brazos desnudos y sus piececitos en pantalones de encaje y zapatos bajos, se encontraba en esa edad encantadora en la que una niña ya no es una niña, pero la niña aún no es una jovencita. Zafándose de su padre, corrió hacia su madre y, sin prestar la menor atención a su severo reproche, escondió su rostro enrojecido en los encajes de la mantilla de su madre y se echó a reír. Se reía de algo, hablando a sacudidas de una muñeca que sacó de debajo de la falda.</p>
					<p>— ¿Ves?... Una muñeca... Mimi... ¿Ves?</p>
					<p>Y Natásha no pudo hablar más (todo le parecía gracioso). Cayó sobre su madre y rompió a reír con tantas ganas y resonancia que todos, incluso la remilgada visitante, se rieron a su pesar.</p>
					<p>— ¡Venga, vete, vete con tu monstruo! — dijo la madre, apartando a su hija con enfado fingido. — Ésta es mi hija menor, — se dirigió a la visita.</p>
					<p>Natásha, apartando un momento la cara del pañuelo de encaje de su madre, la miró a través de lágrimas de risa y volvió a esconder la cara.</p>
					<p>La visitante, obligada a admirar la escena familiar, creyó necesario participar en ella.</p>
					<p>— Dime, querida, — dijo, dirigiéndose a Natásha, — ¿qué parentesco te une a esta Mimi? ¿Es tu hija, seguro?</p>
					<p>A Natásha no le gustó el tono de condescendencia a la charla infantil con que se dirigió a ella la visitante. No respondió nada y miró seriamente a la visitante.</p>
					<p>Mientras tanto, toda esta generación más joven: Borís, el oficial, hijo de la princesa Anna Mikháylovna; Nikoláy, el estudiante, hijo mayor del conde; Sónya, la sobrina de quince años del conde; y el pequeño Petrúsha, el hijo menor, se habían instalado en el salón y evidentemente trataban de mantener dentro de los límites del decoro la animación y la alegría que aún respiraban en todos sus rasgos. Era evidente que allí, en las habitaciones del fondo, de donde habían salido corriendo tan impetuosamente, habían tenido conversaciones más divertidas que aquí sobre los cotilleos del pueblo, el tiempo y la <foreign xml:lang="fr" n="Condesa Apráksina">comtesse Apraksine</foreign>. De vez en cuando se miraban unos a otros y apenas podían contener la risa.</p>
					<p>Los dos jóvenes, el estudiante y el oficial, amigos desde la infancia, tenían la misma edad y ambos eran apuestos, pero no se parecían. Borís era un joven rubio y alto, de rasgos regulares y delicados, en un rostro sereno y apuesto; Nikoláy era un joven de baja estatura, de pelo rizado y expresión abierta. Un vello oscuro asomaba ya en su labio superior, y todo su rostro expresaba impetuosidad y entusiasmo. Nikoláy se ruborizó en cuanto entró en el salón. Era evidente que buscaba y no encontraba qué decir; Borís, por el contrario, se encontró inmediatamente a sí mismo y relató con calma y en tono de broma cómo había conocido a esta muñeca Mimi cuando aún era una jovencita de nariz no estropeada, cómo en cinco años, en su memoria, había envejecido y cómo su cabeza se había partido de un lado a otro del cráneo. Tras decir esto, miró a Natásha. Natásha se apartó de él, miró a su hermano menor, que, con los ojos bien cerrados, temblaba de risa silenciosa, y, no pudiendo contenerse más, dio un salto y salió corriendo de la habitación tan deprisa como sus ágiles piececitos se lo permitieron. Borís no se rió.</p>
					<p>— Usted también quería irse, creo, <foreign xml:lang="fr" n="mamá">maman</foreign>? ¿Mando a por el carruaje? — dijo, dirigiéndose con una sonrisa a su madre.</p>
					<p>— Sí, ve, ve, manda que lo preparen, — dijo ella, sonriendo.</p>
					<p>Borís salió sigilosamente por la puerta y fue tras Natásha; el muchacho regordete corrió enfadado tras ellos, como molesto por el trastorno que se había producido en sus ocupaciones.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

ch8_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="8">'))
text = text[:ch8_start] + en_text_8 + '\n' + es_text_8 + '\n' + text[ch8_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
