import re

en_text = """				<div type="version" xml:lang="en" subtype="translation">
					<head>Volume I, Part One, Chapter II</head>
					<p>Anna Pávlovna's drawing room gradually began to fill up. The highest aristocracy of Petersburg arrived, people most diverse in age and character, but alike in the society in which they all lived; Prince Vasíli's daughter, the beautiful Hélène, came to fetch her father so that they might go together to the ambassador's fête. She wore a cipher and a ball gown. There arrived too the young, little Princess Bolkónskaya, known as <foreign xml:lang="fr" n="the most seductive woman in Petersburg">la femme la plus séduisante de Pétersbourg</foreign>, who had married the previous winter and now, because of her pregnancy, did not go out into <emph>grand</emph> society, but still attended small evening parties. Prince Hippolyte, Prince Vasíli's son, arrived with Mortemart, whom he introduced; the Abbé Morio and many others arrived as well.</p>
					<p>— Have you not yet seen, or: — are you not acquainted with <foreign xml:lang="fr" n="my aunt">ma tante</foreign>? — Anna Pávlovna said to her arriving guests, and very seriously led them up to a little old lady wearing tall bows, who had sailed out of another room as soon as the guests began to arrive. She called them by name, slowly shifting her eyes from the guest to <foreign xml:lang="fr" n="my aunt">ma tante</foreign>, and then stepped away.</p>
					<p>All the guests performed the ceremony of greeting the aunt, who was known to no one, of interest to no one, and of use to no one. Anna Pávlovna, with sad, solemn sympathy, followed their greetings, silently approving them. <foreign xml:lang="fr" n="My aunt">Ma tante</foreign> spoke to everyone in identical terms about their health, about her own health, and about the health of Her Majesty, which today was, thank God, better. All those who approached, out of decorum showing no haste, moved away from the old lady with a sense of relief at having fulfilled a heavy duty, in order not to approach her again the whole evening.</p>
					<p>The young Princess Bolkónskaya arrived with her work in a gold-embroidered velvet bag. Her pretty upper lip, on which a slight dark down was visible, was too short for her teeth, but it opened all the more sweetly, and all the more sweetly did it sometimes stretch and draw down over the lower one. As is always the case with wholly attractive women, her defect — the shortness of her lip and her half-open mouth — seemed her own peculiar, individual beauty. Everyone was delighted to look at this pretty, healthy, and vivacious future mother, who bore her condition so lightly. Old men and bored, gloomy young men felt as if they themselves became like her, after spending some time and talking with her. Anyone who spoke to her and saw her bright little smile and gleaming white teeth, which showed incessantly, thought that he was particularly amiable today. And everyone thought so.</p>
					<p>The little princess, waddling and taking short rapid steps, walked around the table with her workbag on her arm, and, cheerfully arranging her dress, sat down on the sofa near the silver samovar, as if everything she did was a <foreign xml:lang="fr" n="party of pleasure">partie de plaisir</foreign> for herself and for all those around her.</p>
					<p>— <foreign xml:lang="fr" n="I have brought my work">J'ai apporté mon ouvrage</foreign>, — she said, opening her reticule and addressing everyone at once.</p>
					<p>— See here, Annette, <foreign xml:lang="fr" n="do not play a bad trick on me">ne me jouez pas un mauvais tour</foreign>, — she turned to the hostess. — <foreign xml:lang="fr" n="You wrote to me that it was a very small evening party; see how I am dressed up">Vous m'avez écrit, que c'était une toute petite soirée; voyez, comme je suis attifée</foreign>.</p>
					<p>And she spread her arms to show her elegant little gray dress, trimmed with lace and belted slightly below the breast with a broad ribbon.</p>
					<p>— <foreign xml:lang="fr" n="Rest easy, Lise, you will always be the prettiest">Soyez tranquille, Lise, vous serez toujours la plus jolie</foreign>, — replied Anna Pávlovna.</p>
					<p>— <foreign xml:lang="fr" n="You know, my husband is abandoning me">Vous savez, mon mari m'abandonne</foreign>, — she continued in the same tone, addressing a general, — <foreign xml:lang="fr" n="he is going to get himself killed. Tell me, why this nasty war">il va se faire tuer. Dites moi, pourquoi cette vilaine guerre</foreign>, — she said to Prince Vasíli, and, without waiting for an answer, turned to Prince Vasíli's daughter, the beautiful Hélène.</p>
					<p>— <foreign xml:lang="fr" n="What a delightful person this little princess is!">Quelle délicieuse personne, que cette petite princesse!</foreign> — Prince Vasíli said quietly to Anna Pávlovna.</p>
					<p>Soon after the little princess, a massive, stout young man entered, with a cropped head, spectacles, the light-colored breeches fashionable at the time, a high jabot, and a brown dress coat. This stout young man was the illegitimate son of a celebrated grandee of Catherine's time, Count Bezúkhov, who was now dying in Moscow. He had not yet entered the service anywhere, had only just returned from abroad, where he had been educated, and was appearing in society for the first time. Anna Pávlovna greeted him with the nod she reserved for the very lowest hierarchy in her salon. But, in spite of this lowest-grade greeting, at the sight of the entering Pierre, a look of anxiety and fear appeared on Anna Pávlovna's face, similar to that which is expressed at the sight of something too huge and unsuited to the place. Though, indeed, Pierre was somewhat larger than the other men in the room, this fear could only relate to the intelligent and at the same time timid, observant, and natural look that distinguished him from everyone else in this drawing room.</p>
					<p>— <foreign xml:lang="fr" n="It is very kind of you, Monsieur Pierre, to have come to see a poor invalid">C'est bien aimable à vous, <emph>monsieur Pierre,</emph> d'être venu voir une pauvre malade</foreign>, — Anna Pávlovna said to him, exchanging a frightened glance with the aunt to whom she was leading him. Pierre muttered something incomprehensible and continued to search for something with his eyes. He smiled joyfully and cheerfully, bowing to the little princess as to a close acquaintance, and went up to the aunt. Anna Pávlovna's fear was not in vain, because Pierre, without listening to the end of the aunt's speech about Her Majesty's health, walked away from her. Anna Pávlovna stopped him in fright with the words:</p>
					<p>— Do you not know the Abbé Morio? he is a very interesting man... — she said.</p>
					<p>— Yes, I have heard of his plan for perpetual peace, and it is very interesting, but hardly possible...</p>
					<p>— You think so?.. — said Anna Pávlovna, just to say something and get back to her duties as hostess, but Pierre committed a reverse incivility. Before, without listening to the end of his interlocutor's words, he had walked away; now he stopped with his conversation an interlocutor who needed to get away from him. Bending his head and planting his big feet apart, he began to prove to Anna Pávlovna why he considered the Abbé's plan a chimera.</p>
					<p>— We will talk later, — said Anna Pávlovna, smiling.</p>
					<p>And, having got rid of a young man who did not know how to behave, she returned to her duties as hostess and continued to listen and observe, ready to lend assistance at any point where the conversation flagged. Just as the master of a spinning mill, having set the workers in their places, walks up and down the establishment, noticing the immobility or the unusual, creaking, too-loud sound of a spindle, hastens to it, restrains it, or sets it going properly — so Anna Pávlovna, walking up and down her drawing room, approached a circle that had fallen silent or was talking too much, and with a single word or movement set the steady, proper conversational machine going again. But amid these cares, a special fear for Pierre was constantly visible in her. She kept a watchful eye on him as he went to listen to what was being said around Mortemart, and then moved away to another circle where the Abbé was speaking. For Pierre, educated abroad, this evening at Anna Pávlovna's was the first he had seen in Russia. He knew that all the intelligentsia of Petersburg was gathered here, and his eyes wandered like a child's in a toy shop. He was constantly afraid of missing the clever conversations he might hear. Looking at the confident and elegant expressions on the faces gathered here, he kept expecting something particularly intelligent. Finally, he went up to Morio. The conversation seemed interesting to him, and he stopped, waiting for an opportunity to express his thoughts, as young men love to do.</p>
				</div>"""

es_text = """				<div type="version" xml:lang="es" subtype="translation-es">
					<head>Volumen I, Primera Parte, Capítulo II</head>
					<p>El salón de Anna Pávlovna empezó a llenarse poco a poco. Llegó la más alta aristocracia de Petersburgo, personas muy diversas en edad y carácter, pero semejantes en la sociedad en la que todos vivían; la hija del príncipe Vasíli, la hermosa Hélène, fue a buscar a su padre para ir juntos a la fiesta del embajador. Llevaba un monograma y un vestido de baile. Llegó también la joven y pequeña princesa Bolkónskaya, conocida como <foreign xml:lang="fr" n="la mujer más seductora de Petersburgo">la femme la plus séduisante de Pétersbourg</foreign>, que se había casado el invierno anterior y ahora, debido a su embarazo, no salía a la <emph>gran</emph> sociedad, pero seguía asistiendo a pequeñas veladas. El príncipe Hippolyte, hijo del príncipe Vasíli, llegó con Mortemart, a quien presentó; el abate Morio y muchos otros llegaron también.</p>
					<p>— ¿Aún no ha visto, o: no conoce a <foreign xml:lang="fr" n="mi tía">ma tante</foreign>? — decía Anna Pávlovna a los invitados que iban llegando, y muy seriamente los conducía hasta una viejecita con altos lazos, que había salido flotando de otra habitación en cuanto empezaron a llegar los invitados; los llamaba por su nombre, pasando lentamente los ojos del invitado a <foreign xml:lang="fr" n="mi tía">ma tante</foreign>, y luego se apartaba.</p>
					<p>Todos los invitados cumplían la ceremonia de saludar a la tía, que no era conocida de nadie, ni interesaba a nadie, ni era necesaria para nadie. Anna Pávlovna seguía con triste y solemne simpatía sus saludos, aprobándolos en silencio. <foreign xml:lang="fr" n="Mi tía">Ma tante</foreign> hablaba a todos en términos idénticos sobre su salud, sobre la suya propia y sobre la de Su Majestad, que hoy, gracias a Dios, estaba mejor. Todos los que se acercaban, sin mostrar prisa por decoro, se alejaban de la anciana con una sensación de alivio por haber cumplido un pesado deber, para no volver a acercarse a ella en toda la noche.</p>
					<p>La joven princesa Bolkónskaya llegó con su labor en una bolsa de terciopelo bordada en oro. Su bonito labio superior, sobre el que se veía un ligerísimo vello oscuro, era demasiado corto para sus dientes, pero se abría con tanta más dulzura, y con tanta más dulzura se estiraba a veces y bajaba sobre el inferior. Como siempre ocurre con las mujeres totalmente atractivas, su defecto — la cortedad de su labio y su boca entreabierta — parecía su propia y peculiar belleza. A todos les alegraba mirar a esta bonita, sana y vivaz futura madre, que llevaba tan a la ligera su estado. A los ancianos y a los jóvenes aburridos y lúgubres les parecía que ellos mismos se volvían como ella, después de pasar un rato y hablar con ella. Cualquiera que hablara con ella y viera su luminosa sonrisita y sus relucientes dientes blancos, que asomaban incesantemente, pensaba que aquel día estaba especialmente amable. Y todos lo pensaban.</p>
					<p>La princesita, contoneándose y dando pasos cortos y rápidos, dio la vuelta a la mesa con su bolsa de labor en el brazo y, arreglándose alegremente el vestido, se sentó en el sofá, cerca del samovar de plata, como si todo lo que hiciera fuera una <foreign xml:lang="fr" n="partida de placer">partie de plaisir</foreign> para ella y para todos los que la rodeaban.</p>
					<p>— <foreign xml:lang="fr" n="He traído mi labor">J'ai apporté mon ouvrage</foreign>, — dijo, abriendo su retículo y dirigiéndose a todos a la vez.</p>
					<p>— Mire, Annette, <foreign xml:lang="fr" n="no me juegue una mala pasada">ne me jouez pas un mauvais tour</foreign>, — se dirigió a la anfitriona. — <foreign xml:lang="fr" n="Me escribió que era una velada muy pequeña; vea cómo vengo arreglada">Vous m'avez écrit, que c'était une toute petite soirée; voyez, comme je suis attifée</foreign>.</p>
					<p>Y abrió los brazos para mostrar su elegante vestidito gris, adornado con encajes y ceñido ligeramente por debajo del pecho con una ancha cinta.</p>
					<p>— <foreign xml:lang="fr" n="Tranquila, Lise, siempre será la más guapa">Soyez tranquille, Lise, vous serez toujours la plus jolie</foreign>, — respondió Anna Pávlovna.</p>
					<p>— <foreign xml:lang="fr" n="Sabe, mi marido me abandona">Vous savez, mon mari m'abandonne</foreign>, — continuó ella en el mismo tono, dirigiéndose a un general, — <foreign xml:lang="fr" n="va a hacerse matar. Dígame, por qué esta fea guerra">il va se faire tuer. Dites moi, pourquoi cette vilaine guerre</foreign>, — le dijo al príncipe Vasíli y, sin esperar respuesta, se volvió hacia la hija del príncipe Vasíli, la hermosa Hélène.</p>
					<p>— <foreign xml:lang="fr" n="¡Qué persona tan deliciosa es esta princesita!">Quelle délicieuse personne, que cette petite princesse!</foreign> — dijo el príncipe Vasíli en voz baja a Anna Pávlovna.</p>
					<p>Poco después de la princesita entró un joven macizo y corpulento, con la cabeza rapada, gafas, los pantalones claros de moda en la época, una alta chorrera y un frac marrón. Este joven corpulento era el hijo ilegítimo de un célebre grande de la época de Catalina, el conde Bezúkhov, que ahora agonizaba en Moscú. Todavía no había entrado al servicio en ninguna parte, acababa de regresar del extranjero, donde se había educado, y aparecía en sociedad por primera vez. Anna Pávlovna le saludó con la inclinación de cabeza que reservaba a la jerarquía más baja de su salón. Pero, a pesar de este saludo de la categoría más baja, al ver entrar a Pierre, apareció en el rostro de Anna Pávlovna una expresión de ansiedad y miedo, semejante a la que se expresa al ver algo demasiado enorme e inadecuado al lugar. Aunque, de hecho, Pierre era algo más grande que los demás hombres de la habitación, este miedo sólo podía relacionarse con la mirada inteligente y a la vez tímida, observadora y natural que le distinguía de todos los demás en aquel salón.</p>
					<p>— <foreign xml:lang="fr" n="Es muy amable de su parte, señor Pierre, haber venido a ver a una pobre enferma">C'est bien aimable à vous, <emph>monsieur Pierre,</emph> d'être venu voir une pauvre malade</foreign>, — le dijo Anna Pávlovna, intercambiando una mirada asustada con la tía hacia la que le conducía. Pierre murmuró algo incomprensible y siguió buscando algo con los ojos. Sonrió con alegría y jovialidad, inclinándose ante la princesita como ante una conocida cercana, y se acercó a la tía. El miedo de Anna Pávlovna no fue en vano, porque Pierre, sin escuchar hasta el final el discurso de la tía sobre la salud de Su Majestad, se alejó de ella. Anna Pávlovna le detuvo asustada con estas palabras:</p>
					<p>— ¿No conoce al abate Morio? es un hombre muy interesante... — le dijo.</p>
					<p>— Sí, he oído hablar de su plan para la paz perpetua, y es muy interesante, pero apenas posible...</p>
					<p>— ¿Lo cree usted?.. — dijo Anna Pávlovna, sólo por decir algo y volver a sus deberes de anfitriona, pero Pierre cometió una descortesía a la inversa. Antes, sin escuchar hasta el final las palabras de su interlocutora, se había alejado; ahora detuvo con su conversación a una interlocutora que necesitaba alejarse de él. Inclinando la cabeza y separando sus grandes pies, empezó a demostrar a Anna Pávlovna por qué consideraba una quimera el plan del abate.</p>
					<p>— Hablaremos más tarde, — dijo Anna Pávlovna, sonriendo.</p>
					<p>Y, tras deshacerse de un joven que no sabía comportarse, volvió a sus deberes de anfitriona y siguió escuchando y observando, dispuesta a prestar ayuda en cualquier punto en que la conversación decayera. Del mismo modo que el amo de una hilandería, tras colocar a los obreros en sus puestos, se pasea por el establecimiento, y al notar la inmovilidad o el sonido inusual, chirriante y demasiado fuerte de un huso, se apresura hacia él, lo frena o lo pone en marcha adecuadamente — así Anna Pávlovna, paseándose por su salón, se acercaba a un círculo que se había quedado callado o que hablaba demasiado, y con una sola palabra o movimiento volvía a poner en marcha la constante y adecuada máquina de conversación. Pero en medio de estas preocupaciones, era constantemente visible en ella un miedo especial por Pierre. No le quitaba el ojo de encima mientras él iba a escuchar lo que se decía en torno a Mortemart, y luego se apartaba hacia otro círculo donde hablaba el abate. Para Pierre, educado en el extranjero, aquella velada en casa de Anna Pávlovna era la primera que veía en Rusia. Sabía que toda la intelectualidad de Petersburgo estaba allí reunida, y sus ojos vagaban como los de un niño en una juguetería. Temía constantemente perderse las conversaciones inteligentes que pudiera oír. Al ver las expresiones seguras y elegantes de los rostros allí reunidos, no dejaba de esperar algo especialmente inteligente. Finalmente, se acercó a Morio. La conversación le pareció interesante y se detuvo, esperando la oportunidad de expresar sus pensamientos, como les encanta hacer a los jóvenes.</p>
				</div>"""

with open('tei-source/2600-full.xml', 'r', encoding='utf-8') as f:
    text = f.read()

# find ch2 original
ch2_start = text.find('<div type="version" xml:lang="ru" subtype="original">', text.find('<div type="chapter" n="2">'))

text = text[:ch2_start] + en_text + '\n' + es_text + '\n' + text[ch2_start:]

with open('tei-source/2600-full.xml', 'w', encoding='utf-8') as f:
    f.write(text)
