"""Replace ES ch.90, 91, 92 with clean retranslations from the Russian original."""
import os, xml.etree.ElementTree as ET

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ES_FILE = os.path.join(REPO, 'tei-source', 'tolstoy-leo_war-and-peace_es.xml')
NS = {'tei': 'http://www.tei-c.org/ns/1.0'}

PARAS_90 = [
    'En el estado de ánimo más feliz, al regresar de su viaje al sur, <persName ref="#pierre">Pierre</persName> cumplió su antiguo propósito de visitar a su amigo <persName ref="#andrew">Bolkonsky</persName>, al que no había visto en dos años.',
    '<placeName ref="#bogucharovo">Bogucharovo</placeName> se hallaba en una zona fea y llana, cubierta de campos y bosques de abetos y abedules talados y en pie. El patio de la mansión se encontraba al final de una aldea recta dispuesta junto al camino principal, detrás de un estanque recién cavado y rebosante, con orillas aún sin cubrirse de hierba, en medio de un bosque joven entre el que se alzaban varios pinos grandes.',
    'El patio de la mansión constaba de una era, dependencias, establos, baños, un pabellón y una gran casa de piedra con frontón semicircular, que estaba aún en construcción. Alrededor de la casa se había plantado un jardín joven. Las vallas y las puertas eran sólidas y nuevas; bajo el cobertizo había dos bombas contra incendios y un barril pintado de verde; los caminos eran rectos, los puentes firmes con barandillas. Todo llevaba la huella del orden y la economía. Los siervos que salieron al encuentro, al preguntarles dónde vivía el príncipe, señalaron un pequeño y nuevo pabellón que se alzaba al borde mismo del estanque. El viejo lacayo del príncipe <persName ref="#andrew">Andrei</persName>, <persName ref="#anton">Antón</persName>, apeó a <persName ref="#pierre">Pierre</persName> del carruaje, dijo que el príncipe estaba en casa y lo condujo a un pequeño y limpio zaguán.',
    'A <persName ref="#pierre">Pierre</persName> le sorprendió la modestia de la pequeña aunque limpia casa, en comparación con las espléndidas condiciones en que había visto por última vez a su amigo en <placeName ref="#st-petersburg">Petersburgo</placeName>. Entró a paso vivo en el pequeño vestíbulo sin revocar, que aún olía a pino, y quiso seguir adelante, pero <persName ref="#anton">Antón</persName> corrió de puntillas y llamó a la puerta.',
    '— ¿Qué hay? — se oyó una voz aguda y desagradable.',
    '— Un visitante — respondió <persName ref="#anton">Antón</persName>.',
    '— Que espere — y se escuchó el ruido de una silla que se apartaba. <persName ref="#pierre">Pierre</persName> se acercó rápidamente a la puerta y se encontró cara a cara con el príncipe <persName ref="#andrew">Andrei</persName>, que salía a su encuentro, ceñudo y envejecido. <persName ref="#pierre">Pierre</persName> lo abrazó y, subiéndose las gafas, lo besó en las mejillas y lo miró de cerca.',
    '— Vaya sorpresa, me alegro muchísimo — dijo el príncipe <persName ref="#andrew">Andrei</persName>. <persName ref="#pierre">Pierre</persName> no dijo nada; miraba a su amigo con sorpresa, sin apartar los ojos de él. Le había impresionado el cambio operado en el príncipe <persName ref="#andrew">Andrei</persName>. Las palabras eran cariñosas, había una sonrisa en los labios y en el rostro del príncipe <persName ref="#andrew">Andrei</persName>, pero la mirada era apagada, muerta, a la que, a pesar del visible deseo, el príncipe <persName ref="#andrew">Andrei</persName> no podía dar un brillo alegre y animado. No era que su amigo hubiera adelgazado, palidecido, madurado; sino esa mirada y esa arruga en la frente, que expresaba una larga concentración en una sola cosa, lo que asombraba y alejaba a <persName ref="#pierre">Pierre</persName> hasta que se acostumbró a ellos.',
    'Al reencontrarse tras una larga separación, como siempre sucede, la conversación no podía detenerse mucho tiempo en ningún punto; preguntaban y respondían brevemente sobre cosas de las que ellos mismos sabían que habría que hablar largamente. Por fin la conversación fue poco a poco deteniéndose en lo dicho antes de modo fragmentario, en preguntas sobre la vida pasada, sobre planes para el futuro, sobre el viaje de <persName ref="#pierre">Pierre</persName>, sobre sus ocupaciones, sobre la guerra, etc. Aquella concentración y abatimiento que <persName ref="#pierre">Pierre</persName> había notado en la mirada del príncipe <persName ref="#andrew">Andrei</persName> se expresaba ahora aún con más fuerza en la sonrisa con que le escuchaba, especialmente cuando <persName ref="#pierre">Pierre</persName> hablaba con animada alegría del pasado o del futuro. Era como si el príncipe <persName ref="#andrew">Andrei</persName> hubiera querido, pero no hubiera podido, participar en lo que decía. <persName ref="#pierre">Pierre</persName> empezaba a sentir que ante el príncipe <persName ref="#andrew">Andrei</persName> el entusiasmo, los sueños, las esperanzas de felicidad y bondad no eran apropiados. Le daba vergüenza expresar todos sus nuevos pensamientos masónicos, especialmente los renovados y excitados en él por su último viaje. Se contenía, temía ser ingenuo; pero al mismo tiempo le era irresistible el deseo de mostrar enseguida a su amigo que era ahora un <persName ref="#pierre">Pierre</persName> completamente diferente, mejor que el de <placeName ref="#st-petersburg">Petersburgo</placeName>.',
    '— No puedo decirle cuánto he vivido en este tiempo. Yo mismo no me reconocería.',
    '— Sí, mucho, mucho hemos cambiado los dos desde entonces — dijo el príncipe <persName ref="#andrew">Andrei</persName>.',
    '— ¿Y usted? — preguntaba <persName ref="#pierre">Pierre</persName>. — ¿Cuáles son sus planes?',
    '— ¿Planes? — repitió irónicamente el príncipe <persName ref="#andrew">Andrei</persName>. — ¿Mis planes? — repitió, como si se sorprendiese del significado de semejante palabra. — Pues ya ves, estoy construyendo, quiero para el año que viene mudarme del todo...',
    '<persName ref="#pierre">Pierre</persName> miraba en silencio, con atención, el envejecido rostro de <persName ref="#andrew">Andrei</persName>.',
    '— No, yo pregunto — dijo <persName ref="#pierre">Pierre</persName>... Pero el príncipe <persName ref="#andrew">Andrei</persName> lo interrumpió:',
    '— ¿Qué hay que decir de mí?... Cuéntame, cuéntame tu viaje, todo lo que hiciste allí en tus haciendas.',
    '<persName ref="#pierre">Pierre</persName> empezó a contar lo que había hecho en sus haciendas, procurando en lo posible disimular su participación en las mejoras realizadas. El príncipe <persName ref="#andrew">Andrei</persName> varias veces le sugería a <persName ref="#pierre">Pierre</persName> de antemano lo que iba contando, como si todo lo que había hecho <persName ref="#pierre">Pierre</persName> fuera una historia conocida desde hacía mucho tiempo, y escuchaba no ya sin interés, sino incluso como si le diera vergüenza lo que contaba <persName ref="#pierre">Pierre</persName>.',
    'A <persName ref="#pierre">Pierre</persName> le resultaba incómodo e incluso penoso estar en compañía de su amigo. Se calló.',
    '— Pues mira, alma mía — dijo el príncipe <persName ref="#andrew">Andrei</persName>, a quien evidentemente también le resultaba penoso e incómodo con el huésped —, estoy aquí de bivac, vine solo a echar un vistazo. Hoy mismo me voy de nuevo con mi hermana. Te los presentaré. Tú ya los conoces, según creo — dijo, dando evidentemente conversación al huésped con quien ya no tenía nada en común —. Saldremos después de comer. ¿Quieres ver ahora la hacienda? Salieron y estuvieron paseando hasta la comida, conversando sobre noticias políticas y conocidos comunes, como personas que no son muy íntimas. Con cierta animación e interés el príncipe <persName ref="#andrew">Andrei</persName> habló solo de la nueva hacienda que estaba organizando y la construcción, pero también aquí, en medio de la conversación, en el andamio, cuando el príncipe <persName ref="#andrew">Andrei</persName> le describía a <persName ref="#pierre">Pierre</persName> la futura distribución de la casa, se detuvo de pronto. — En fin, aquí no hay nada interesante, vamos a comer y nos marchamos. — Durante la comida surgió la conversación sobre el matrimonio de <persName ref="#pierre">Pierre</persName>.',
    '— Me sorprendió mucho cuando me enteré — dijo el príncipe <persName ref="#andrew">Andrei</persName>.',
    '<persName ref="#pierre">Pierre</persName> se sonrojó, como se sonrojaba siempre ante esto, y se apresuró a decir:',
    '— Ya te contaré algún día cómo fue todo aquello. Pero ya sabes que todo ha terminado y para siempre.',
    '— ¿Para siempre? — dijo el príncipe <persName ref="#andrew">Andrei</persName>. — Nada dura para siempre.',
    '— ¿Pero sabes cómo terminó todo? ¿Has oído hablar del duelo?',
    '— Sí, también eso pasaste.',
    '— Lo único de lo que doy gracias a Dios es de no haber matado a ese hombre — dijo <persName ref="#pierre">Pierre</persName>.',
    '— ¿Por qué? — dijo el príncipe <persName ref="#andrew">Andrei</persName>. — Matar a un perro rabioso es incluso muy conveniente.',
    '— No, matar a un hombre no es bueno, es injusto...',
    '— ¿Por qué es injusto? — repitió el príncipe <persName ref="#andrew">Andrei</persName>; lo justo y lo injusto no está dado a los hombres para que lo juzguen. Los hombres se han equivocado siempre y seguirán equivocándose, y en nada más que en lo que consideran justo e injusto.',
    '— Es injusto lo que causa mal a otro hombre — dijo <persName ref="#pierre">Pierre</persName>, sintiendo con agrado que por primera vez desde su llegada el príncipe <persName ref="#andrew">Andrei</persName> se animaba y comenzaba a hablar, y quería expresar todo lo que lo había convertido en lo que era ahora.',
    '— ¿Y quién te ha dicho qué es el mal para otro hombre? — preguntó.',
    '— ¿El mal? ¿El mal? — dijo <persName ref="#pierre">Pierre</persName>. — Todos sabemos lo que es el mal para nosotros mismos.',
    '— Sí, lo sabemos; pero el mal que yo conozco para mí mismo no puedo hacérselo a otro hombre — decía el príncipe <persName ref="#andrew">Andrei</persName>, animándose cada vez más, evidentemente deseando exponer a <persName ref="#pierre">Pierre</persName> su nueva visión de las cosas. Hablaba en francés. <foreign xml:lang="fr" n="Solo conozco en la vida dos males verdaderos: el remordimiento y la enfermedad. Y la felicidad no es sino la ausencia de esos dos males.">Je ne connais dans la vie que maux bien réels: c\'est le remord et la maladie. Il n\'est de bien que l\'absence de ces maux.</foreign> Vivir para uno mismo, evitando solo esos dos males: esa es ahora toda mi sabiduría.',
    '— ¿Y el amor al prójimo y el sacrificio propio? — habló <persName ref="#pierre">Pierre</persName>. — ¡No, yo no puedo estar de acuerdo con usted! Vivir solo de tal modo que no hagamos el mal, que no nos arrepintamos, eso no basta. Yo viví así, viví para mí mismo y arruiné mi vida. Y solo ahora, cuando vivo, al menos lo intento — se corrigió <persName ref="#pierre">Pierre</persName> por modestia — vivir para los demás, solo ahora comprendo toda la felicidad de la vida. No, no estoy de acuerdo con usted, y usted tampoco piensa lo que dice. El príncipe <persName ref="#andrew">Andrei</persName> miraba a <persName ref="#pierre">Pierre</persName> en silencio y sonreía con ironía.',
    '— Ya verás a mi hermana, la princesa <persName ref="#princess-mary">Marya</persName>. Os entenderéis — dijo él. — Quizás tengas razón para ti — continuó, tras un breve silencio —; pero cada uno vive a su manera: tú viviste para ti y dices que con eso casi arruinaste tu vida, y solo conociste la felicidad cuando empezaste a vivir para los demás. Y yo experimenté lo contrario. Viví para la gloria. (Pues bien, ¿qué es la gloria? Ese mismo amor a los demás, el deseo de hacer algo por ellos, el deseo de sus alabanzas.) Así pues, viví para los demás, y no solo casi, sino que arruiné del todo mi vida. Y desde entonces estoy más tranquilo, porque vivo solo para mí.',
    '— ¿Y cómo se puede vivir solo para uno? — preguntó <persName ref="#pierre">Pierre</persName> acalorándose. — ¿Y el hijo, y la hermana, y el padre?',
    '— Pero esos soy yo mismo, no son otros — dijo el príncipe <persName ref="#andrew">Andrei</persName>, y los otros, los <emph>prójimos</emph>, <foreign xml:lang="fr" n="el prójimo">le prochain</foreign>, como usted y la princesa <persName ref="#princess-mary">Marya</persName> lo llaman, son la principal fuente de error y maldad. <foreign xml:lang="fr" n="El prójimo">Le prochain</foreign> son tus mujiks de Kiev, a quienes quieres hacer el bien.',
    'Y miró a <persName ref="#pierre">Pierre</persName> con una mirada burlona y desafiante. Al parecer lo provocaba.',
    '— ¿Está bromeando? — decía <persName ref="#pierre">Pierre</persName>, animándose cada vez más. — ¿Qué error y qué mal puede haber en que yo haya querido — muy poco y mal ejecutado, pero haya querido — hacer el bien, y haya hecho algo, aunque pequeño? ¿Qué mal puede haber en que la gente desgraciada, nuestros mujiks, personas como nosotros, que crecen y mueren sin más idea de Dios y de la verdad que ritos y oraciones sin sentido, reciban la enseñanza de las creencias consoladoras de la vida futura, la retribución, la recompensa, el consuelo? ¿Qué mal y engaño hay en que la gente muera de enfermedad sin ayuda, cuando es tan fácil ayudarles materialmente, y yo les dé un médico, un hospital, un asilo para los ancianos? ¿Y no es un beneficio tangible e indudable que el mujik, la mujer con el niño no tengan reposo ni de día ni de noche, y yo les dé descanso y ocio?... — decía <persName ref="#pierre">Pierre</persName>, con precipitación y ceceo. — Y esto lo he hecho, aunque mal, aunque poco, pero algo he hecho para ello, y no solo no me convencerá usted de que lo que hice estuvo mal, sino que tampoco me convencerá de que usted mismo no lo cree así. Y lo principal — continuó <persName ref="#pierre">Pierre</persName> —, que esto es lo que sé y sé con certeza: que el goce de hacer ese bien es la única felicidad verdadera en la vida.',
    '— Sí, si se plantea la pregunta así, eso es otra cosa — dijo el príncipe <persName ref="#andrew">Andrei</persName>. — Yo construyo una casa, planto un jardín, y tú un hospital. Ambas cosas pueden servir de pasatiempo. Pero lo que es justo, lo que es bueno, déjalo juzgar al que todo lo sabe, no a nosotros. Bueno, si quieres discutir — añadió —, pues venga. Salieron de la mesa y se sentaron en el porche que hacía las veces de balcón.',
    '— Pues discutamos — dijo el príncipe <persName ref="#andrew">Andrei</persName>. — Tú hablas de escuelas — continuó, doblando un dedo —, de enseñanzas y demás, es decir, quieres sacar a ese hombre — dijo, señalando a un mujik que pasaba descubriéndose ante ellos — de su estado animal y darle necesidades morales; pero a mí me parece que la única felicidad posible es la felicidad animal, y tú se la quieres quitar. Le envidio a él, y tú quieres convertirlo en mí, pero sin darle mis medios. Otra cosa: dices aligerar su trabajo. Pero a mi juicio el trabajo físico es para él la misma necesidad, la misma condición de su existencia, que para mí y para ti el trabajo mental. Tú no puedes no pensar. Me acuesto a las tres, me vienen pensamientos y no puedo dormir, me doy vueltas, no duermo hasta la mañana porque pienso y no puedo no pensar, igual que él no puede no arar, no segar; de lo contrario, irá a la taberna o caerá enfermo. Así como yo no soportaría su terrible trabajo físico y moriría en una semana, él no soporta mi ocio físico; engordará y morirá. Tercero — ¿qué más dijiste?',
    'El príncipe <persName ref="#andrew">Andrei</persName> dobló el tercer dedo.',
    '— Ah, sí, hospitales, medicina. Tiene una apoplejía, se muere, y tú le has sangrado, le has curado. Quedará cojo diez años, una carga para todos. Mucho más tranquilo y más sencillo habría sido para él morir. Nacerán otros, y tantos hay. Si lamentaras que te falta un trabajador — como yo lo veo —, eso es otra cosa; pero tú quieres curarle por amor a él. Y eso no lo necesita. Y además, ¡qué imaginación la de creer que la medicina ha curado a alguien alguna vez! ¡Matar, eso sí! — dijo, frunciendo el ceño con enojo y apartándose de <persName ref="#pierre">Pierre</persName>.',
    'El príncipe <persName ref="#andrew">Andrei</persName> exponía sus pensamientos con tal claridad y precisión que se veía que los había reflexionado más de una vez, y hablaba con soltura y rapidez, como un hombre que no ha hablado en mucho tiempo. Su mirada se animaba tanto más cuanto más desesperados eran sus juicios.',
    '— ¡Ah, esto es terrible, terrible! — dijo <persName ref="#pierre">Pierre</persName>. — Yo no comprendo solo cómo puede vivir con esos pensamientos. Yo he tenido esos mismos momentos, fue recientemente, en Moscú y en el camino; pero entonces me hundo a tal grado que no vivo, todo me resulta repugnante... lo principal, yo mismo. Entonces no como, no me lavo... bueno, ¿y usted?...',
    '— ¿Para qué no lavarse? No es limpio — dijo el príncipe <persName ref="#andrew">Andrei</persName>; al contrario, hay que procurar hacer la vida lo más agradable posible. Vivo y no tengo la culpa de ello, así que hay que vivir de algún modo mejor hasta morir, sin molestar a nadie.',
    '— ¿Pero qué le impulsa a vivir con esos pensamientos? Se quedaría uno sentado, inmóvil, sin hacer nada...',
    '— La vida no te deja en paz de todas formas. Yo quisiera no hacer nada, pero, por un lado, la nobleza local me honró con su elección como mariscal: a duras penas me libré. No podían comprender que en mí no hay lo que se necesita para eso, esa conocida vulgaridad bondadosa y solícita que se requiere. Luego está esta casa, que había que construir para tener un rincón donde estar tranquilo. Ahora la milicia.',
    '— ¿Por qué no sirve en el ejército?',
    '— ¡Después de <placeName ref="#austerlitz">Austerlitz</placeName>! — dijo con tristeza el príncipe <persName ref="#andrew">Andrei</persName>. — No; muchas gracias, me he prometido no servir más en el ejército ruso activo. Y no lo haré, aunque <persName ref="#bonaparte">Bonaparte</persName> estuviese aquí, cerca de <placeName ref="#smolensk">Smolensk</placeName>, amenazando las <placeName ref="#bald_hills">Colinas Calvas</placeName>, incluso entonces no serviría en el ejército ruso. Bueno, eso ya te lo dije — continuó el príncipe <persName ref="#andrew">Andrei</persName>, serenándose —. Ahora la milicia, mi padre es comandante en jefe del tercer distrito, y el único medio de librarme del servicio es estar con él.',
    '— ¿De modo que sirve?',
    '— Sirvo. — Guardó silencio un momento.',
    '— ¿Y para qué sirve entonces?',
    '— Pues por esto. Mi padre es uno de los hombres más notables de su siglo. Pero está envejeciendo y no es que sea cruel, sino que tiene un temperamento demasiado activo. Es terrible con su costumbre de poder ilimitado, y ahora con ese poder otorgado por el <persName ref="#emperor-alexander">soberano</persName> al comandante en jefe de la milicia. Si hace dos semanas hubiera llegado dos horas tarde, habría mandado ahorcar al secretario de protocolo en <placeName ref="#yukhnov">Yukhnov</placeName> — dijo el príncipe <persName ref="#andrew">Andrei</persName> con una sonrisa —; así que sirvo porque nadie más que yo tiene influencia sobre mi padre, y aquí y allá le salvo de algún acto del que después él mismo sufriría.',
    '— ¡Ah, pues ya ve!',
    '— Sí, <foreign xml:lang="fr" n="pero no de la manera que usted lo entiende">mais ce n\'est pas comme vous l\'entendez,</foreign> continuó el príncipe <persName ref="#andrew">Andrei</persName>. — Yo ni entonces ni ahora deseaba lo más mínimo bien a ese miserable secretario que robó unas botas a los milicianos; incluso me alegraría mucho verle ahorcado, pero me da lástima mi padre, es decir, de nuevo yo mismo.',
    'El príncipe <persName ref="#andrew">Andrei</persName> se animaba cada vez más. Sus ojos brillaban febrilmente mientras intentaba demostrar a <persName ref="#pierre">Pierre</persName> que en ninguna de sus acciones había habido jamás un deseo de hacer el bien al prójimo.',
    '— Bueno, pues quieres liberar a los campesinos — continuó. — Eso está muy bien; pero no para ti (creo que tú no has azotado a nadie ni enviado a nadie a Siberia) y menos aún para los campesinos. Si les golpean, les azotan, les envían a Siberia, creo que no están peor por ello. En Siberia lleva esa misma vida bestial, las cicatrices del cuerpo se curan, y será igual de feliz que antes. Pero esto es necesario para esas personas que perecen moralmente, que acumulan remordimiento, que lo sofocan y se embrutecen porque tienen la posibilidad de castigar con razón o sin ella. A esos es a quienes me da lástima, y por quienes yo querría liberar a los campesinos. Quizás tú no lo hayas visto, pero yo he visto cómo personas buenas, criadas en esas tradiciones de poder ilimitado, con los años, cuando se vuelven más irritables, se hacen crueles, rudas, lo saben, no pueden contenerse, y se van haciendo más y más desdichadas.',
    'El príncipe <persName ref="#andrew">Andrei</persName> decía esto con tal entusiasmo que <persName ref="#pierre">Pierre</persName> pensó involuntariamente que esos pensamientos se los había sugerido a <persName ref="#andrew">Andrei</persName> su padre. No le respondió.',
    '— Así que por eso me da lástima: la dignidad humana, la paz de conciencia, la pureza, y no sus espaldas y frentes, que por mucho que se azoten, por mucho que se afeiten, seguirán siendo las mismas espaldas y frentes.',
    '— ¡No, no y mil veces no! Jamás podré estar de acuerdo con usted — dijo <persName ref="#pierre">Pierre</persName>.',
]

PARAS_91 = [
    'Esa tarde el príncipe <persName ref="#andrew">Andrei</persName> y <persName ref="#pierre">Pierre</persName> subieron al carruaje y partieron hacia las <placeName ref="#bald_hills">Colinas Calvas</placeName>. El príncipe <persName ref="#andrew">Andrei</persName>, mirando a <persName ref="#pierre">Pierre</persName>, interrumpía de cuando en cuando el silencio con palabras que demostraban que estaba de buen humor.',
    'Le fue hablando, señalando los campos, de sus mejoras agrícolas.',
    '<persName ref="#pierre">Pierre</persName> guardaba un sombrío silencio, respondía con monosílabos y parecía absorto en sus pensamientos.',
    '<persName ref="#pierre">Pierre</persName> pensaba que el príncipe <persName ref="#andrew">Andrei</persName> era desdichado, que estaba en un error, que no conocía la verdadera luz y que <persName ref="#pierre">Pierre</persName> debía acudir en su ayuda, iluminarle y levantarle. Pero en cuanto <persName ref="#pierre">Pierre</persName> imaginaba cómo y qué le diría, presagiaba que el príncipe <persName ref="#andrew">Andrei</persName> con una sola palabra, con un solo argumento, echaría por tierra toda su doctrina, y le daba miedo empezar, le daba miedo exponer su querida santidad a la posibilidad del ridículo.',
    '— No, ¿por qué piensa usted...? — comenzó de pronto <persName ref="#pierre">Pierre</persName>, bajando la cabeza y adoptando el aire de un toro que embiste, ¿por qué piensa usted así? No debe pensar de ese modo.',
    '— ¿En qué pienso? — preguntó el príncipe <persName ref="#andrew">Andrei</persName> con sorpresa.',
    '— En la vida, en el destino del hombre. No puede ser. Yo pensaba lo mismo, y me salvó, ¿sabe usted qué? La masonería. No, no sonría. La masonería no es una secta religiosa ni de ritos, como yo también creía, sino que la masonería es la mejor, la única expresión de los mejores y eternos aspectos de la humanidad. — Y comenzó a exponerle al príncipe <persName ref="#andrew">Andrei</persName> la masonería tal como él la entendía.',
    'Dijo que la masonería es la doctrina del cristianismo, liberado de las ataduras estatales y religiosas; la doctrina de la igualdad, la fraternidad y el amor.',
    '— Solo nuestra santa hermandad tiene un sentido verdadero en la vida; todo lo demás es un sueño — decía <persName ref="#pierre">Pierre</persName>. — Comprenda, amigo mío, que fuera de esta unión todo está lleno de mentira y falsedad, y estoy de acuerdo con usted en que a un hombre inteligente y bueno no le queda otra cosa que, como usted, sobrellevar la vida procurando solo no molestar a los demás. Pero asimile nuestras creencias fundamentales, ingrese en nuestra hermandad, déjese guiar, y enseguida se sentirá, como yo me sentí, parte de esa enorme e invisible cadena cuyo comienzo se esconde en los cielos — decía <persName ref="#pierre">Pierre</persName>.',
    'El príncipe <persName ref="#andrew">Andrei</persName>, en silencio, con la vista al frente, escuchaba el discurso de <persName ref="#pierre">Pierre</persName>. Varias veces, al no oír por el ruido del carruaje, preguntó a <persName ref="#pierre">Pierre</persName> las palabras que no había entendido. Por el brillo especial que se encendió en los ojos del príncipe <persName ref="#andrew">Andrei</persName>, y por su silencio, <persName ref="#pierre">Pierre</persName> vio que sus palabras no eran en vano, que el príncipe <persName ref="#andrew">Andrei</persName> no le interrumpiría ni se reiría de sus palabras.',
    'Se acercaron a un río desbordado que debían cruzar en balsa. Mientras embarcaban el carruaje y los caballos, pasaron a la balsa.',
    'El príncipe <persName ref="#andrew">Andrei</persName>, apoyado en la borda, miraba en silencio la extensión brillante bajo el sol poniente.',
    '— ¿Y bien, qué piensa usted de todo esto? — preguntó <persName ref="#pierre">Pierre</persName>. — ¿Por qué calla?',
    '— ¿Qué pienso yo? Te escuchaba. Todo eso es cierto — dijo el príncipe <persName ref="#andrew">Andrei</persName>. — Pero dices: entra en nuestra hermandad, y te mostraremos el fin de la vida y el destino del hombre, y las leyes que rigen el mundo. Pero ¿quiénes somos? Los hombres. ¿Por qué lo sabéis vosotros todo? ¿Por qué solo yo no veo lo que vosotros veis? Vosotros veis en la tierra el reino del bien y de la verdad, y yo no lo veo.',
    '<persName ref="#pierre">Pierre</persName> le interrumpió.',
    '— ¿Cree usted en la vida futura? — preguntó.',
    '— ¿En la vida futura? — repitió el príncipe <persName ref="#andrew">Andrei</persName>, pero <persName ref="#pierre">Pierre</persName> no le dio tiempo de responder y tomó esa repetición como una negación, tanto más cuanto que conocía las anteriores convicciones ateas del príncipe <persName ref="#andrew">Andrei</persName>.',
    '— Dice usted que no puede ver el reino del bien y de la verdad en la tierra. Y yo tampoco lo vi, y no se puede ver si miramos nuestra vida como el fin de todo. En la <emph>tierra,</emph> precisamente en esta tierra — <persName ref="#pierre">Pierre</persName> señaló el campo —, no hay verdad: todo es mentira y maldad; pero en el mundo, en el mundo entero, hay un reino de verdad, y nosotros somos ahora hijos de la tierra, y para siempre hijos de todo el mundo. ¿Acaso no siento en mi alma que formo parte de ese todo vasto y armonioso? ¿Acaso no siento que en ese inmenso e incontable número de seres en quienes se manifiesta la Divinidad — la fuerza suprema, llámela como quiera —, formaré un eslabón, un peldaño de los seres inferiores a los superiores? Si veo, si veo con claridad esa escalera que conduce de la planta al hombre, ¿por qué he de suponer que esa escalera se rompe conmigo y no sigue adelante y adelante? Siento que no solo no puedo desaparecer, como nada desaparece en el mundo, sino que siempre seré y siempre he sido. Siento que junto a mí, por encima de mí, viven espíritus y que en este mundo hay verdad.',
    '— Sí, esa es la doctrina de <persName ref="#herder">Herder</persName> — dijo el príncipe <persName ref="#andrew">Andrei</persName> —, pero no es eso, alma mía, lo que me convencerá, sino la vida y la muerte, eso es lo que convence. Lo que convence es cuando ves a un ser querido, ligado a ti, ante el que eras culpable y esperabas justificarte — el príncipe <persName ref="#andrew">Andrei</persName> tembló de voz y se volvió — y de pronto ese ser sufre, padece y deja de existir... ¿Por qué? No puede ser que no haya respuesta. Y yo creo que la hay... Eso es lo que convence, eso es lo que me convenció — dijo el príncipe <persName ref="#andrew">Andrei</persName>.',
    '— ¡Pues sí, pues sí! — decía <persName ref="#pierre">Pierre</persName>. — ¿No digo yo lo mismo?',
    '— No. Solo digo que no son los argumentos los que te convencen de la necesidad de la vida futura, sino cuando caminas por la vida de la mano de una persona y de pronto esa persona desaparece <emph>allí en la nada</emph>, y tú mismo te detienes ante ese abismo y lo miras. Y yo lo miré...',
    '— ¡Bueno, pues! ¿Sabe usted que hay <emph>algo allí</emph> y que hay <emph>alguien?</emph> Allí está la vida futura. Alguien hay: Dios.',
    'El príncipe <persName ref="#andrew">Andrei</persName> no respondió. El carruaje y los caballos hacía rato que habían sido llevados a la otra orilla y ya enganchados, y el sol se había ocultado a medias, y la escarcha de la tarde cubría de estrellas los charcos junto al vado, mientras <persName ref="#pierre">Pierre</persName> y <persName ref="#andrew">Andrei</persName>, con asombro de los lacayos, cocheros y barqueros, seguían aún de pie en la balsa hablando.',
    '— Si hay Dios y hay vida futura, entonces hay verdad, hay virtud; y la mayor felicidad del hombre consiste en esforzarse por alcanzarlas. Hay que vivir, hay que amar, hay que creer — decía <persName ref="#pierre">Pierre</persName> —, que no vivimos solo ahora en este pedazo de tierra, sino que hemos vivido y viviremos eternamente allí en todo — señaló el cielo —. El príncipe <persName ref="#andrew">Andrei</persName> estaba apoyado en la borda de la balsa y, escuchando a <persName ref="#pierre">Pierre</persName>, sin apartar los ojos, miraba el reflejo rojo del sol sobre la extensión azulada. <persName ref="#pierre">Pierre</persName> calló. Estaba en completo silencio. La balsa hacía rato que había atracado, y solo las olas de la corriente golpeaban con un leve sonido el fondo de la balsa. Al príncipe <persName ref="#andrew">Andrei</persName> le parecía que ese batir de olas repetía las palabras de <persName ref="#pierre">Pierre</persName>: «verdad, créelo».',
    'El príncipe <persName ref="#andrew">Andrei</persName> suspiró, y con una mirada radiante, infantil y tierna miró el encendido y entusiasta, aunque cada vez más tímido, rostro de <persName ref="#pierre">Pierre</persName>, su amigo de mayor rango.',
    '— ¡Sí, si así fuera! — dijo. — Bueno, vamos a sentarnos — añadió el príncipe <persName ref="#andrew">Andrei</persName>, y al salir de la balsa miró al cielo que <persName ref="#pierre">Pierre</persName> le había señalado, y por primera vez, después de <placeName ref="#austerlitz">Austerlitz</placeName>, vio aquel cielo alto y eterno que había visto tendido en el campo de <placeName ref="#austerlitz">Austerlitz</placeName>, y algo que había estado dormido desde hacía mucho, algo mejor que había en él, de pronto se despertó en su alma con alegría y juventud. Ese sentimiento desapareció en cuanto el príncipe <persName ref="#andrew">Andrei</persName> volvió a entrar en las condiciones habituales de la vida, pero él sabía que ese sentimiento, que no sabía cómo desarrollar, vivía en él. El encuentro con <persName ref="#pierre">Pierre</persName> fue para el príncipe <persName ref="#andrew">Andrei</persName> una época con la que, aunque en apariencia todo seguía igual, en su mundo interior comenzaba una vida nueva.',
]

PARAS_92 = [
    'Ya anochecía cuando el príncipe <persName ref="#andrew">Andrei</persName> y <persName ref="#pierre">Pierre</persName> llegaron a la entrada principal de la casa de <placeName ref="#bald_hills">Lysogorie</placeName>. Mientras se acercaban, el príncipe <persName ref="#andrew">Andrei</persName> con una sonrisa llamó la atención de <persName ref="#pierre">Pierre</persName> sobre el revuelo producido en el portal trasero. Una anciana encorvada con un zurrón a la espalda y un hombre de baja estatura con hábito negro y cabello largo, al ver entrar el carruaje, salieron corriendo hacia la puerta. Dos mujeres salieron corriendo tras ellos, y los cuatro, mirando hacia el carruaje, entraron asustados corriendo por el portal trasero.',
    '— Son los peregrinos de Masha — dijo el príncipe <persName ref="#andrew">Andrei</persName>. — Nos han tomado por padre. Y esto es lo único en que ella no le obedece: él ordena echar a estos vagabundos, y ella los acoge.',
    '— ¿Y qué son los peregrinos? — preguntó <persName ref="#pierre">Pierre</persName>.',
    'El príncipe <persName ref="#andrew">Andrei</persName> no tuvo tiempo de responderle. Los criados salieron a recibirle y preguntó dónde estaba el viejo príncipe y si se le esperaba pronto.',
    'El viejo príncipe seguía en la ciudad y se le esperaba de un momento a otro.',
    'El príncipe <persName ref="#andrew">Andrei</persName> condujo a <persName ref="#pierre">Pierre</persName> a sus habitaciones, que siempre le esperaban en perfecto orden en la casa de su padre, y él mismo fue al cuarto de los niños.',
    '— Vamos a ver a mi hermana — dijo el príncipe <persName ref="#andrew">Andrei</persName>, al volver junto a <persName ref="#pierre">Pierre</persName>. — Aún no la he visto; ella ahora está escondida, sentada con sus peregrinos. Tiene su merecido; se avergonzará, y tú verás a los peregrinos. <foreign xml:lang="fr" n="Esto es curioso, palabra.">C\'est curieux, ma parole.</foreign>',
    '— <foreign xml:lang="fr" n="¿Qué es eso de">Qu\'est ce que c\'est que</foreign> los peregrinos? — preguntó <persName ref="#pierre">Pierre</persName>.',
    '— Ya lo verás.',
    'La princesa <persName ref="#princess-mary">Marya</persName> se turbó visiblemente y se ruborizó por manchas cuando entraron. En su acogedora habitación con lámparas ante los iconos, en el sofá, junto al samovar, estaba sentado a su lado un joven de nariz larga y cabello largo, vestido con hábito monástico.',
    'En un sillón próximo estaba sentada una anciana delgada y arrugada, de expresión mansa en su rostro de niña.',
    '— <foreign xml:lang="fr" n="— Andryusha, ¿por qué no me avisaste?">André, pourquoi ne pas m\'avoir prévenu?</foreign> — dijo con manso reproche, plantándose ante sus peregrinos como la gallina ante sus polluelos.',
    '— <foreign xml:lang="fr" n="— ¡Qué contenta estoy de verle! Me alegro mucho.">Charmée de vous voir. Je suis très contente de vous voir,</foreign> — le dijo a <persName ref="#pierre">Pierre</persName> mientras él le besaba la mano. Le conocía desde niño, y ahora su amistad con <persName ref="#andrew">Andrei</persName>, su difunta esposa y, sobre todo, su rostro bondadoso y sencillo la inclinaban hacia él. Le miraba con sus hermosos ojos radiantes y parecía decirle: «Le quiero mucho, pero por favor no se ría de <emph>los míos</emph>». Tras intercambiar las primeras frases de saludo, se sentaron.',
    '— ¡Ah, y está Ivanushka! — dijo el príncipe <persName ref="#andrew">Andrei</persName>, señalando con una sonrisa al joven peregrino.',
    '— ¡André! — dijo la princesa <persName ref="#princess-mary">Marya</persName> suplicante.',
    '— <foreign xml:lang="fr" n="— Sabe usted, esto es una mujer,">Il faut que vous sachiez que c\'est une femme,</foreign> — le dijo <persName ref="#andrew">Andrei</persName> a <persName ref="#pierre">Pierre</persName>.',
    '— <foreign xml:lang="fr" n="— ¡Andryusha, por el amor de Dios!">André, au nom de Dieu!</foreign> — repitió la princesa <persName ref="#princess-mary">Marya</persName>.',
    'Era evidente que la actitud burlona del príncipe <persName ref="#andrew">Andrei</persName> hacia los peregrinos y la inútil defensa de ellos por parte de la princesa <persName ref="#princess-mary">Marya</persName> eran relaciones habituales y establecidas entre ellos.',
    '— <foreign xml:lang="fr" n="— Pero, amiga mía, deberías agradecerme que le explique a Pierre tu intimidad con este joven.">Mais, ma bonne amie, vous devriez au contraire m\'être reconaissante de ce que j\'explique à Pierre votre intimité avec ce jeune homme.</foreign>',
    '— <foreign xml:lang="fr" n="— ¿De veras?">Vraiment?</foreign> — dijo <persName ref="#pierre">Pierre</persName> con curiosidad y seriedad (por lo que la princesa <persName ref="#princess-mary">Marya</persName> le estaba especialmente agradecida), mirando a través de las gafas el rostro de Ivanushka, quien, al darse cuenta de que hablaban de él, miró a todos con ojos astutos.',
    'La princesa <persName ref="#princess-mary">Marya</persName> se había turbado del todo en vano por <emph>los suyos</emph>. Estos no tenían ningún miedo. La anciana, con los ojos bajos pero mirando de reojo a los que entraban, había puesto la taza boca abajo sobre el platillo y colocado a un lado un terrón de azúcar a medio morder, y estaba sentada tranquila e inmóvil en su sillón, esperando que le ofrecieran más té. Ivanushka, bebiendo del platillo, miraba a los jóvenes por debajo de sus cejas con ojos astutos y femeninos.',
    '— ¿Dónde estuviste, en Kiev? — preguntó el príncipe <persName ref="#andrew">Andrei</persName> a la anciana.',
    '— Estuve, padrecito — respondió la anciana locuazmente —, en las mismas Navidades tuve el honor de comulgar los santos misterios celestiales junto a los santos mártires. Y ahora desde Kolyazin, padrecito, ha brotado una gran gracia...',
    '— ¿Y va contigo Ivanushka?',
    '— Yo voy solo, sostén — dijo Ivanushka, esforzándose por hablar en voz grave. — Solo en Yukhnov nos juntamos con Pelagueyushka...',
    'Pelagueyushka interrumpió a su compañero; evidentemente quería contar lo que había visto.',
    '— En Kolyazin, padrecito, ha brotado una gran gracia.',
    '— ¿Qué, son reliquias nuevas? — preguntó el príncipe <persName ref="#andrew">Andrei</persName>.',
    '— Basta, Andrei — dijo la princesa <persName ref="#princess-mary">Marya</persName>. — No cuentes, Pelagueyushka.',
    '— ¿Por qué no, madre, por qué no contar? Le quiero. Es bueno. Elegido por Dios, él me dio, bienhechor, diez rublos, lo recuerdo. Como estuve en Kiev y me dice Kiryusha, el loco de Dios — un hombre verdaderamente de Dios, camina descalzo invierno y verano —: «¿Qué andas sin ton ni son? Ve a Kolyazin, allí hay una imagen milagrosa, la santa madrecita Virgen se ha manifestado». Con esas palabras me despedí de los mártires y me puse en camino...',
    'Todos guardaron silencio; solo la peregrina hablaba con voz mesurada, aspirando el aire.',
    '— Llego, padrecito mío, y la gente me dice: una gran gracia se ha manifestado, de la mejilla de la santa madrecita Virgen mana el santo óleo...',
    '— Bueno, bueno, ya lo contarás luego — dijo la princesa <persName ref="#princess-mary">Marya</persName>, ruborizándose.',
    '— Permítame que le pregunte — dijo <persName ref="#pierre">Pierre</persName>. — ¿Lo viste tú misma? — preguntó.',
    '— ¿Cómo no, padrecito, yo misma lo he visto y honrado. Tal resplandor hay en el santo rostro, como una luz celestial, y de la mejilla de la madrecita así gotea y gotea...',
    '— Pero si eso es un engaño — dijo ingenuamente <persName ref="#pierre">Pierre</persName>, que había estado escuchando atentamente a la peregrina.',
    '— ¡Ay, padrecito, lo que dices! — dijo Pelagueyushka con espanto, volviéndose a la princesa <persName ref="#princess-mary">Marya</persName> en busca de protección.',
    '— Están engañando al pueblo — repitió.',
    '— ¡Señor Jesucristo! — dijo la peregrina santiguándose. — Oh, no digas eso, padrecito. Así un general no creía, dijo: «Los monjes engañan», y nada más decirlo, se quedó ciego. Y soñó que la Madrecita Pechersk se le aparecía y le decía: «Cree en mí, te sanaré». Y se puso a pedir: «Llevadle, llevadle» a ella. Esto te lo digo con la verdad, yo misma lo vi. Le llevaron ciego, directamente a ella; se acercó, cayó y dice: «¡Sáname! Te daré, dice, lo que me dio el zar». Yo misma lo vi, padrecito: la estrella estaba incrustada en ella. Y, ¿qué quieres?, ¡recobró la vista! Mal está decir eso. Dios castigará — se volvió hacia <persName ref="#pierre">Pierre</persName> en tono admonitorio.',
    '— ¿Cómo fue a parar la estrella al icono? — preguntó <persName ref="#pierre">Pierre</persName>.',
    '— ¿Y han ascendido a nuestra madrecita a general? — dijo el príncipe <persName ref="#andrew">Andrei</persName> sonriendo.',
    'Pelagueyushka palideció de pronto y juntó las manos.',
    '— ¡Padrecito, padrecito, es pecado lo que dices, tienes un hijo! — dijo, pasando de golpe de la palidez al vivo color.',
    '— Padrecito, ¿cómo has podido decir eso? Dios te perdone. — Se persignó. — Señor, perdónale. Madrecita, ¿qué es esto? — se dirigió a la princesa <persName ref="#princess-mary">Marya</persName>. Se levantó y, casi llorando, empezó a recoger su bolsa. Evidentemente estaba asustada y avergonzada a la vez de haber disfrutado de la hospitalidad en una casa donde podían decir tales cosas, y le daba pena tener que perder ahora esa hospitalidad.',
    '— ¿A qué viene eso? — dijo la princesa <persName ref="#princess-mary">Marya</persName>. — ¿Para qué has venido a verme?...',
    '— No, Pelagueyushka, estaba bromeando — dijo <persName ref="#pierre">Pierre</persName>. — <foreign xml:lang="fr" n="— Princesa, se lo juro, no era mi intención ofenderla,">Princesse, ma parole, je n\'ai pas voulu l\'offenser,</foreign> solo fue broma. No pienses, era broma — dijo, sonriendo tímidamente y deseando reparar la ofensa.',
    'Pelagueyushka se detuvo desconfiada, pero en el rostro de <persName ref="#pierre">Pierre</persName> había tal sinceridad de arrepentimiento, y el príncipe <persName ref="#andrew">Andrei</persName> miraba con tanta mansedumbre ora a Pelagueyushka ora a <persName ref="#pierre">Pierre</persName>, que ella se fue calmando poco a poco.',
]

HEADS = {
    90: 'Volume II, Part Two, Chapter XI',
    91: 'Volume II, Part Two, Chapter XII',
    92: 'Volume II, Part Two, Chapter XIII',
}


def build_block(n, paras):
    lines = [f'<div type="chapter" n="{n}">']
    lines.append(f'        <head>{HEADS[n]}</head>')
    lines.append('        <div type="version" xml:lang="es" subtype="translation-es">')
    for p in paras:
        lines.append(f'          <p>{p}</p>')
    lines.append('        </div>')
    lines.append('      </div>')
    return '\n'.join(lines)


def chapter_span(content, n):
    marker = f'<div type="chapter" n="{n}">'
    start = content.find(marker)
    if start == -1:
        raise ValueError(f'Chapter {n} not found')
    nxt = content.find('<div type="chapter"', start + len(marker))
    if nxt == -1:
        # last chapter: find closing body/text tag
        nxt = content.find('</body>', start)
    if nxt == -1:
        raise ValueError(f'End of chapter {n} not found')
    return start, nxt


with open(ES_FILE, encoding='utf-8') as f:
    content = f.read()

# Validate paragraph counts before replacing
root = ET.fromstring(content)
NS2 = {'tei': 'http://www.tei-c.org/ns/1.0'}
for n, paras in [(90, PARAS_90), (91, PARAS_91), (92, PARAS_92)]:
    old_count = 0
    for ch in root.findall('.//tei:div[@type="chapter"]', NS2):
        if ch.get('n') == str(n):
            old_count = len(ch.findall('.//tei:p', NS2))
    print(f'Ch.{n}: replacing {old_count} old paragraphs with {len(paras)} new paragraphs')

for n, paras in [(90, PARAS_90), (91, PARAS_91), (92, PARAS_92)]:
    block = build_block(n, paras)
    start, end = chapter_span(content, n)
    content = content[:start] + block + '\n\n      ' + content[end:]

with open(ES_FILE, 'w', encoding='utf-8', newline='') as f:
    f.write(content)

print('Done. Validating XML...')
try:
    ET.parse(ES_FILE)
    print('XML is valid.')
except ET.ParseError as e:
    print(f'XML ERROR: {e}')
